### ISSUE TITLE
[Bug] Multinode Llama 3.1 405B fp8

### ISSUE THREAD

**Issue by matthew-hippocratic** [sgl-project/sglang#1012]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.

### Describe the bug

I can run Llama 3.1 405B-fp8 on one node successfully (from sglang container -- see next comment), but when I try to deploy it on two nodes for tp=16, I see the following issue after loading the model successfully (nodes are connected fine too as well):

```
Exception in run_tp_server:
Traceback (most recent call last):
  File "/workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 772, in run_tp_server
    model_server = ModelTpServer(
  File "/workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 94, in __init__
    self.model_runner = ModelRunner(
  File "/workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 139, in __init__
    self.init_cuda_graphs()
  File "/workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 344, in init_cuda_graphs
    self.cuda_graph_runner.capture(batch_size_list)
  File "/workspace/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 148, in capture
    ) = self.capture_one_batch_size(bs, forward)
  File "/workspace/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 211, in capture_one_batch_size
    run_once()
  File "/workspace/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 208, in run_once
    return forward(input_ids, input_metadata.positions, input_metadata)
TypeError: LlamaForCausalLM.forward() missing 1 required positional argument: 'attn_metadata'
```

After looking through the source code, it seems like the vllm llama model config (which's forward method takes a mandatory 'attn_metadata') is being used and then sglang isn't passing these params during the forward call. Not sure if this is the issue, but it's all I can figure out for now

### Reproduction

vllm - latest (0.5.4)
sglang - latest

On the head node, running:
`python3 -m sglang.launch_server --model-path meta-llama/Meta-Llama-3.1-405B-Instruct-FP8 --tp 16 --nccl-init-addr <head_node_ip>:8000 --nnodes 2 --node-rank 0`

On the worker node, running:
`python3 -m sglang.launch_server --model-path meta-llama/Meta-Llama-3.1-405B-Instruct-FP8 --tp 16 --nccl-init-addr <head_node_ip>:8000 --nnodes 2 --node-rank 1`

### Environment

```Shell
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA H100 80GB HBM3
GPU 0,1,2,3,4,5,6,7 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.3, V12.3.107
CUDA Driver Version: 535.161.08
PyTorch: 2.4.0+cu121
flashinfer: 0.1.3+cu121torch2.4
triton: 3.0.0
transformers: 4.44.0
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.24.4
aiohttp: 3.9.1
fastapi: 0.112.0
hf_transfer: 0.1.8
huggingface_hub: 0.24.5
interegular: 0.3.3
packaging: 23.2
PIL: 9.5.0
psutil: 5.9.4
pydantic: 2.5.2
uvicorn: 0.30.5
uvloop: 0.19.0
zmq: 25.1.2
multipart: 0.0.9
openai: 1.40.0
anthropic: 0.33.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV18    NV18    NV18    NV18    NV18    NV18    NV18    0-47    0               N/A
GPU1    NV18     X      NV18    NV18    NV18    NV18    NV18    NV18    0-47    0               N/A
GPU2    NV18    NV18     X      NV18    NV18    NV18    NV18    NV18    0-47    0               N/A
GPU3    NV18    NV18    NV18     X      NV18    NV18    NV18    NV18    0-47    0               N/A
GPU4    NV18    NV18    NV18    NV18     X      NV18    NV18    NV18    48-95   1               N/A
GPU5    NV18    NV18    NV18    NV18    NV18     X      NV18    NV18    48-95   1               N/A
GPU6    NV18    NV18    NV18    NV18    NV18    NV18     X      NV18    48-95   1               N/A
GPU7    NV18    NV18    NV18    NV18    NV18    NV18    NV18     X      48-95   1               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 1048576
```

**Comment by matthew-hippocratic** [comment]
After running:
`python3 -m sglang.launch_server --model-path meta-llama/Meta-Llama-3.1-405B-Instruct-FP8 --tp 8`

...getting the same bug in the model forward on single node:

```
Exception in run_tp_server:
Traceback (most recent call last):
  File "/workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 772, in run_tp_server
    model_server = ModelTpServer(
  File "/workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 94, in __init__
    self.model_runner = ModelRunner(
  File "/workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 139, in __init__
    self.init_cuda_graphs()
  File "/workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 344, in init_cuda_graphs
    self.cuda_graph_runner.capture(batch_size_list)
  File "/workspace/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 148, in capture
    ) = self.capture_one_batch_size(bs, forward)
  File "/workspace/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 211, in capture_one_batch_size
    run_once()
  File "/workspace/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 208, in run_once
    return forward(input_ids, input_metadata.positions, input_metadata)
TypeError: LlamaForCausalLM.forward() missing 1 required positional argument: 'attn_metadata'
```

For context, I built a custom docker container with Amazon EFA support for multinode (installing vllm and sglang on top). So my original single node testing was with the sglang docker contianer. But single node with the following command still failed with the above error

**Comment by matthew-hippocratic** [comment]
Fixed container

**Comment by lxww302** [comment]
@matthew-hippocratic Hi, I encountered the same problem. How did you solve it?

**Comment by matthew-hippocratic** [comment]
> @matthew-hippocratic Hi, I encountered the same problem. How did you solve it?

For me what fixed it was installing the latest release of SGLang from source in my docker container:
```
# Use the last release branch
git clone -b v0.2.12 https://github.com/sgl-project/sglang.git
cd sglang

pip install --upgrade pip
pip install -e "python[all]"

# Install FlashInfer CUDA kernels
pip install flashinfer -i https://flashinfer.ai/whl/cu121/torch2.4/
```

Instead of installing from latest main branch (which was how the Dockerfile was doing it at the time)

I think it is as simple as version mismatching

**Comment by lxww302** [comment]
@matthew-hippocratic Thanks for your information. After debugging, it turns out that the issue only occurs when vllm is built from source in my case. When I install vllm using `pip3 install vllm` everything works out just fine.

**Comment by aflah02** [comment]
Hi @matthew-hippocratic 

Can you share the script you were using to run multinode inference? Essentially the container to run these
