### ISSUE TITLE
[Bug] Potential Logic Error in Memory Capacity Check for Distributed Setup

### ISSUE THREAD

**Issue by hxer7963** [sgl-project/sglang#1015]
https://github.com/sgl-project/sglang/blob/62757db6f0f09a6dff15b1ee1ac3029602951509/python/sglang/srt/model_executor/model_runner.py#L115-L124

There seems to be a logic error in the code that checks for unbalanced GPU memory capacity in a distributed setup. The current implementation compares the available memory on a specific GPU to 90% of the minimum available memory across all GPUs, which may not correctly identify situations where GPU memory is unbalanced.

Proposed Solution:
```python
- if total_local_gpu_memory < total_gpu_memory * 0.9:
+ if total_gpu_memory < total_local_gpu_memory * 0.9:
```

**Comment by merrymercy** [comment]
Good catch! Could you submit a PR to fix this?

**Comment by hxer7963** [comment]
> Good catch! Could you submit a PR to fix this?

Sure, I will fix this with XVERSE models support PR in this week.

**Comment by merrymercy** [comment]
Fixed by https://github.com/sgl-project/sglang/pull/1194
