### ISSUE TITLE
[Feature] any accuracy score on MMLU or CMMLU ?

### ISSUE THREAD

**Issue by zhang001122** [sgl-project/sglang#1054]
### Motivation

I have tested the sglang with multi llmperf tools, really impresive.
Any benchmark on accuracy score on MMLU or CMMLU

**Comment by zhyncs** [comment]
ref https://github.com/sgl-project/sglang/blob/main/test/srt/test_eval_accuracy_large.py

**Comment by merrymercy** [comment]
We run the accuracy test for every commit in our CI. We tested MMLU/HumanEval/GSM-8K and all of them match the results from vLLM.
CI history: https://github.com/sgl-project/sglang/actions/workflows/accuracy-test.yml
Workflow file: https://github.com/sgl-project/sglang/blob/main/.github/workflows/accuracy-test.yml

**Comment by merrymercy** [comment]
If you are interested, please contribute your scripts or data to our CI.
