### ISSUE TITLE
[Feature] P100/Cuda 6.1 support

### ISSUE THREAD

**Issue by dirkson** [sgl-project/sglang#1062]
### Motivation

As per https://github.com/sgl-project/sglang/issues/1059 , P100/pascal/6.1 support is not currently a target. This feature request is an official request to support it. This GPU is the least expensive hardware that will run modern LLMs, and is a common GPU in both academia and common use.

This issue was created as the original was locked with the cryptic phrase, "It makes nonsense for me.", the meaning of which was not clear in context. This issue is intended to be a place where the community can discuss support for these GPUs, as well as petition for support.

**Comment by gilbrotheraway** [comment]
have you tried patched triton? works for me on VLLM 

https://github.com/sasha0552/pascal-pkgs-ci
