### ISSUE TITLE
[Bug] Unable to run deepseek-v2

### ISSUE THREAD

**Issue by lxww302** [sgl-project/sglang#1065]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.

### Describe the bug

When I run deepseek-v2-lite with sglang, an error accured:
`  File "/opt/tiger/sglang/python/sglang/srt/managers/tp_worker.py", line 452, in forward_prefill_batch
    output = self.model_runner.forward(batch, ForwardMode.EXTEND)
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 397, in forward
    return self.forward_extend(batch)
  File "/home/tiger/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 373, in forward_extend
    return self.model.forward(
TypeError: DeepseekV2ForCausalLM.forward() missing 1 required positional argument: 'attn_metadata'`

And we can see that the signature of `forward_extend` in `model_runner.py` is not compatible with  vllm deepseek_v2 https://github.com/vllm-project/vllm/blob/774cd1d3bf7890c6abae6c7ace798c4a376b2b20/vllm/model_executor/models/deepseek_v2.py#L496

### Reproduction

command: `python3 -m sglang.launch_server --model-path=/opt/tiger/models/dsv2 --port=30000 --trust-remote-code --disable-radix-cache --enable-mla`

### Environment

vllm 0.5.4+cu122
sglang 0.2.11

**Comment by zhyncs** [comment]
May you try v0.2.12? Thanks.

**Comment by lxww302** [comment]
@zhyncs It's the same error, and it maybe an environmental issue, not just deepseek-v2, all models failed to launch in this environment.
the environment that I test is as follows:
`Python: 3.10.13 (main, Mar 30 2024, 12:22:16) [GCC 10.2.1 20210110]
CUDA available: True
GPU 0,1: NVIDIA H100 80GB HBM3
GPU 0,1 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.2, V12.2.140
CUDA Driver Version: 535.161.08
PyTorch: 2.4.0+cu121
sglang: 0.2.12
flashinfer: 0.1.4+cu121torch2.4
triton: 3.0.0
transformers: 4.44.0
requests: 2.32.3
tqdm: 4.66.4
numpy: 1.26.4
aiohttp: 3.9.5
fastapi: 0.112.0
hf_transfer: 0.1.8
huggingface_hub: 0.23.4
interegular: 0.3.3
packaging: 24.0
PIL: 10.3.0
psutil: 6.0.0
pydantic: 2.7.4
uvicorn: 0.30.5
uvloop: 0.19.0
zmq: 26.1.0
vllm: 0.5.4
multipart: 0.0.9
openai: 1.40.2
anthropic: 0.32.0
NVIDIA Topology: 
        GPU0    GPU1    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5    NIC6    NIC7    NIC8    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV18    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE    0-47   0N/A
GPU1    NV18     X      NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE    0-47   0N/A
NIC0    NODE    NODE     X      NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE
NIC1    NODE    NODE    NODE     X      NODE    NODE    SYS     SYS     SYS     SYS     NODE
NIC2    NODE    NODE    NODE    NODE     X      NODE    SYS     SYS     SYS     SYS     NODE
NIC3    NODE    NODE    NODE    NODE    NODE     X      SYS     SYS     SYS     SYS     NODE
NIC4    SYS     SYS     SYS     SYS     SYS     SYS      X      NODE    NODE    NODE    SYS
NIC5    SYS     SYS     SYS     SYS     SYS     SYS     NODE     X      NODE    NODE    SYS
NIC6    SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE     X      NODE    SYS
NIC7    SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    NODE     X      SYS
NIC8    NODE    NODE    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3
  NIC4: mlx5_4
  NIC5: mlx5_5
  NIC6: mlx5_6
  NIC7: mlx5_7
  NIC8: mlx5_8


ulimit soft: 1024768`

**Comment by zhyncs** [comment]
I did not reproduce your problem on the RunPod H100 8 devices setup.

**Comment by zhyncs** [comment]
```bash
git clone https://github.com/sgl-project/sglang.git
cd sglang

pip install --upgrade pip
pip install -e "python[all]"

pip install flashinfer -i https://flashinfer.ai/whl/cu121/torch2.4/
```

@lxww302 May you try this? Thanks.

**Comment by zhyncs** [comment]
## env
```
root@hostname:/# python3 -m sglang.check_env
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
CUDA available: True
GPU 0: NVIDIA H100 80GB HBM3
GPU 0 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
CUDA Driver Version: 550.54.15
PyTorch: 2.4.0+cu121
flashinfer: 0.1.4+cu121torch2.4
triton: 3.0.0
transformers: 4.44.0
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.3
aiohttp: 3.10.3
fastapi: 0.112.0
hf_transfer: 0.1.8
huggingface_hub: 0.24.5
interegular: 0.3.3
packaging: 23.2
PIL: 10.2.0
psutil: 5.9.8
pydantic: 2.8.2
uvicorn: 0.30.5
uvloop: 0.19.0
zmq: 24.0.1
vllm: 0.5.4
multipart: 0.0.9
openai: 1.40.6
anthropic: 0.33.1
NVIDIA Topology:
        GPU0    NIC0    NIC1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PXB     PXB     52-103,156-207  1               N/A
NIC0    PXB      X      PIX
NIC1    PXB     PIX      X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1


ulimit soft: 1048576
```

## install

```
git clone https://github.com/sgl-project/sglang.git
cd sglang

pip install --upgrade pip
pip install -e "python[all]"

pip install flashinfer -i https://flashinfer.ai/whl/cu121/torch2.4/
```

## run server

```
python3 -m sglang.launch_server --model-path deepseek-ai/DeepSeek-V2-Lite --port 30000 --trust-remote-code --disable-radix-cache --enable-mla
```

## benchmark

```
python3 -m sglang.bench_serving --backend sglang
```

## result

```
============ Serving Benchmark Result ============
Backend:                                 sglang
Traffic request rate:                    inf
Successful requests:                     1000
Benchmark duration (s):                  59.88
Total input tokens:                      236142
Total generated tokens:                  215614
Total generated tokens (retokenized):    215363
Request throughput (req/s):              16.70
Input token throughput (tok/s):          3943.75
Output token throughput (tok/s):         3600.92
----------------End-to-End Latency----------------
Mean E2E Latency (ms):                   26369.84
Median E2E Latency (ms):                 23558.31
---------------Time to First Token----------------
Mean TTFT (ms):                          6397.42
Median TTFT (ms):                        5881.20
P99 TTFT (ms):                           11738.08
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          249.32
Median TPOT (ms):                        109.31
P99 TPOT (ms):                           1745.76
---------------Inter-token Latency----------------
Mean ITL (ms):                           96.14
Median ITL (ms):                         70.83
P99 ITL (ms):                            300.09
==================================================
```

@lxww302 I've confirmed there are no issues in this environment, and I hope it serves as a useful reference for you.

**Comment by lxww302** [comment]
> ```shell
> git clone https://github.com/sgl-project/sglang.git
> cd sglang
> 
> pip install --upgrade pip
> pip install -e "python[all]"
> 
> pip install flashinfer -i https://flashinfer.ai/whl/cu121/torch2.4/
> ```
> 
> @lxww302 May you try this? Thanks.

Yes, I have tried these comands and still got the same errors. Looks like your environment is pretty much the same as mine. Still can not figure out what the problem is. Could you kindly help me with that? the track stack is as follows: 

```
Initialization failed. controller_init_state: Traceback (most recent call last):
  File "/opt/tiger/sglang/python/sglang/srt/managers/controller_single.py", line 150, in start_controller_process
    controller = ControllerSingle(
  File "/opt/tiger/sglang/python/sglang/srt/managers/controller_single.py", line 84, in __init__
    self.tp_server = ModelTpServer(
  File "/opt/tiger/sglang/python/sglang/srt/managers/tp_worker.py", line 100, in __init__
    self.model_runner = ModelRunner(
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 139, in __init__
    self.init_cuda_graphs()
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/model_runner.py", line 344, in init_cuda_graphs
    self.cuda_graph_runner.capture(batch_size_list)
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 148, in capture
    ) = self.capture_one_batch_size(bs, forward)
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 211, in capture_one_batch_size
    run_once()
  File "/opt/tiger/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 208, in run_once
    return forward(input_ids, input_metadata.positions, input_metadata)
TypeError: forward() missing 1 required positional argument: 'attn_metadata'
```

**Comment by lxww302** [comment]
After debugging, it turns out that the issue only occurs when vllm is built from source. When I install vllm using `pip3 install vllm` everything works out just fine.
