### ISSUE TITLE
Mistral model no longer loads following PR#101

### ISSUE THREAD

**Issue by johndun** [sgl-project/sglang#107]
The `get_model_cls_by_arch_name` introduced in [Dynamic model class loading PR](https://github.com/sgl-project/sglang/pull/101) removes the hard-coded mapping between `MistralForCausalLM` and `LlamaForCausalLM` causing issues trying to local host [Mistral-7b](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2) model as of sglang version 0.1.9. I have tested that adding the following simple `models/mistral.py` file allows hosting the mistral-7b model.

```python
from sglang.srt.models.llama2 import LlamaForCausalLM


class MistralForCausalLM(LlamaForCausalLM):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


EntryClass = MistralForCausalLM
```

**Comment by comaniac** [comment]
Thanks for pointing out this issue and the workaround. I'll take a look today.

**Comment by comaniac** [comment]
Ok it turns out that we should do exactly what you proposed. Mistral config does use `MistralForCausalLM`, so we should look for this class instead of using a hard-coded mapping. I'll file a PR for it now and make you a co-author. Thanks!
