### ISSUE TITLE
[Feature] Are there plans to implement a prefill-decode split inference architecture?

### ISSUE THREAD

**Issue by CSEEduanyu** [sgl-project/sglang#1080]
### Motivation
Related work includes:

1.https://github.com/LLMServe/DistServe/tree/main
2.https://github.com/vllm-project/vllm/pull/2809
3.mooncake has proven that separating prefill and decode can lead to throughput improvements and significant cost savings for online services. Are there any plans to do this?

**Comment by zhyncs** [comment]
The feature you mentioned is highly dependent on business requirements and real-world scenarios. It's a promising area for improvement, such as https://github.com/kvcache-ai/Mooncake, and @Jeffwan might be also interested in it. While it's on our roadmap https://github.com/sgl-project/sglang/issues/634, its priority and implementation complexity mean the short-term ROI is not very high. And we'll keep tracking its progress. Thanks for your interest!

**Comment by zhyncs** [comment]
We plan to implement this feature in Q4, please stay tuned. ref https://github.com/sgl-project/sglang/issues/1487
