### ISSUE TITLE
will triton kernels support cuda graph?

### ISSUE THREAD

**Issue by AlvL1225** [sgl-project/sglang#1097]
### Motivation

Only flash infer support cuda graph bug triton (with more cpu overhead) might gain more with cuda graph .

**Comment by merrymercy** [comment]
supported in v0.3.1.post1 
https://github.com/sgl-project/sglang/pull/1401

**Comment by AlvL1225** [comment]
> supported in v0.3.1.post1 #1401

nice work! custom triton ops will reach better performance!
