### ISSUE TITLE
Qwen-7B-Chat UnicodeDecodeError Stop working

### ISSUE THREAD

**Issue by exceedzhang** [sgl-project/sglang#111]
I have found that when running the Qwen-7B-Chat model for inference, sometimes the following errors occur, which can cause the entire inference service to malfunction in the future. As shown in the following figure:

<img width="1298" alt="image" src="https://github.com/sgl-project/sglang/assets/4583537/53596022-c749-42d0-ad6b-919ad4bf3d5c">

<img width="1512" alt="image" src="https://github.com/sgl-project/sglang/assets/4583537/253015ab-3de3-40ca-a5b7-de9a980e4615">

Start script:
python -m sglang.launch_server --model-path /root/autodl-tmp/Qwen-7B-Chat --port 8000 --load-format safetensors --mem-fraction-static 0.9 --tokenizer-mode auto --trust-remote-code

Test script:
python3 bench_throughput.py  --tokenizer /root/autodl-tmp/Qwen-7B-Chat --dataset /root/autodl-tmp/ShareGPT_V3_unfiltered_cleaned_split.json --num-prompts 1000  --port 8000 --backend srt --trust-remote-code

**Comment by merrymercy** [comment]
@exceedzhang It has been fixed by https://github.com/sgl-project/sglang/commit/873d0e85378792f170cab1eac6c39a2efbb89ab1.

Try the latest main branch.
