### ISSUE TITLE
[Feature] add disable_custom_all_reduce

### ISSUE THREAD

**Issue by Xu-Chen** [sgl-project/sglang#1118]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

Sometimes, we need to turn off Custom allreduce. 
Please  support disable_custom_all_reduce.

**Comment by zhyncs** [comment]
May you submit a PR? We highly welcome contributions!

**Comment by Xu-Chen** [comment]
Test code https://github.com/Xu-Chen/sglang/tree/add-disable_custom_all_reduce. And can work fine.

**Comment by Xu-Chen** [comment]
https://github.com/sgl-project/sglang/pull/1148

**Comment by m0g1cian** [comment]
Have you tried to add the system variable `NCCL_ALGO=Tree` before running the backend? It seems to alleviate the hanging problem on A800 specificlly.

**Comment by zhyncs** [comment]
> Have you tried to add the system variable `NCCL_ALGO=Tree` before running the backend? It seems to alleviate the hanging problem on A800 specificlly.

@Xu-Chen May you have a try? Thanks.

**Comment by Xu-Chen** [comment]
> > Have you tried to add the system variable `NCCL_ALGO=Tree` before running the backend? It seems to alleviate the hanging problem on A800 specificlly.
> 
> @Xu-Chen May you have a try? Thanks.

Great, will try.

**Comment by Xu-Chen** [comment]
> Have you tried to add the system variable `NCCL_ALGO=Tree` before running the backend? It seems to alleviate the hanging problem on A800 specificlly.

Limited testing on the 0.2.14 version shows the issue is resolved.
