### ISSUE TITLE
[Bug] I set `--host 0.0.0.0`, but it can't be called on another server

### ISSUE THREAD

**Issue by YinSonglin1997** [sgl-project/sglang#1121]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

I use the commond:
`python -m sglang.launch_server --model-path /ldata/llms/Meta-Llama-3.1-70B-Instruct --host 0.0.0.0 --port 30000 --tp 4 --mem-fraction-static 0.95 --context-length 4096 --max-total-tokens 4096
`, I was able to call the model successfully when I ran the script on this server, but calling the model on another server yields the following error:
`httpcore.ConnectError: [Errno 113] No route to host`
The two servers can ping each other successfully. What is the cause of the problem?

### Reproduction

```
import openai
client = openai.Client(
    base_url="http://10.0.1.228:30000/v1", api_key="EMPTY")

# Text completion
response = client.completions.create(
        model="default",
        prompt="The capital of France is",
        temperature=0,
        max_tokens=32,
)
print(response.choices[0].text)

# Chat completion
response = client.chat.completions.create(
    model="default",
    messages=[
        {"role": "system", "content": "You are a helpful AI assistant"},
        {"role": "user", "content": "List 3 countries and their capitals."},
    ],
    temperature=0,
    max_tokens=64,
)
print(response.choices[0].message.content)
```
model: `Meta-Llama-3.1-70B-Instruct`

### Environment

Python: 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:50:21) [GCC 12.3.0]
CUDA available: True
GPU 0,1,2,3: NVIDIA A100-PCIE-40GB
GPU 0,1,2,3 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda-11.8
NVCC: Cuda compilation tools, release 11.8, V11.8.89
CUDA Driver Version: 535.86.10
PyTorch: 2.4.0+cu121
sglang: 0.2.12
flashinfer: 0.1.4+cu121torch2.4
triton: 3.0.0
transformers: 4.44.0
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.3
fastapi: 0.112.1
hf_transfer: 0.1.8
huggingface_hub: 0.24.5
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.8.2
uvicorn: 0.30.6
uvloop: 0.20.0
zmq: 26.1.0
vllm: 0.5.4
multipart: 0.0.9
openai: 1.40.8
anthropic: 0.34.0

**Comment by zhyncs** [comment]
I can't reproduce your issue. Perhaps you could check the network connectivity. Besides the ping you mentioned, after all, ping uses the ICMP protocol, you can simply set up an HTTP server and try accessing it with curl.
