### ISSUE TITLE
[Bug] llava not working after pull latest code

### ISSUE THREAD

**Issue by boqiny** [sgl-project/sglang#1130]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

  File "/u/miniconda3/lib/python3.11/site-packages/sglang/srt/managers/tp_worker.py", line 441, in forward_prefill_batch
    batch.prepare_for_extend(self.model_config.vocab_size)
TypeError: ScheduleBatch.prepare_for_extend() missing 1 required positional argument: 'int_token_logit_bias'

Killed

### Reproduction

python -m sglang.launch_server --model-path liuhaotian/llava-v1.5-7b --tokenizer-path llava-hf/llava-1.5-7b-hf --chat-template vicuna_v1.1 --port 30000

### Environment

Python: 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0]
CUDA available: True
GPU 0: NVIDIA A40
GPU 0 Compute Capability: 8.6
CUDA_HOME: /sw/spack/deltas11-2023-03/apps/linux-rhel8-zen3/gcc-11.4.0/cuda-11.8.0-vfixfmc
NVCC: Cuda compilation tools, release 11.8, V11.8.89
CUDA Driver Version: 535.183.01
PyTorch: 2.4.0+cu121
sglang: 0.2.12
flashinfer: 0.1.5+cu121torch2.4
triton: 3.0.0
transformers: 4.44.0
requests: 2.32.3
tqdm: 4.66.4
numpy: 1.26.4
aiohttp: 3.9.5
fastapi: 0.112.0
hf_transfer: 0.1.8
huggingface_hub: 0.23.3
interegular: 0.3.3
packaging: 23.0
PIL: 10.4.0
psutil: 5.9.0
pydantic: 2.8.2
uvicorn: 0.30.5
uvloop: 0.19.0
zmq: 25.1.2
vllm: 0.5.4
multipart: 0.0.9
openai: 1.40.1
anthropic: 0.32.0
NVIDIA Topology: 
        GPU0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      0-15    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 131072

**Comment by zhyncs** [comment]
Why the latest code is displaying as version 0.2.12 in SGLang? It should indicate version 0.2.13.

**Comment by boqiny** [comment]
Thank you. turns out I need to reinstall sglang package.
