### ISSUE TITLE
[Bug] when llama-3.1-70b-instruct batch inference, CUDA memory usage is unusually large

### ISSUE THREAD

**Issue by yak9meat** [sgl-project/sglang#1132]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

When i use 8*A100 for llama-3.1-70b-instruct batch inference, CUDA memory usage is unusually large，num_threads，max_num_reqs, mem_fraction_static are all useless.  I've also tried iterative single  inference, and the CUDA memory is constantly increasing. The Cuda memory doesn't seem to be released after inference.

### Reproduction

Model: llama-3.1-70b-instruct
GPUS: 8*A100
Method:run_batch() tp_size=8

### Environment

sglang 0.2.12

**Comment by qeternity** [comment]
We have noticed the same, trying to run on any recent 0.2.x branch. Consistent increases in VRAM usage. Reducing chunked prefill sizes and static memory only help for a short period of time before OOM'ing.

**Comment by qeternity** [comment]
This commit seems to have improved things (too early to say if resolved, but early testing is working better): https://github.com/sgl-project/sglang/commit/df191254abc002b3284560d9c4b94214a4656265

**Comment by yak9meat** [comment]
Thank you for your reply. I have tried the  commit you mentioned, but it doesn't seem to be working for me.

**Comment by ShadowTeamCN** [comment]
> We have noticed the same, trying to run on any recent 0.2.x branch. Consistent increases in VRAM usage. Reducing chunked prefill sizes and static memory only help for a short period of time before OOM'ing.

would you mind share the latest normal version? Does it mean latest 1.x  version?

**Comment by yak9meat** [comment]
Using chunked prefill may be useful to solve this problem. I set chunked_prefill_size=8192, which worked for me.

**Comment by yak9meat** [comment]
> This commit seems to have improved things (too early to say if resolved, but early testing is working better): [df19125](https://github.com/sgl-project/sglang/commit/df191254abc002b3284560d9c4b94214a4656265)

Using chunked prefill may be useful to solve this problem. I set chunked_prefill_size=8192, which worked for me.

**Comment by merrymercy** [comment]
It seems the issue has been solved with chunked prefill
