### ISSUE TITLE
[Feature] support W8A8(FP8) and KV Cache FP8 for DeepSeek V2

### ISSUE THREAD

**Issue by zhyncs** [sgl-project/sglang#1156]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

As titled. Make DeepSeek V2 MLA Faster!

**Comment by fengyang95** [comment]
Is there a specific timeline for this?

**Comment by zhyncs** [comment]
> Is there a specific timeline for this?

bmm fp8 has been implemented with https://github.com/flashinfer-ai/flashinfer/pull/469
fp8 e5m2 kv cache has been implemented with https://github.com/sgl-project/sglang/pull/1204

Currently, there is no adaptation for DeepSeek V2 as we are focusing on other higher priority tasks. Expected to be completed within these few days.

**Comment by zhyncs** [comment]
done
