### ISSUE TITLE
[Bug] Gemma-2-9b-it produces garbage output

### ISSUE THREAD

**Issue by Quang-elec44** [sgl-project/sglang#1160]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

Gemma-2-9b-it: "<unused99><unused99><unused99><unused99><unused99>..."

### Reproduction

I just pulled the latest Docker image and deployed Gemma-2-9b-it [AWQ version](https://huggingface.co/nihaomur/gemma-2-9b-it-AWQ). Here is how I deployed the model

```shell
HF_TOKEN=<my-token>
MODEL=nihaomur/gemma-2-9b-it-AWQ
SERVED_MODEL_NAME=gpt-4o
MFS=0.6
TP=2
API_KEY=<my-key>

docker run -d --gpus '"device=2,3"' \
    -p 8002:8002 \
    --rm \
    --network=<network-name> \
    --name sglang-server \
    -v ~/.cache/huggingface:/root/.cache/huggingface \
    --env HF_TOKEN=$HF_TOKEN \
    --ipc=host \
    lmsysorg/sglang:latest \
        python3 -m sglang.launch_server \
        --model-path $MODEL \
        --host 0.0.0.0 \
        --port 8002 \
        --served-model-name $SERVED_MODEL_NAME \
        --mem-fraction-static $MFS \
        --tensor-parallel-size $TP \
        --api-key $API_KEY \
        --quantization awq_marlin \
        --efficient-weight-load \
        --enable-p2p-check
```

Here is my prompt
```python
prompt = """### Task:
You will be given a question and several context files, which may contain relevant information. Your objectives are as follows:

1. **Extract Supported Evidence**: For each file name provided, identify and extract short, concise phrases that serve as strong evidence supporting the question. The evidence must be:
   - Relevant: Directly related to the question.
   - Strongly Related: Clearly substantiates or informs the question.

2. **Evaluate Relevance**: Gather all extracted evidence and evaluate how well it supports the question. Provide your thoughts on the relevance and strength of the evidence as it relates to the question.

3. **Formulate the Final Answer**:
   - If the collected evidence collectively provides a clear and accurate answer to the question, present the answer in a well-informed and concise manner.
   - If the evidence is insufficient or inconclusive, explicitly state that a definitive answer could not be determined. Avoid making unsupported assumptions.
   
4. **Output Format**: Return your findings as a JSON object adhering to the following schema:

```json
{{
  "supported_evidence": [{{"filename": "<filename>", "text": ["<evidence>", "<evidence>"]}}, ...],
  "thought": "<your evaluation of relevance>",
  "final_answer": "<your final answer or statement of inconclusiveness>"
}}```

### Here is your input
Question: {question}
Reports: {contexts}"""
```

My Pydantic model
```python
class Evidence(BaseModel):
    filename: str
    text: list[str]

class Output(BaseModel):
    supported_evidence: list[Evidence]
    thought: str
    final_answer: str
```

How I called the server

```python
content = await self.client(
            messages=Messages(
                messages=[
                    {"role": "user", "content": prompt}]
            ),
            extra_body={
                "regex": build_regex_from_object(Output),
                "repetition_penalty": 1.2,
            **self.params
        )
```

[Llama-3.1-8B-Instruct](https://huggingface.co/hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4) worked with this prompt while Gemma-2 produced garbage outputs (Note: with repetition_penalty = 1.0, Llama-3.1 produced duplicated content)

### Environment

Python: 3.10.14 (main, Apr  6 2024, 18:45:05) [GCC 9.4.0]
CUDA available: True
GPU 0,1: NVIDIA A10G
GPU 0,1 Compute Capability: 8.6
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
CUDA Driver Version: 550.90.07
PyTorch: 2.4.0+cu121
flashinfer: 0.1.5+cu121torch2.4
triton: 3.0.0
transformers: 4.44.0
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.3
fastapi: 0.112.1
hf_transfer: 0.1.8
huggingface_hub: 0.24.5
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.8.2
uvicorn: 0.30.6
uvloop: 0.20.0
zmq: 26.1.0
vllm: 0.5.4
multipart: 0.0.9
openai: 1.40.8
anthropic: 0.34.0
NVIDIA Topology: 
        GPU0    GPU1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PHB     0-47    0               N/A
GPU1    PHB      X      0-47    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 1048576

**Comment by zhyncs** [comment]
What are the inference results of this AWQ version model using `transformers`, under the same parameters?

**Comment by Quang-elec44** [comment]
@zhyncs It didn't generate anything. I think the awq version is broken.

**Comment by Quang-elec44** [comment]
@zhyncs It seems like `gemma-2` hasn't been supported yet [issue](https://github.com/casper-hansen/AutoAWQ/pull/562), but somehome there is a checkpoint on HF.

**Comment by zhyncs** [comment]
ok. You can use fp16 version for now.
