### ISSUE TITLE
[Feature] Support W8A16 Int8 inside FusedMoE

### ISSUE THREAD

**Issue by halexan** [sgl-project/sglang#1161]
### Checklist

- [x] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 2. Please use English, otherwise it will be closed.

### Motivation

vllm now supports W8A16 Int8 inside FusedMoE. see [#7415](https://github.com/vllm-project/vllm/pull/7415)

So, after vllm new version released. sglang will support too?

**Comment by zhyncs** [comment]
In the short term, yes. In the long term, we will maintain it ourselves.
