### ISSUE TITLE
[Feature] SGLang using  JSON as template config file needs improve

### ISSUE THREAD

**Issue by zhang001122** [sgl-project/sglang#1172]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

{
  "name": "my_model",
  "system": "<|im_start|>system",
  "user": "<|im_start|>user",
  "assistant": "<|im_start|>assistant",
  "sep_style": "CHATML",
  "sep": "<|im_end|>",
  "stop_str": ["<|im_end|>", "<|im_start|>"]
}

this is not general , I think jinja is more popular such as huggingface tgi、vllm、interlm、QWEN， they all use jinjia as the chat template, this JSON format really needs to impove, no needs to build another wheel, right?

**Comment by zhyncs** [comment]
ref https://github.com/sgl-project/sglang/pull/1104
