### ISSUE TITLE
Support gptq  quantization

### ISSUE THREAD

**Issue by meichangsu1** [sgl-project/sglang#124]

**Comment by merrymercy** [comment]
Contributions are welcome. You can add the support for GPTQ here
https://github.com/sgl-project/sglang/blob/71b54eea7d21a2bb1d8ef340e7002983a29b1d5f/python/sglang/srt/managers/router/model_runner.py#L282-L286

We reuse the quantization and linear method in vLLM, so you can learn how to use them in the vLLM code 
https://github.com/vllm-project/vllm/blob/3dad94448583a835230ae68c726d4b67e46845f2/vllm/model_executor/model_loader.py#L47

**Comment by merrymercy** [comment]
done by #141
