### ISSUE TITLE
[Bug] Lower single request speed with mla enabled

### ISSUE THREAD

**Issue by halexan** [sgl-project/sglang#1264]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

Lower speed with mla enabled

### Reproduction

Model: DeepSeek-V2-Chat-0628

Enable mla: 
```
python3 -m sglang.launch_server \
    --model-path /data/model-cache/deepseek-ai/DeepSeek-V2-Chat-0628 \
    --served-model-name deepseek-chat \
    --tp 8 \
    --enable-mla
```

1 request, 11.5 token/s

![image](https://github.com/user-attachments/assets/5295b30a-578d-4eb5-9e46-0c162f49733e)

Disable mla:
```
python3 -m sglang.launch_server \
    --model-path /data/model-cache/deepseek-ai/DeepSeek-V2-Chat-0628 \
    --served-model-name deepseek-chat \
    --tp 8
```

1 request, 38 token/s

![image](https://github.com/user-attachments/assets/47de7932-60f7-4e63-becd-aca8ad003d48)

### Environment

docker image lmsysorg/sglang:v0.2.14.post2-cu124

**Comment by ispobock** [comment]
@halexan could you share the request?

**Comment by ispobock** [comment]
@halexan I think it's mainly the optimization of cuda graph. Could you test with `--disable-cuda-graph` for both cases?

**Comment by halexan** [comment]
disable cuda graph, enable mla

```
python3 -m sglang.launch_server \
    --model-path /data/model-cache/deepseek-ai/DeepSeek-V2-Chat-0628 \
    --served-model-name deepseek-chat \
    --tp 8 \
    --enable-mla \
    --disable-cuda-graph
```

1 request, 12 tokens/s

![image](https://github.com/user-attachments/assets/8012e38c-cf90-4aec-8aaa-a9cb88b2763c)


disable cuda graph, disable mla
```
python3 -m sglang.launch_server \
    --model-path /data/model-cache/deepseek-ai/DeepSeek-V2-Chat-0628 \
    --served-model-name deepseek-chat \
    --tp 8 \
    --disable-cuda-graph
```

1 request, 12 tokens/s

![image](https://github.com/user-attachments/assets/0db4cf08-8fe5-46c3-884a-daefdd4a23de)

**Comment by zhyncs** [comment]
"for both cases" @halexan

**Comment by halexan** [comment]
> "for both cases" @halexan

I update, is it right ?

**Comment by ispobock** [comment]
@halexan Currently cuda graph is only supported for flashinfer backend, while MLA uses Triton backend. We plan to support cuda graph for Triton soon. Stay tuned.
cc: @merrymercy

**Comment by halexan** [comment]
To provide a more precise description, I  revised the title.

**Comment by Achazwl** [comment]
I also encountered the same problem.

**Comment by zhyncs** [comment]
It is expected that this week or so, @merrymercy  and @ispobock  will support CUDA Graph for Triton Runtime. The latency under small batch sizes will be greatly reduced after that. Please stay tuned.

**Comment by merrymercy** [comment]
Can you try this PR? https://github.com/sgl-project/sglang/pull/1401

**Comment by Achazwl** [comment]
Work for short sequences now. `--enable-mla` would have approximately the same speed as not enabling it.
However, when tested on longer sequences, `--enable-mla` is still much slower.
It seems that it becomes slower as the sequence gets longer.

1024 case:
`python3 -m sglang.bench_latency --model ../models/DeepSeek-V2-Lite/ --trust-remote-code --input-len 1024 --output-len 1024 --batch 1`
```
Decode.  median latency: 0.00847 s, median throughput:    118.08 token/s
Total. latency:  8.721 s, throughput:    234.84 token/s
```

`python3 -m sglang.bench_latency --model ../models/DeepSeek-V2-Lite/ --trust-remote-code --input-len 1024 --output-len 1024 --batch 1 --enable-mla`
```
Decode.  median latency: 0.00989 s, median throughput:    101.13 token/s
Total. latency: 10.133 s, throughput:    202.11 token/s
```

2048 case:
`python3 -m sglang.bench_latency --model ../models/DeepSeek-V2-Lite/ --trust-remote-code --input-len 2048 --output-len 2048 --batch 1`
```
Decode.  median latency: 0.00881 s, median throughput:    113.45 token/s
Total. latency: 18.176 s, throughput:    225.35 token/s
```

`python3 -m sglang.bench_latency --model ../models/DeepSeek-V2-Lite/ --trust-remote-code --input-len 2048 --output-len 2048 --batch 1 --enable-mla`
```
Decode.  median latency: 0.01206 s, median throughput:     82.93 token/s
Total. latency: 24.700 s, throughput:    165.83 token/s
```

**Comment by Achazwl** [comment]
> Can you try this PR? #1401

In addition to the longer sequence issue I raised above, I also encountered the issue in https://github.com/sgl-project/sglang/issues/1372, where the deepseek model cannot support `--enable-torch-compile`. The issue https://github.com/sgl-project/sglang/issues/1372 says that torch compile could be used when the cuda graph is supported, but I still cannot use torch-compile in this PR, whether `--enable-mla` or not.

**Comment by merrymercy** [comment]
Both cuda graph and torch.compile are supported in the latest version v0.3.1.post3. (PR: https://github.com/sgl-project/sglang/pull/1442).

The slower speed on long context is expected because the triton decoding kernel lacks some optimization (e.g, split kv).
I will close this PR for now as most issues have been solved. If you are interested, please open a new issue to track the performance of triton backend on long context.
