### ISSUE TITLE
[Bug] Update to 0.2.15 and torch compile leads to error

### ISSUE THREAD

**Issue by zhaochenyang20** [sgl-project/sglang#1310]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

I updated my SGLang to 0.2.15 and reused my previous code base. This time, `--enable-torch-compile` would lead to an error after several posts get successful responses.

I delete `--enable-torch-compile` and it will be right.

This is the error logging:

```
[21:30:46 TP0] Prefill batch. #new-seq: 1, #new-token: 1776, #cached-token: 65, cache hit rate: 97.63%, #running-req: 0, #queue
-req: 0                                                                                                                        
[21:30:47 TP0] Prefill batch. #new-seq: 5, #new-token: 5, #cached-token: 9719, cache hit rate: 97.73%, #running-req: 1, #queue-
req: 0                                                                                                                         
../aten/src/ATen/native/cuda/MultinomialKernel.cu:112: binarySearchForMultinomial: block: [0,7,0], thread: [0,0,0] Assertion `c
umdist[size - 1] > static_cast<scalar_t>(0)` failed.                                                                           
../aten/src/ATen/native/cuda/MultinomialKernel.cu:112: binarySearchForMultinomial: block: [0,7,0], thread: [1,0,0] Assertion `c
umdist[size - 1] > static_cast<scalar_t>(0)` failed.                                                                           
[21:30:47 TP0] Exception in ModelTpServer:                                                                                     
Traceback (most recent call last):                                                                                             
  File "/home/chenyang/miniconda3/envs/AlphaMeemory/lib/python3.11/site-packages/sglang/srt/managers/tp_worker.py", line 244, i
n exposed_step                                                                                                                 
    self.forward_step()                                                                                                        
  File "/home/chenyang/miniconda3/envs/AlphaMeemory/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in deco
rate_context                                                                                                                   
    return func(*args, **kwargs)                                                                                               
           ^^^^^^^^^^^^^^^^^^^^^                                                                                               
  File "/home/chenyang/miniconda3/envs/AlphaMeemory/lib/python3.11/site-packages/sglang/srt/managers/tp_worker.py", line 273, i
n forward_step                                                                                                                 
    self.forward_decode_batch(self.running_batch)                                                                              
  File "/home/chenyang/miniconda3/envs/AlphaMeemory/lib/python3.11/site-packages/sglang/srt/managers/tp_worker.py", line 685, i
n forward_decode_batch         
    sample_output, logits_output = self.model_runner.forward( 
  File "/home/chenyang/miniconda3/envs/AlphaMeemory/lib/python3.11/site-packages/sglang/srt/model_executor/model_runne[37/1758]
ne 582, in forward                                                                                                             
    return self.forward_decode(batch)                                                                                          
           ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                          
  File "/home/chenyang/miniconda3/envs/AlphaMeemory/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in deco
rate_context                                                                                                                   
    return func(*args, **kwargs)                                                                                               
           ^^^^^^^^^^^^^^^^^^^^^                                                                                               
  File "/home/chenyang/miniconda3/envs/AlphaMeemory/lib/python3.11/site-packages/sglang/srt/model_executor/model_runner.py", li
ne 528, in forward_decode                                                                                                      
    return self.cuda_graph_runner.replay(batch)                                                                                
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                
  File "/home/chenyang/miniconda3/envs/AlphaMeemory/lib/python3.11/site-packages/sglang/srt/model_executor/cuda_graph_runner.py
", line 315, in replay                                                                                                         
    torch.cuda.synchronize()                                                                                                   
  File "/home/chenyang/miniconda3/envs/AlphaMeemory/lib/python3.11/site-packages/torch/cuda/__init__.py", line 892, in synchron
ize                                                                                                                            
    return torch._C._cuda_synchronize()                                                                                        
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                        
RuntimeError: CUDA error: device-side assert triggered                                                                         
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1                                                                          
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### Reproduction

`8bins` is Llama3.1-8b-instruct.

```
CUDA_VISIBLE_DEVICES=1 python -m sglang.launch_server --enable-p2p-check --model-path 8bins     --dtype auto --tensor-parallel-size 1     --context-length 131072 --chunked-prefill-size 16384     --port 8056 --host 0.0.0.0 --api-key sk-1dwqsdv4r3wef3rvefg34ef1dwRv  --mem-fraction-static 0.8 
```

This is the right one. And `--enable-torch-compile` would be errorneous.

### Environment

Python: 3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA RTX A6000
GPU 0,1,2,3,4,5,6,7 Compute Capability: 8.6
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.3, V12.3.103
CUDA Driver Version: 545.23.08
PyTorch: 2.4.0+cu121
sglang: 0.2.15
flashinfer: 0.1.6+cu124torch2.4
triton: 3.0.0
transformers: 4.44.0
requests: 2.32.3
tqdm: 4.66.4
numpy: 1.24.1
aiohttp: 3.9.5
fastapi: 0.112.1
hf_transfer: 0.1.8
huggingface_hub: 0.24.6
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.8.2
uvicorn: 0.23.2
uvloop: 0.19.0
zmq: 26.0.3
vllm: 0.5.5
multipart: 0.0.9
openai: 1.40.3
anthropic: 0.33.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS     SYS     SYS     SYS     SYS     SYS     SYS     0-15,32-47      0               N/A
GPU1    SYS      X      SYS     SYS     SYS     SYS     SYS     SYS     0-15,32-47      0               N/A
GPU2    SYS     SYS      X      SYS     SYS     SYS     SYS     SYS     0-15,32-47      0               N/A
GPU3    SYS     SYS     SYS      X      SYS     SYS     SYS     SYS     0-15,32-47      0               N/A
GPU4    SYS     SYS     SYS     SYS      X      SYS     SYS     SYS     16-31,48-63     1               N/A
GPU5    SYS     SYS     SYS     SYS     SYS      X      SYS     SYS     16-31,48-63     1               N/A
GPU6    SYS     SYS     SYS     SYS     SYS     SYS      X      SYS     16-31,48-63     1               N/A
GPU7    SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      16-31,48-63     1               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

**Comment by zhyncs** [comment]
fixed with https://github.com/sgl-project/sglang/pull/1306
