### ISSUE TITLE
The CPU is also occupied at 100% when there are no requests.

### ISSUE THREAD

**Issue by luhairong11** [sgl-project/sglang#1315]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

The CPU is also occupied at 100% when there are no requests.
![image](https://github.com/user-attachments/assets/d0ba33d7-ca65-42d6-87a0-1b6d3666cb65)

### Reproduction

python3 -m sglang.launch_server --model-path /data/chdmx/models/qwen/Qwen1.5-0.5B-Chat-GPTQ-Int4  --port 9997 --host 0.0.0.0 --mem-fraction-static 0.3

### Environment

Python: 3.10.14 (main, Apr  6 2024, 18:45:05) [GCC 9.4.0]
CUDA available: True
GPU 0: NVIDIA A100 80GB PCIe
GPU 0 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.99
CUDA Driver Version: 550.54.14
PyTorch: 2.4.0+cu121
sglang: 0.2.15
flashinfer: 0.1.6+cu124torch2.4
triton: 3.0.0
transformers: 4.43.4
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.1
fastapi: 0.110.3
hf_transfer: 0.1.8
huggingface_hub: 0.24.5
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.8.2
uvicorn: 0.30.5
uvloop: 0.19.0
zmq: 26.1.0
vllm: 0.5.5
multipart: 0.0.9
openai: 1.39.0
anthropic: 0.34.1
NVIDIA Topology: 
	GPU0	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	0-15	0		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

Hypervisor vendor: KVM
ulimit soft: 1048576

**Comment by zhyncs** [comment]
duplicate https://github.com/sgl-project/sglang/issues/955
