### ISSUE TITLE
[Bug] Facing Error When starting.

### ISSUE THREAD

**Issue by Abdulhanan535** [sgl-project/sglang#1321]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

`WARNING 09-04 04:55:04 _core_ext.py:180] Failed to import from vllm._core_C with ImportError('/opt/conda/lib/python3.10/site-packages/vllm/_core_C.abi3.so: undefined symbol: _ZN5torch6detail10class_baseC2ERKSsS3_SsRKSt9type_infoS6_')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.10/site-packages/sglang/launch_server.py", line 6, in <module>
    from sglang.srt.server import launch_server
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/server.py", line 44, in <module>
    from sglang.srt.hf_transformers_utils import get_tokenizer
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/hf_transformers_utils.py", line 36, in <module>
    from vllm.transformers_utils.configs import ChatGLMConfig, DbrxConfig
  File "/opt/conda/lib/python3.10/site-packages/vllm/__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "/opt/conda/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 11, in <module>
    from vllm.config import (CacheConfig, DecodingConfig, DeviceConfig,
  File "/opt/conda/lib/python3.10/site-packages/vllm/config.py", line 12, in <module>
    from vllm.model_executor.layers.quantization import QUANTIZATION_METHODS
  File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/layers/quantization/__init__.py", line 3, in <module>
    from vllm.model_executor.layers.quantization.aqlm import AQLMConfig
  File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/layers/quantization/aqlm.py", line 11, in <module>
    from vllm import _custom_ops as ops
  File "/opt/conda/lib/python3.10/site-packages/vllm/_custom_ops.py", line 7, in <module>
    from vllm._core_ext import ScalarType
  File "/opt/conda/lib/python3.10/site-packages/vllm/_core_ext.py", line 182, in <module>
    ScalarType = torch.classes._core_C.ScalarType
  File "/opt/conda/lib/python3.10/site-packages/torch/_classes.py", line 13, in __getattr__
    proxy = torch._C._get_custom_class_python_wrapper(self.name, attr)
RuntimeError: Tried to instantiate class '_core_C.ScalarType', but it does not exist! Ensure that it is registered via torch::class_`

### Reproduction
`
!python -m sglang.launch_server --model-path lemon07r/Gemma-2-Ataraxy-9B --port 2222`

### Environment
SHELL=/bin/bash
NV_LIBCUBLAS_VERSION=12.3.4.1-1
NVIDIA_VISIBLE_DEVICES=all
TENSORFLOW_IO_VERSION=0.37.0
NV_NVML_DEV_VERSION=12.3.101-1
NV_CUDNN_PACKAGE_NAME=libcudnn9-cuda-12
NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.20.3-1+cuda12.3
NV_LIBNCCL_DEV_PACKAGE_VERSION=2.20.3-1
KMP_WARNINGS=0
CUDA_MINOR_VERSION=3
HOSTNAME=04da6915c408
DL_ANACONDA_HOME=/opt/conda
NODE_OPTIONS=--max-old-space-size=4096
KAGGLE_DATA_PROXY_TOKEN=eyJhbGciOiJBMTI4S1ciLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0.3OKkZyBQlaCaih-0VOULor5zJLDdZq_sSOcsWwwumcpbxWfhXFkN3A.PJCb6rvvihJqoRWqOkIYXg.wDbE19g7-I4inKMj4jrsmudPC11UAPMpbSRYC_DDRAbxt_n7Lng0bw75ny_IyEK4a3geqCKelTyVF7B4ExTc_zzBFJw7BTdg-pmopUzaamPJ-5RCMjq8E4A_g8f10NvvP6NBKcCeicI-1k4VU5IOen_5wORXox95CB0Ez99JFju-iEAq_faowY3XX34l-yF7tcuuaFyHHE-ZI7suE2E39vdwKZ2vRCi6zMiQSBIt_iSFLTwTDR0VI8iYX_SaDold0TzB-mgFbwZfdhjRG16AUHF-hDkwgra5cnUrh_2FnIaLLNKrzBuCk5garOcyqLIx.E2hBmwSLcvnWA7p2K3W3oQ
NVIDIA_REQUIRE_CUDA=cuda>=12.3 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=525,driver<526 brand=unknown,driver>=525,driver<526 brand=nvidia,driver>=525,driver<526 brand=nvidiartx,driver>=525,driver<526 brand=geforce,driver>=525,driver<526 brand=geforcertx,driver>=525,driver<526 brand=quadro,driver>=525,driver<526 brand=quadrortx,driver>=525,driver<526 brand=titan,driver>=525,driver<526 brand=titanrtx,driver>=525,driver<526 brand=tesla,driver>=535,driver<536 brand=unknown,driver>=535,driver<536 brand=nvidia,driver>=535,driver<536 brand=nvidiartx,driver>=535,driver<536 brand=geforce,driver>=535,driver<536 brand=geforcertx,driver>=535,driver<536 brand=quadro,driver>=535,driver<536 brand=quadrortx,driver>=535,driver<536 brand=titan,driver>=535,driver<536 brand=titanrtx,driver>=535,driver<536
NV_LIBCUBLAS_DEV_PACKAGE=libcublas-dev-12-3=12.3.4.1-1
NV_NVTX_VERSION=12.3.101-1
TF_CPP_MIN_LOG_LEVEL=2
NV_CUDA_CUDART_DEV_VERSION=12.3.101-1
NV_LIBCUSPARSE_VERSION=12.2.0.103-1
KAGGLE_URL_BASE=https://www.kaggle.com/
NV_LIBNPP_VERSION=12.2.3.2-1
NCCL_VERSION=2.20.3-1
KAGGLE_DOCKER_IMAGE=gcr.io/kaggle-gpu-images/python
KAGGLE_KERNEL_INTEGRATIONS=
CONTAINER_NAME=tf2-gpu/2-16+cu123
PWD=/kaggle/working
TESSERACT_PATH=/usr/bin/tesseract
TENSORFLOW_VERSION=2.16.1
NV_CUDNN_PACKAGE=libcudnn9-cuda-12=9.0.0.312-1
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NV_NVPROF_DEV_PACKAGE=cuda-nvprof-12-3=12.3.101-1
NV_LIBNPP_PACKAGE=libnpp-12-3=12.2.3.2-1
BUILD_DATE=20240820-122555
NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
_=/usr/bin/printenv
NV_LIBCUBLAS_DEV_VERSION=12.3.4.1-1
NVIDIA_PRODUCT_NAME=CUDA
NV_LIBCUBLAS_DEV_PACKAGE_NAME=libcublas-dev-12-3
NV_CUDA_CUDART_VERSION=12.3.101-1
HOME=/root
LANG=C.UTF-8
CUDA_VERSION=12.3.2
NV_LIBCUBLAS_PACKAGE=libcublas-12-3=12.3.4.1-1
KMP_SETTINGS=false
FORCE_COLOR=1
NV_CUDA_NSIGHT_COMPUTE_DEV_PACKAGE=cuda-nsight-compute-12-3=12.3.2-1
PYDEVD_USE_FRAME_EVAL=NO
CLICOLOR=1
CLICOLOR_FORCE=1
NV_LIBNPP_DEV_PACKAGE=libnpp-dev-12-3=12.2.3.2-1
NV_LIBCUBLAS_PACKAGE_NAME=libcublas-12-3
NV_LIBNPP_DEV_VERSION=12.2.3.2-1
JPY_PARENT_PID=1
LD_LIBRARY_PATH_NO_STUBS=/usr/local/cuda/lib64:/usr/local/cuda/lib:/usr/local/lib/x86_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/opt/conda/lib
ANACONDA_PYTHON_VERSION=3.10
PYTHONPATH=/kaggle/lib/kagglegym:/kaggle/lib
TERM=xterm-color
NV_LIBCUSPARSE_DEV_VERSION=12.2.0.103-1
KAGGLE_DATA_PROXY_PROJECT=kaggle-161607
GIT_PAGER=cat
GCSFUSE_METADATA_IMAGE_TYPE=DLC
KAGGLE_USER_SECRETS_TOKEN=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..8g_NfgpPpKsfMZOyvqeaqQ.U6hfh6j7lO4765Cx62RYB6zZTsu799bK0_8xF_iyvrXTx8LW5NP0J34BcNU_tm_vwGaigj_6-7KzfZ7XGTKKGmcTIXVemlU_zdz5KwXWZpxI5DGXtl3FY3s2MC4bHtddeFlcfHGUKx08Dk7H6imPvg.u7BI0_QudsmaqntQswgkPg
LIBRARY_PATH=/usr/local/cuda/lib64/stubs:/opt/conda/lib
NV_CUDNN_VERSION=9.0.0.312
SHLVL=0
PAGER=cat
NV_CUDA_LIB_VERSION=12.3.2-1
NVARCH=x86_64
KAGGLE_KERNEL_RUN_TYPE=Interactive
NV_CUDNN_PACKAGE_DEV=libcudnn9-dev-cuda-12=9.0.0.312-1
PROJ_DATA=/opt/conda/share/proj
NV_CUDA_COMPAT_PACKAGE=cuda-compat-12-3
PIP_ROOT_USER_ACTION=ignore
MPLBACKEND=agg
NV_LIBNCCL_PACKAGE=libnccl2=2.20.3-1+cuda12.3
LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib:/usr/local/lib/x86_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/opt/conda/lib
KAGGLE_GCP_ZONE=us-west1-b
MKL_THREADING_LAYER=GNU
GIT_PYTHON_REFRESH=quiet
NV_CUDA_NSIGHT_COMPUTE_VERSION=12.3.2-1
CUDA_MAJOR_VERSION=12
GIT_COMMIT=846647d98e4999e565155e3324afbefd41bdd468
NV_NVPROF_VERSION=12.3.101-1
LC_ALL=POSIX
CUDA_HOME=/usr/local/cuda
KAGGLE_CONTAINER_NAME=kaggle_HxFEIrKoXF7U8OWyxdQLY5I6LcsoC4TomBFh5GzRmA-195242250-webtier
PATH=/opt/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PYTHONUSERBASE=/root/.local
NV_LIBNCCL_PACKAGE_NAME=libnccl2
NV_LIBNCCL_PACKAGE_VERSION=2.20.3-1
ENABLE_MULTI_ENV=false
KAGGLE_API_V1_TOKEN=/etc/secrets/kaggle/api-v1-token
KAGGLE_GRPC_DATA_PROXY_URL=dp.kaggle.net:443
KAGGLE_DATA_PROXY_URL=https://dp.kaggle.net/

**Comment by zhyncs** [comment]
```
pip install sglang[all]==0.3.0 --force-reinstall
```

**Comment by Abdulhanan535** [comment]
okay it worked.. but now facing another issue, is there any way to limit total memory? like 95% max usage of vram?
just need 1gb free.

**Comment by Abdulhanan535** [comment]
the model i'm loading is gemma 2 9B i have 30gb vram total and it's using all of it (2 gpus)

**Comment by zhyncs** [comment]
Try to use `--mem-fraction-static` https://github.com/sgl-project/sglang?tab=readme-ov-file#additional-server-arguments
