### ISSUE TITLE
[Feature] support smooth-quant?

### ISSUE THREAD

**Issue by Lzhang-hub** [sgl-project/sglang#1322]
### Checklist

- [ ] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 2. Please use English, otherwise it will be closed.

### Motivation

sglang support smooth-quant(w8a8)?

**Comment by zhyncs** [comment]
SGLang support FP8(W8A8) and it works well on H100

**Comment by Lzhang-hub** [comment]
Thanks, I just have A100-80G(sad)

**Comment by zhyncs** [comment]
BTW SmoothQuant (INT8 W8A8) has even lower accuracy than AWQ (W4A16). You might want to consider using AWQ instead.

**Comment by Lzhang-hub** [comment]
You are right! For my case, I want to speedup inference for batch=1, AWQ (W4A16) seems can not help.

**Comment by zhyncs** [comment]
> speedup inference for batch=1

You can enable torch compile with `--enable-torch-compile`

**Comment by Lzhang-hub** [comment]
thanks, I will try it.
