### ISSUE TITLE
[Bug] Unsupported architectures: ChatGLMForConditionalGeneration.

### ISSUE THREAD

**Issue by maxin9966** [sgl-project/sglang#1331]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

ValueError: Unsupported architectures: ChatGLMForConditionalGeneration. Supported list: ['ChatGLMForCausalLM', 'ChatGLMModel', 'CohereForCausalLM', 'DbrxForCausalLM', 'DeepseekForCausalLM', 'DeepseekV2ForCausalLM', 'ExaoneForCausalLM', 'GemmaForCausalLM', 'Gemma2ForCausalLM', 'GPTBigCodeForCausalLM', 'Grok1ForCausalLM', 'Grok1ModelForCausalLM', 'InternLM2ForCausalLM', 'LlamaForCausalLM', 'Phi3ForCausalLM', 'LlamaForClassification', 'LlamaEmbeddingModel', 'MistralModel', 'LlavaLlamaForCausalLM', 'LlavaQwenForCausalLM', 'LlavaMistralForCausalLM', 'LlavaVidForCausalLM', 'MiniCPMForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'StableLmForCausalLM', 'YiVLForCausalLM']

**vllm 0.5.5 supports this architecture. why has sglang always been unsupported?**

### Reproduction

1

### Environment

1

**Comment by zhyncs** [comment]
If a model, like Llama or Mixtral, becomes very popular, in other words, is widely used, we will definitely support it proactively as soon as possible. However, for other models that are not as popular, we highly welcome contributions from the community. I think if a framework wants to be adopted by enterprise users, it's not about supporting as many models as possible. Instead, it should focus on SOTA models and better performance, usability, and scalability.

**Comment by zhyncs** [comment]
You may refer to https://github.com/sgl-project/sglang/issues/1152

**Comment by maxin9966** [comment]
Thank you, I will try.

**Comment by merrymercy** [comment]
I think ChatGLM has been supported.
You can see https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/models/chatglm.py and https://sglang.readthedocs.io/en/latest/model_support.html
