### ISSUE TITLE
[Feature] KV Cache Compression

### ISSUE THREAD

**Issue by ghost** [sgl-project/sglang#1347]
### Checklist

- [x] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 2. Please use English, otherwise it will be closed.

### Motivation

For long context (long input prompts), the group I work with would love to have a compressed KV cache implementation, similar to H2O or SnapKV, integrated into SGLang.

### Related resources

- SnapKV: [paper](https://arxiv.org/pdf/2404.14469)
- Heavy-Hitter Oracle: [paper](https://arxiv.org/abs/2306.14048)

**Comment by merrymercy** [comment]
cc @andy-yang-1 who is working on something related https://github.com/andy-yang-1/DoubleSparse

**Comment by ghost** [comment]
Double Sparsity is a great paper! If @andy-yang-1 can provide brief tips on how to integrate it into SGLang, I would be very grateful.

Looking forward to hearing more discussion on this topic!

**Comment by andy-yang-1** [comment]
@vnkc1 I am working on integrating Double Sparsity into SGLang. We will notify you as soon as the PR is released!

**Comment by merrymercy** [comment]
https://github.com/sgl-project/sglang/pull/1459
