### ISSUE TITLE
[Bug] `served_model_name` argument in the server_arg.py is not checked

### ISSUE THREAD

**Issue by zhaochenyang20** [sgl-project/sglang#1348]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

No matter how you set this argument while initializing this parameter, you can pass in anything in the `model` arguments when sending requests.

```
python -m sglang.launch_server --model-path Alibaba-NLP/gte-Qwen2-7B-instruct \
--port 30000 --api-key sk-None-hello-world --host 0.0.0.0 --is-embedding --served-model-name whatever
```

```
curl http://localhost:30000/v1/embeddings \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer sk-None-hello-world" \
  -d '{
    "model": "Nothing",
    "input": "Once upon a time"
  }'
```

### Reproduction

Easy to reproduce.

### Environment

Easy to reproduce and it's just a software-level bug.

**Comment by zhaochenyang20** [comment]
Also, let me fix this these days and send the PR.

**Comment by merrymercy** [comment]
@zhaochenyang20 can you fix this soon?

**Comment by zhaochenyang20** [comment]
@merrymercy Yeah. Sorry for the late reply due to ICLR ddl. I will fix it before 10/06.

**Comment by zhyncs** [comment]
@zhaochenyang20 Any update?

**Comment by zhaochenyang20** [comment]
I think this bug is negotiable since we only serve one model at one port. OpenAI needs this parameter since they have multiple models on the same port. @zhyncs

**Comment by zhyncs** [comment]
@zhaochenyang20 When there is a demand for a model, such as loading meta-llama/Llama-3.1-8B-Instruct, but the actual user wants to request it using the name llama31-8b-instruct, you can understand it as an alias.

**Comment by zhaochenyang20** [comment]
So what's your opinion on this bug? Should we fix it? @zhyncs

**Comment by zhyncs** [comment]
Yeah I think so

**Comment by merrymercy** [comment]
It is used in the return value, but it is not checked. Actually, I think this is also a feature not only a bug.

**Comment by opslinux** [comment]
So how should I assign a value on sglang?
