### ISSUE TITLE
[Feature] DRY repetition penalty

### ISSUE THREAD

**Issue by vnkc1** [sgl-project/sglang#1350]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

DRY is a modern repetition penalty which ramps up penalties on N-grams to avoid looping behavior.

The penalty is commonly used on Llama 3.1 8B by practitioners to avoid repetition spirals.

### Related resources

https://github.com/oobabooga/text-generation-webui/pull/5677

https://www.reddit.com/r/SillyTavernAI/comments/1eg2pq5/good_info_on_dry_to_get_you_started_has/

**Comment by zhyncs** [comment]
@vnkc1 ref https://github.com/sgl-project/sglang/pull/1187

**Comment by ghost** [comment]
Thanks

**Comment by ghost** [comment]
Closing this issue
