### ISSUE TITLE
[Feature] KV Cache Quantization

### ISSUE THREAD

**Issue by ghost** [sgl-project/sglang#1351]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

Quantizing the KV cache (keys per-channel and values per-token) will allow higher throughput in long context situations.

### Related resources

- [KIVI quantization](https://arxiv.org/pdf/2402.02750)
- [KVQuant](https://arxiv.org/pdf/2401.18079)

**Comment by merrymercy** [comment]
cc @andy-yang-1 who is working on something related https://github.com/andy-yang-1/DoubleSparse

**Comment by ghost** [comment]
Thanks for the reply @merrymercy !

For the sake of clarification, I am referring to optimization techniques which store the KV cache in lower bit precision (not sparsity/compression).

**Comment by merrymercy** [comment]
Contributions are welcome!
also this is related
https://github.com/sgl-project/sglang/blob/39bb49d156f2319d2aec67c458c2db980bb0f4c3/README.md?plain=1#L227
