### ISSUE TITLE
[Feature] support qwen2 vl

### ISSUE THREAD

**Issue by zhyncs** [sgl-project/sglang#1352]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

https://huggingface.co/collections/Qwen/qwen2-vl-66cee7455501d7126940800d

**Comment by merrymercy** [comment]
cc @JustinLin610

**Comment by HiDostoyevskiy** [comment]
I eagerly look forward to the support for the qwen2-vl series models by sglang as soon as possible. Thanks!

**Comment by zhyncs** [comment]
> I eagerly look forward to the support for the qwen2-vl series models by sglang as soon as possible. Thanks!

@ispobock's partner is currently working on it.

**Comment by bash99** [comment]
I would like to know will sglang support qwen2 vl gptq-int4 release with more than one GPU?

https://qwen.readthedocs.io/en/latest/quantization/gptq.html said vllm don't work and need padding and quantizated again.

**Comment by zhyncs** [comment]
ref https://github.com/sgl-project/sglang/pull/1546

**Comment by John-Ge** [comment]
Hello, does current QWen2-VL in sglang support video input like LLaVA-OneVision? Thanks!
