### ISSUE TITLE
[Feature] support LLaVA-NeXT-Video-32B-Qwen

### ISSUE THREAD

**Issue by HarperGG** [sgl-project/sglang#1356]
### Checklist

- [x] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 2. Please use English, otherwise it will be closed.

### Motivation

Hope to support [LLaVA-NeXT-Video-32B-Qwen](https://huggingface.co/lmms-lab/LLaVA-NeXT-Video-32B-Qwen)   model

**Comment by zhyncs** [comment]
@Luodian May you help take a look

**Comment by merrymercy** [comment]
cc @Luodian @kcz358  @ZhangYuanhan-AI 

But I think you can use llava-onevision now. https://github.com/sgl-project/sglang/blob/dff2860a690757966e408b598a8f0b47a29a4713/test/srt/test_vision_openai_server.py#L211
