### ISSUE TITLE
[Bug] it seems memory leak in zmp?

### ISSUE THREAD

**Issue by CSEEduanyu** [sgl-project/sglang#1358]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

128134 memory blocks: 5104.2 KiB
Traceback:
  File "/usr/local/lib/python3.10/dist-packages/zmq/_future.py", line 374
    loaded = load(buf)

### Reproduction

tracemalloc in detokenizer_manager.py

### Environment

llama2-13B A800*1

**Comment by zhyncs** [comment]
@CSEEduanyu You can analyze in detail using this method: https://github.com/InternLM/lmdeploy/issues/1334#issuecomment-2017418190

**Comment by CSEEduanyu** [comment]
> @CSEEduanyu You can analyze in detail using this method: [InternLM/lmdeploy#1334 (comment)](https://github.com/InternLM/lmdeploy/issues/1334#issuecomment-2017418190)

https://github.com/zeromq/pyzmq/issues/1928 I think the description seems very similar to this scenario, and you should be able to reproduce it easily, with small models and high qps. The main process responsible for forward() is ok, but both the tokenzier and detokenzer processes had significant memory leaks

**Comment by zhyncs** [comment]
Can you provide a minimal reproducible demo, please do not use such simple descriptions.

**Comment by CSEEduanyu** [comment]
> Can you provide a minimal reproducible demo, please do not use such simple descriptions.

Sorry, for some reason I can't provide any code or scripts or more information. I know this is not kind to reproduce this problem, sorry again. However, it is true that running in production for more than 12 hours in a row will cause significant memory leaks (depending on the request qps). This problem occurs in both llama and mixtral models, and I think it is not relevant to the model. The main memory leak is the process in which the tokenizer is running, and you can see that RES is increasing using linux top command. As for the reason of memory leak, the information I provided before is wrong, which has nothing to do with zmq. I am still investigating the real reason. Or you can wait for someone else to report this problem, and maybe they can provide a reproduction demo.
