### ISSUE TITLE
deepseek-v2 enable-mla 4x slower

### ISSUE THREAD

**Issue by cdj0311** [sgl-project/sglang#1369]
hi,
The DeepSeek-Coder-V2-Lite-Base  inference with --enable-mla on A100(the same L20)，but get 4x slower than mha, the server command:
```` 
# with --enable-mla
python3 -m sglang.launch_server --model deepseek-ai/DeepSeek-Coder-V2-Lite-Base --enable-mla --disable-radix --trust-remote-code
````
speed: 31ms/token
```` 
# without --enable-mla
python3 -m sglang.launch_server --model deepseek-ai/DeepSeek-Coder-V2-Lite-Base --trust-remote-code
````
speed: 8ms/token

**Comment by zhyncs** [comment]
We have improved the maximum throughput. But with small batch sizes, due to Triton Runtime not yet supporting CUDA Graph, there will be higher latency.
duplicate https://github.com/sgl-project/sglang/issues/1264#issuecomment-2322917622

**Comment by merrymercy** [comment]
Try this PR https://github.com/sgl-project/sglang/pull/1401
