### ISSUE TITLE
[Bug] too many processes 

### ISSUE THREAD

**Issue by wellhowtosay** [sgl-project/sglang#1382]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

app.py 
```python
def set_qwen_runtime():
    runtime = sgl.Runtime(
        model_path="/root/luka/llm/cloth-attri-qwen-vl-chat-int4/checkpoint-6038-gptq-int4",
        tokenizer_path="/root/luka/llm/cloth-attri-qwen-vl-chat-int4/checkpoint-6038-gptq-int4",
        disable_cuda_graph=True,
        mem_fraction_static=0.90,
        enable_torch_compile=True
    )
    # runtime.endpoint.chat_template = get_chat_template("chatml")
    # runtime = sgl.Runtime(
    #     model_path="lmms-lab/llava-next-72b",
    #     tokenizer_path="lmms-lab/llavanext-qwen-tokenizer",
    # )
    runtime.endpoint.chat_template = get_chat_template("chatml-qwen")
    sgl.set_default_backend(runtime)
    return runtime

```

I run it with `python3 app.py`,  and it somehow creates 184 processes
```shell
ps aux|grep "python3 app.py" |wc -l
```
185

### Environment
a docker run on a machine with TWO Intel(R) Xeon(R) Platinum 8457C 
```shell
cat /proc/cpuinfo| grep "processor"| wc -l
180
```
But the docker used only 16 cores

**Comment by merrymercy** [comment]
Can you help us debug more and find out what these processes are?
