### ISSUE TITLE
[Feature] Can centos7 use this project?

### ISSUE THREAD

**Issue by luo647** [sgl-project/sglang#1387]
### Checklist

- [ ] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 2. Please use English, otherwise it will be closed.

### Motivation

I can't install flashinfer-0.1.6;
" Download NCCL 2.22.3, for CUDA 12.4 " maybe not support centos7 ?
Have you ever try running on centos7?

**Comment by zhyncs** [comment]
cc @yzh119

**Comment by m0g1cian** [comment]
You can install CUDA compat if you cannot directly upgrade your nvidia driver. 
Otherwise, everything is working fine in CentOS 7 on my end.

**Comment by zhyncs** [comment]
FlashInfer is built with `pytorch/manylinux-builder` and it should be compatible with CentOS 7. I am unable to reproduce your issue.
https://github.com/flashinfer-ai/flashinfer/blob/52dab1d4a4d7e5d910a8c695de911d979d6f2038/.github/workflows/release_wheel.yml#L57
