### ISSUE TITLE
[Feature] Support torch profiler

### ISSUE THREAD

**Issue by danielhua23** [sgl-project/sglang#1388]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

Hi, I did not find sglang support torch profiler, Could you pls support torch profiler like vllm just adding --profile?

**Comment by merrymercy** [comment]
Contributions are welcome! We do support nsight profiling https://github.com/sgl-project/sglang/blob/main/docs/en/benchmark_and_profiling.md#profile-with-nsight

**Comment by vaibhawvipul** [comment]
@merrymercy I would like to work on this.

**Comment by zhyncs** [comment]
ref https://github.com/sgl-project/sglang/pull/1604 https://github.com/sgl-project/sglang/pull/1626
