### ISSUE TITLE
[Bug] 'LlamaTokenizerFast' object has no attribute 'tokenizer'

### ISSUE THREAD

**Issue by zwc163** [sgl-project/sglang#1391]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

When I used the multimodal model, the following error was reported  
File "python/sglang/srt/managers/tokenizer_manager.py", line 133, in __init__
    self.tokenizer = self.processor.tokenizer
AttributeError: 'LlamaTokenizerFast' object has no attribute 'tokenizer'. Did you mean: '_tokenizer'?

I checked the source code of the transformer library and confirmed that there is no such attribute. Has this code been tested?
### Reproduction

I used the llavallama model

### Environment

transformers==4.44.2
sglang v0.30

**Comment by BaiStone2017** [comment]
same error

**Comment by BaiStone2017** [comment]
> same error

for janus-pro the solution is：
pip install  addict
