### ISSUE TITLE
[Feature] support awq of deepseek-v2 or deepseek-v2.5

### ISSUE THREAD

**Issue by tutu329** [sgl-project/sglang#1396]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

sglang 3.0 can run DeepSeek-Coder-V2-Lite-Instruct.
but running DeepSeek-Coder-V2-Lite-Instruct-AWQ reports:
"
ValueError: The input size is not aligned with the quantized weight shape. This can be caused by too large tensor parallel size.
"

sglang command is :
python -m sglang.launch_server --model-path=/path/DeepSeek-Coder-V2-Lite-Instruct-AWQ --host=0.0.0.0 --port=8001 --tp=8 --trust-remote-code --max-total-tokens=15000

**Comment by 1cekrim** [comment]
It seems that vllm does not support deepseek awq. The k size of deepseek attention is 192, which is not a multiple of 128, and GPTQ_MARLIN_MIN_THREAD_K is 128, which causes an assertion. If I change this value to 64, the assertion passes, but the get_quant_method fails in FusedMoE as None.

**Comment by Xu-Chen** [comment]
> It seems that vllm does not support deepseek awq. The k size of deepseek attention is 192, which is not a multiple of 128, and GPTQ_MARLIN_MIN_THREAD_K is 128, which causes an assertion. If I change this value to 64, the assertion passes, but the get_quant_method fails in FusedMoE as None.

Supporting MLA with awq is also very important
