### ISSUE TITLE
[Bug] This modeling file requires the following packages that were not found in your environment: datamodel_code_generator. Run `pip install datamodel_code_generator`

### ISSUE THREAD

**Issue by cicicji** [sgl-project/sglang#1398]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

When attempting to run openBmb/MiniCPM 3.0 using Docker, I encountered an issue related to missing dependencies. The error log indicates that certain dependencies required for the project are not installed. Could you please provide guidance on how to resolve this issue, or update the Docker environment to include the necessary dependencies?

### Reproduction

ocker run --gpus '"device=0,1"'     -p 11436:30000     -v /home/jszc/vllm:/root/.cache/modelscope    --ipc=host     --name sglang-minicpm3-4b   my_sglang:v0.3.0-cu124-updated     python3 -m sglang.launch_server  --model /root/.cache/modelscope/MiniCPM3-4B  --host 0.0.0.0 --port 30000 --tp 2 --mem-fraction-static 0.75 --chunked-prefill-size 8192 --enable-p2p-check --schedule-policy fcfs --schedule-conservativeness 0.3 --trust-remote-code

### Environment

docker

**Comment by cicicji** [comment]
docker run --gpus '"device=0,1"'     -p 11436:30000     -v /home/jszc/vllm:/root/.cache/modelscope    --ipc=host     --name sglang-minicpm3-4b   my_sglang:v0.3.0-cu124-updated     python3 -m sglang.launch_server  --model /root/.cache/modelscope/MiniCPM3-4B  --host 0.0.0.0 --port 30000 --tp 2 --mem-fraction-static 0.75 --chunked-prefill-size 8192 --enable-p2p-check --schedule-policy fcfs --schedule-conservativeness 0.3 --trust-remote-code

my  Reproduction fix

**Comment by merrymercy** [comment]
fixed by https://github.com/sgl-project/sglang/pull/1492
please wait for the next release.
