### ISSUE TITLE
KV cache pool leak detected!

### ISSUE THREAD

**Issue by exceedzhang** [sgl-project/sglang#140]
python -m sglang.launch_server --model-path /root/autodl-tmp/Yi-6B-Chat --port 8000 --mem-fraction-static 0.9 --tokenizer-mode auto --tokenizer-path /root/autodl-tmp/Yi-6B-Chat --trust-remote-code

<img width="1439" alt="image" src="https://github.com/sgl-project/sglang/assets/4583537/dd6decd6-99a1-420e-8be2-b9a130d972fb">

python3 bench_throughput.py  --tokenizer /root/autodl-tmp/Yi-6B-Chat  --dataset /root/autodl-tmp/ShareGPT_V3_unfiltered_cleaned_split.json   --port 8000 --backend srt --trust-remote-code --num-prompts 2048

<img width="1512" alt="image" src="https://github.com/sgl-project/sglang/assets/4583537/5a47f9e6-e356-4269-859a-0e0e395e6d89">

**Comment by aliencaocao** [comment]
Same issue on llava1.6 7b mistral

**Comment by gintasz** [comment]
I observe this with `meta-llama/Meta-Llama-3-8B-Instruct`. I think it’s very critical issue

**Comment by thomasgauthier** [comment]
Also experiencing this with `meta-llama/Meta-Llama-3-8B-Instruct`, this makes the library more or less unusable for me. Which is a shame because I love sglang.

**Comment by gintasz** [comment]
> Also experiencing this with `meta-llama/Meta-Llama-3-8B-Instruct`, this makes the library more or less unusable for me. Which is a shame because I love sglang.

I've reverted back to 0.1.14 and added registration of llama-3 prompt template, copied from newer versions. It works fine. I'm also calling `flush cache` after each batch processing is done.

**Comment by m0g1cian** [comment]
> python -m sglang.launch_server --model-path /root/autodl-tmp/Yi-6B-Chat --port 8000 --mem-fraction-static 0.9 --tokenizer-mode auto --tokenizer-path /root/autodl-tmp/Yi-6B-Chat --trust-remote-code
> 
> <img alt="image" width="1439" src="https://private-user-images.githubusercontent.com/4583537/302088747-dd6decd6-99a1-420e-8be2-b9a130d972fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NzIxNjIsIm5iZiI6MTcxNzQ3MTg2MiwicGF0aCI6Ii80NTgzNTM3LzMwMjA4ODc0Ny1kZDZkZWNkNi05OWExLTQyMGUtOGJlMi1iOWExMzBkOTcyZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMDMzMTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRmYzM3MGI0ZTI5Y2M4ZDRjZTBkZTM3MTkwYjI0ZGNmOWJlMWM5NWI4MTAyN2IzYTIxYjZjMzRjODY5Mzc3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZsEmyShR_ySA-c2tTOgy5x6Korpts5HIin4gPsKtQJg">
> python3 bench_throughput.py --tokenizer /root/autodl-tmp/Yi-6B-Chat --dataset /root/autodl-tmp/ShareGPT_V3_unfiltered_cleaned_split.json --port 8000 --backend srt --trust-remote-code --num-prompts 2048
> 
> <img alt="image" width="1512" src="https://private-user-images.githubusercontent.com/4583537/302088789-5a47f9e6-e356-4269-859a-0e0e395e6d89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NzIxNjIsIm5iZiI6MTcxNzQ3MTg2MiwicGF0aCI6Ii80NTgzNTM3LzMwMjA4ODc4OS01YTQ3ZjllNi1lMzU2LTQyNjktODU5YS0wZTBlMzk1ZTZkODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMDMzMTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTkxN2RkYmQxNmMwYTY3M2JmOTRkZDRkNzBmNDRkYzc1NTYxYzlkNTQwNmJhNThmNDYyZDRkMmZiYjY3MzNiNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QHK13ZM1DOwObJNTqp2_xR9nwEIXfzDU8C7rvBjnfjk">

My educated guess is the prefix length fits  the `max_seq_len` of the model. However, during generation, the generated length is exceeding the limit, which somehow causes this KV cache leak.

**Comment by gintasz** [comment]
@m0g1cian I've observed that with some Regex formulations, current versions will get stuck in an infinite generation long beyond max token length, check my other issue: https://github.com/sgl-project/sglang/issues/414

**Comment by m0g1cian** [comment]
@Gintasz As of now, I just set `max_tokens` parameter as a safeguard in every `sgl.gen()` to avoid such infinite generation issue.

**Comment by gintasz** [comment]
> @Gintasz As of now, I just set `max_tokens` parameter as a safeguard in every `sgl.gen()` to avoid such infinite generation issue.

Yes, but with some regex formulations, this 'max_tokens' will be ignored, as demonstrated in that linked issue
