### ISSUE TITLE
[Bug] ImportError : cannot import name 'gemma_fused_add_rmsnorm' from 'flashinfer.norm'

### ISSUE THREAD

**Issue by luo647** [sgl-project/sglang#1404]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

I have installed flashinfer-0.1.6; 
But only "rmsnorm" and "fused_add_rmsnorm" methods are available here (norm.py).

### Reproduction

python3 -m sglang.launch_server --model-path /home/models/deepseekcoder-6.7b-base/ --port 30000

### Environment

/usr/local/lib/python3.9/site-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'underscore_attrs_are_private' has been removed
  warnings.warn(message, UserWarning)
Python: 3.9.9 (main, Feb 28 2023, 12:44:34) [GCC 10.3.1]
CUDA available: True
GPU 0,1: NVIDIA A100-PCIE-40GB
GPU 0,1 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.99
CUDA Driver Version: 550.107.02
PyTorch: 2.4.0+cu121
sglang: 0.3.0
flashinfer: 0.1.6
triton: 3.0.0
transformers: 4.44.2
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.5
fastapi: 0.114.0
hf_transfer: 0.1.8
huggingface_hub: 0.24.6
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.9.1
uvicorn: 0.30.6
uvloop: 0.20.0
zmq: 26.2.0
vllm: 0.5.5
multipart: 0.0.9
openai: 1.44.1
anthropic: 0.34.2
NVIDIA Topology:
        GPU0    GPU1    NIC0    NIC1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS     SYS     SYS     12-17,60-65     2               N/A
GPU1    SYS      X      SYS     SYS     36-41,84-89     6               N/A
NIC0    SYS     SYS      X      PIX
NIC1    SYS     SYS     PIX      X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: rocep1s0f0
  NIC1: rocep1s0f1

ulimit soft: 65535

**Comment by zhyncs** [comment]
ref https://github.com/flashinfer-ai/flashinfer/actions/runs/10582649299
commit ac41d1b

**Comment by luo647** [comment]
> ref https://github.com/flashinfer-ai/flashinfer/actions/runs/10582649299 commit ac41d1b

I didn't understand, could you explain it in more detail？
