### ISSUE TITLE
[Feature] Support AMD GPU via PyTorch for ROCm

### ISSUE THREAD

**Issue by HaiShaw** [sgl-project/sglang#1419]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

Enable SGLang on AMD GPUs !

**Comment by zhyncs** [comment]
ref
https://github.com/sgl-project/sglang/pull/1420
https://github.com/sgl-project/sglang/pull/1453
