### ISSUE TITLE
[Bug] missing max_workers param when initiate ProcessPoolExecutor 

### ISSUE THREAD

**Issue by wellhowtosay** [sgl-project/sglang#1424]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

https://github.com/sgl-project/sglang/blob/30b404ce72b52e02076fa46ff5ee16f3e1a68a98/python/sglang/srt/managers/tokenizer_manager.py#L122

the default value for max_workers is the num of cpu on the physical server, this may cause problems when running on a docker with much less cpu cores than its  physical server.

### Reproduction

runner sglang on a docker with much less cpu cores than its  physical server.

### Environment

.

**Comment by merrymercy** [comment]
@wellhowtosay Thanks for reporting. Can you send a fix?

**Comment by wellhowtosay** [comment]
> @wellhowtosay Thanks for reporting. Can you send a fix?

https://github.com/sgl-project/sglang/pull/1456
