### ISSUE TITLE
Error under high concurrency. `sqlite3.DatabaseError: database disk image is malformed`

### ISSUE THREAD

**Issue by Ja1Zhou** [sgl-project/sglang#143]
The error stack is as follows:
```bash
File "/User/jay/sglang/python/sglang/api.py", line 37, in Runtime
  from sglang.srt.server import Runtime
File "/User/jay/sglang/python/sglang/srt/server.py", line 47, in <module>
  from sglang.srt.managers.router.manager import start_router_process
File "/User/jay/sglang/python/sglang/srt/managers/router/manager.py", line 8, in <module>
  from sglang.srt.managers.router.model_rpc import ModelRpcClient
File "/User/jay/sglang/python/sglang/srt/managers/router/model_rpc.py", line 15, in <module>
  from sglang.srt.constrained.fast_forward import FastForwardCache
File "/User/jay/sglang/python/sglang/srt/constrained/fast_forward.py", line 2, in <module>
  from sglang.srt.constrained.disk_cache import disk_cache
File "/User/jay/sglang/python/sglang/srt/constrained/disk_cache.py", line 13, in <module>
  memory = Cache(cache_dir, eviction_policy="none", cull_limit=0)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/User/jay/miniconda3/envs/sglang/lib/python3.11/site-packages/diskcache/core.py", line 500, in __init__
  self.reset(key, value)
File "/User/jay/miniconda3/envs/sglang/lib/python3.11/site-packages/diskcache/core.py", line 2409, in reset
  sql_retry(statement, (value, key))
File "/User/jay/miniconda3/envs/sglang/lib/python3.11/site-packages/diskcache/core.py", line 666, in _execute_with_retry
  return sql(statement, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.DatabaseError: database disk image is malformed
```
Should be related to https://github.com/sgl-project/sglang/blob/82fa69b3cc0c8b9b3b31148f1d53070649f0d433/python/sglang/srt/constrained/disk_cache.py#L13

Would it be fine to change this line
https://github.com/sgl-project/sglang/blob/82fa69b3cc0c8b9b3b31148f1d53070649f0d433/python/sglang/srt/constrained/disk_cache.py#L12
to
```python
cache_dir = os.environ.get("SGLANG_CACHE_DIR", f"{home_dir}/.cache/sglang/{os.getpid()}")
```

Probably @hnyls2002

**Comment by merrymercy** [comment]
Could you contribute a PR?

**Comment by hnyls2002** [comment]
@Ja1Zhou Could you provide more details about how to reproduce this error? The disk cache python lib is supposed to be concurrent with these operations. And for the identical object, we only read/write it with disk_cache only once. The disk_cache in our lib is designed to share identical objects across different processes.

**Comment by Ja1Zhou** [comment]
@hnyls2002 I am using SLURM to launch multiple tasks using the same network file system. Each task starts a runtime and I got this error.

**Comment by hnyls2002** [comment]
@Ja1Zhou Thanks! I am not sure whether this is a python disk_cache internal error or our inappropriate usage. I will check it later trying to figure it out.
For current usage, you can comment disk cache decorator, and our lib can also perform well.

**Comment by hnyls2002** [comment]
@Ja1Zhou I have tested running multiple SGL runtime and calling JSON regex with disk cache simultaneously. I tested on 4xA10 GPUs locally, without notebook, Slurm, or network file systems.
All the operations with the disk cache should be concurrent; I am still confused about what you have met.

You can now add `--disable-disk-cache`(#160) to avoid the disk cache crash on our latest main branch. This option will bring some initial overhead only when launching the server, so don't worry about it.
