### ISSUE TITLE
[Bug] The latest Sglang docker image cannot start online services

### ISSUE THREAD

**Issue by CedricHwong** [sgl-project/sglang#1443]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

I pulled the latest Sglang docker image and got the following error message when running it:

user@MS-7D70:# docker logs cosmic-32k

==========
== CUDA ==
==========

CUDA Version 12.1.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/sgl-workspace/sglang/__init__.py", line 1, in <module>
    raise Exception(
Exception: You imported 'sglang' from the git repo root directory 'sglang', which is incorrect. You should import it from 'sglang/python/sglang'. Please do not run your scripts adjacent to the git repo root directory.

# Docker  Version 
Docker version 27.2.0, build 3ab4256

# Image ID
a370b6c8a8a9

# OS 
Description:	Ubuntu 24.04.1 LTS

# nvidia-smi
Tue Sep 17 15:06:34 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:01:00.0 Off |                  N/A |
| 30%   41C    P8              25W / 350W |     10MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 3090        Off | 00000000:02:00.0 Off |                  N/A |
| 30%   39C    P8              24W / 350W |    274MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         

### Reproduction

docker run -itd --name qwen2 --runtime nvidia --gpus "device=0"  \
    -p 10087:30000 \
    -v /Qwen2-7B-Instruct:/qwen2\
    --ipc=host \
    lmsysorg/sglang:latest \
    python3 -m sglang.launch_server --model-path /qwen2 --host 0.0.0.0 --port 30000  --dtype bfloat16 --served-model-name qwen2 --log-requests 

### Environment

Using docker

**Comment by zhyncs** [comment]
cc @Ying1123

**Comment by merrymercy** [comment]
Thanks for reporting. It has been fixed by #1432.
We also released a new version and docker image. Please wait for this action to finish (in 10 mins) and you can pull the latest image again. (https://github.com/sgl-project/sglang/actions/runs/10899655401)
