### ISSUE TITLE
分类准确率下降，性能提升一倍，咋解决呢？

### ISSUE THREAD

**Issue by xxm1668** [sgl-project/sglang#149]
qwen自带推理：
第一身份准确率：0.968421052631579
第二身份准确率：0.9368421052631579
一条数据平均耗时：0.9585727064233077

slang推理：
第一身份准确率：0.6631578947368421
第二身份准确率：0.7894736842105263
一条数据平均耗时：0.5773725032806396

**Comment by Ying1123** [comment]
@xxm1668 你好，可以给一些例子，使用方法信息，让我们复现吗？可能是prompt没有对齐之类的原因。

**Comment by xxm1668** [comment]
微调的qwen1.5-chat-14b，对电话录音文本说话人进行分类的。输出的结果如：{"对话人1身份":"","对话人2身份":""}
