### ISSUE TITLE
After enabling tensor parallelism (tp-size=2), there is no response

### ISSUE THREAD

**Issue by wushixong** [sgl-project/sglang#150]
my command is:
```shell
CUDA_VISIBLE_DEVICES="2,4" python -m sglang.launch_server --model-path  ./Yi-34B-Chat --trust-remote-code --port 30000 --tp-size 2 
``` 
when I run the demo code, **there is nothing returned.** 

```python
from sglang import function, system, user, assistant, gen, set_default_backend, RuntimeEndpoint

@function
def multi_turn_question(s, question_1, question_2):
    s += system("You are a helpful assistant.")
    s += user(question_1)
    s += assistant(gen("answer_1", max_tokens=256))
    s += user(question_2)
    s += assistant(gen("answer_2", max_tokens=256))

set_default_backend(RuntimeEndpoint("http://localhost:30000"))

state = multi_turn_question.run(
    question_1="What is the capital of the United States?",
    question_2="List two local attractions.",
)

for m in state.messages():
    print(m["role"], ":", m["content"])
```

**But when I  remove  "--tp-size 2 " in the command ,which means the model is only in 1 GPU , it works well.**

**Comment by Reichenbachian** [comment]
I'm also running into this.

**Comment by felifri** [comment]
me too

**Comment by lss15151161** [comment]
me too.

**Comment by isofun** [comment]
I also meet similar problem. With tp=2, the log stop at:
[2025-03-07 17:58:29 TP0] Prefill batch. #new-seq: 1, #new-token: 7, #cached-token: 0, token usage: 0.00, #running-req: 0, #queue-req: 0,
But if i remove it, it works fine with the following log:
[2025-03-07 17:56:12] INFO:     127.0.0.1:26962 - "POST /generate HTTP/1.1" 200 OK
[2025-03-07 17:56:12] The server is fired up and ready to roll!

**Comment by realJaydenCheng** [comment]
same to me 😭
