### ISSUE TITLE
[Feature] _get_pixel_values needs to return tgt_sizes

### ISSUE THREAD

**Issue by huangzl18883** [sgl-project/sglang#1514]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

For some multi-modal models like minicpmv-2.6, it is necessary to obtain tgt_sizes when processing images, but the current _get_pixel_values only returns pixel_values and not tgt_sizes
 
Refer to https://huggingface.co/openbmb/MiniCPM-V-2_6/blob/4e4be000cd81feda8b96d14b53f1791b4010b038/image_processing_minicpmv.py#L415

**Comment by merrymercy** [comment]
Thanks for reporting this. Contributions are welcome!
