### ISSUE TITLE
Accuracy reduction of Lora

### ISSUE THREAD

**Issue by yileld** [sgl-project/sglang#1519]
I used lora trained on qwen2（using the lora code just updated recent weeks）, but the accuracy of test dataset reduced from 75 to 67.
Then I merged lora weights into base model, the accuracy was right.
Is there something wrong with lora? Or some other pipeline difference between lora and normal model?

**Comment by Ying1123** [comment]
Hi @yileld, would you mind sharing the Lora weights with me so that I can test them? You can join our [slack](https://join.slack.com/t/sgl-fru7574/shared_invite/zt-2nsybupkx-oEQ8vMxFkMOC0d5ECB_A2A) and message me.

**Comment by yileld** [comment]
It solved, I forget to disable cuda graph. Although lora model output logprobs are still different from merge model, but the accuracy of dataset is right.
