### ISSUE TITLE
[Feature] add support for llama 3.2

### ISSUE THREAD

**Issue by Stealthwriter** [sgl-project/sglang#1523]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

data did not match any variant of untagged enum ModelWrapper at line 1251003 column 3

### Reproduction

try to run llama 3.2 3b

### Environment

docker

**Comment by shubhanshu786** [comment]
vLLM as already added support for Llama 3.2. SGLang, should do that too fast.

**Comment by zhyncs** [comment]
Yes, vLLM currently only supports a single image. @hnyls2002 is working on support Llama 3.2 3b functionality.

**Comment by 81549361** [comment]
> Yes, vLLM currently only supports a single image. @hnyls2002 is working on support Llama 3.2 3b functionality.

I just need to reinstall sglang and update some packages to reason about llama 3b

**Comment by merrymercy** [comment]
Will be ready soon https://github.com/sgl-project/sglang/pull/1551

**Comment by slin1237** [comment]
any ETA? And would this support all family and multiple images?

**Comment by merrymercy** [comment]
Yes, it will support all family and multi image.

**Comment by merrymercy** [comment]
supported by #1551
