### ISSUE TITLE
[Feature] VLLM 6.0 support

### ISSUE THREAD

**Issue by arunpatala** [sgl-project/sglang#1527]
### Checklist

- [ ] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 2. Please use English, otherwise it will be closed.

### Motivation

VLLM 6.0 supports better throughput and latency with the latest version. Is there a roadmap to integrate the latest VLLM version. Can you please let me know what is stopping from using it? 

Thanks for a great library. 

### Related resources

https://blog.vllm.ai/2024/09/05/perf-update.html

**Comment by zhyncs** [comment]
SGLang only relies on the Linear and Distributed parts of vLLM. SGLang's runtime has no relation to vLLM, updating vLLM version currently doesn't make much sense.

**Comment by arunpatala** [comment]
ok thanks.
