### ISSUE TITLE
Print out what the model saw?

### ISSUE THREAD

**Issue by cinjon** [sgl-project/sglang#1560]
I have a finetuned model that I'm trying to run with SGLang. I want to verify that the prompt format, etc, is correct. Is there a flag to output the prompt each time?

**Comment by merrymercy** [comment]
https://github.com/sgl-project/sglang/blob/91877a9f9c8763a504373e41d238dbf9adf65f8c/python/sglang/srt/server_args.py#L373-L377

**Comment by CedricHwong** [comment]
> https://github.com/sgl-project/sglang/issues/1608#issue-2572891867

@merrymercy  Please help me look at this related question, thank you
