### ISSUE TITLE
[Feature] Add `choices` in `/generate` endpoint and add `min_new_tokens` in `sgl.gen()`

### ISSUE THREAD

**Issue by TING2938** [sgl-project/sglang#1564]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

Add `choices` in `/generate` endpoint and add `min_new_tokens` in `sgl.gen()`

**Comment by ByronHsu** [comment]
@merrymercy @Ying1123 I can help working on this if this makes sense to you

**Comment by ByronHsu** [comment]
@merrymercy choice is not supported yet
