### ISSUE TITLE
[doc] Chinese Documentation Translation Available for sglang

### ISSUE THREAD

**Issue by khum08** [sgl-project/sglang#1565]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

We have translated the sglang documentation into Chinese using Gemini 1.5 Flash. We believe this could be valuable for your Chinese-speaking users and contributors.
The translated documentation is currently hosted at: https://sglang-zh.llamafactory.cn/
We're willing to contribute the translated files directly to your repository if you're interested in incorporating them officially.

**Comment by zhyncs** [comment]
Contribution are welcome!
