### ISSUE TITLE
[Bug] `Meta-Llama-3.1-8B-Instruct` triggers "Detected errors during sampling! NaN in the probability." under high concurrency/RPS.

### ISSUE THREAD

**Issue by tongyx361** [sgl-project/sglang#1571]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

The `Meta-Llama-3.1-8B-Instruct` hosted by SRT causes "Detected errors during sampling! NaN in the probability."  under high concurrency/RPS.
I also tried with an MoE model but didn't encounter similar errors.

An issue under similar circumstances in #1434 was fixed by updating to the newest version, but this new bug was introduced.

### Reproduction

I launch the server by running:

```bash
python -m sglang.launch_server \
    --model-path "meta-llama/Meta-Llama-3.1-8B-Instruct" \
    --dp 2 --quantization fp8 --kv-cache-dtype fp8_e5m2
```

Below is the minimal reproducible demo:

```python
import asyncio
import json
import os
import time

import requests
from openai import AsyncOpenAI

client = AsyncOpenAI(api_key="EMPTY", base_url=os.getenv("OPENAI_API_BASE", "http://localhost:30000/v1"))

MATH500_URL: str = (
    "https://github.com/openai/prm800k/raw/main/prm800k/math_splits/test.jsonl"
)
data = [json.loads(line) for line in requests.get(MATH500_URL).iter_lines()]

req_data = [
    {
        "model": "default",
        "messages": [{"role": "user", "content": d["problem"]}],
        "stream": False,
        "extra_body": {
            "logprobs": False,
            "top_logprobs": 0,
            "max_tokens": 4096,
            "temperature": 0,
            "top_p": 0.95,
        },
    }
    for d in data
]


async def main(n: int) -> None:
    resps = await asyncio.gather(
        *[client.chat.completions.create(**req) for req in req_data[:n]]
    )
    print(f"{resps[0]} = ")
    with open(f"tmp{n}.jsonl", "w") as f:
        for resp in resps:
            resp_str = resp.json()
            if isinstance(resp_str, dict):
                resp_str = json.dumps(resp_str)
            f.write(resp_str + "\n")


if __name__ == "__main__":
    for n in [64, 128]:
        # NOTE: 64 works well, 128 triggers the error
        t_start = time.time()
        asyncio.run(main(n))  # Output normally
        t_span = time.time() - t_start
        print(
            f"Time taken {t_span:.2f} seconds for {n} requests -> RPS: {n / t_span:.2f}"
        )
```

### Environment

```
$ python3 -m sglang.check_env
/gpfs/public/infra/miniconda3/envs/metagen/lib/python3.11/site-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'underscore_attrs_are_private' has been removed
  warnings.warn(message, UserWarning)
Python: 3.11.10 | packaged by conda-forge | (main, Sep 10 2024, 11:01:28) [GCC 13.3.0]
CUDA available: True
GPU 0,1: NVIDIA H100 80GB HBM3
GPU 0,1 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
CUDA Driver Version: 535.161.08
PyTorch: 2.4.0+cu121
sglang: 0.3.2
flashinfer: 0.1.6+cu121torch2.4
triton: 3.0.0
transformers: 4.44.2
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.5
fastapi: 0.114.1
hf_transfer: 0.1.8
huggingface_hub: 0.24.7
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.9.1
uvicorn: 0.30.6
uvloop: 0.20.0
zmq: 26.2.0
vllm: 0.5.5
multipart: 0.0.9
openai: 1.45.0
anthropic: 0.34.2
NVIDIA Topology: 
        GPU0    GPU1    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5    NIC6    NIC7    NIC8    NIC9    NIC10   NIC11   CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV18    NODE    PIX     NODE    NODE    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     0-47,96-143     0               N/A
GPU1    NV18     X      NODE    NODE    PIX     NODE    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     0-47,96-143     0               N/A
NIC0    NODE    NODE     X      NODE    NODE    NODE    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS
NIC1    PIX     NODE    NODE     X      NODE    NODE    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS
NIC2    NODE    PIX     NODE    NODE     X      NODE    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS
NIC3    NODE    NODE    NODE    NODE    NODE     X      PIX     PXB     PXB     NODE    SYS     SYS     SYS     SYS
NIC4    NODE    NODE    NODE    NODE    NODE    PIX      X      PXB     PXB     NODE    SYS     SYS     SYS     SYS
NIC5    NODE    NODE    NODE    NODE    NODE    PXB     PXB      X      PIX     NODE    SYS     SYS     SYS     SYS
NIC6    NODE    NODE    NODE    NODE    NODE    PXB     PXB     PIX      X      NODE    SYS     SYS     SYS     SYS
NIC7    NODE    NODE    NODE    NODE    NODE    NODE    NODE    NODE    NODE     X      SYS     SYS     SYS     SYS
NIC8    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      NODE    NODE    NODE
NIC9    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     NODE     X      NODE    NODE
NIC10   SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE     X      NODE
NIC11   SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    NODE     X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3
  NIC4: mlx5_4
  NIC5: mlx5_5
  NIC6: mlx5_6
  NIC7: mlx5_7
  NIC8: mlx5_8
  NIC9: mlx5_9
  NIC10: mlx5_10
  NIC11: mlx5_11


ulimit soft: 65535
```

**Comment by merrymercy** [comment]
Can you try to disable kv cache quantization?  Drop `--kv-cache-dtype fp8_e5m2`

**Comment by billvsme** [comment]
I'm having the same problem with ``Meta-Llama-3.1-70B-Instruct`` and **fp8** quantization under high concurrency/RPS (without using ``--kv-cache-dtype fp8_e5m2``).   
  
When I add ``--chunked-prefill-size 2048``, there is no error.

**Comment by qeternity** [comment]
We have also just encountered this with a finetuned Qwen 2.5 7B w4a16 in a high rps json setting.

Disabling cuda graph fixed this for us.

**Comment by merrymercy** [comment]
@qeternity  Can you try `--disable-cuda-graph-padding` ? It has less performance degradation than `--disable-cuda-graph`

**Comment by Flynn-Zh** [comment]
I'm having the same problem with Qwen2.5-32B-Instruct-GPTQ-Int4，--quantization gptq

**Comment by Flynn-Zh** [comment]
> I'm having the same problem with Qwen2.5-32B-Instruct-GPTQ-Int4，--quantization gptq

try --quantization gptq_marlin，there is no error.

**Comment by zzh-www** [comment]
same error in Qwen2.5-7b-instruct with two a30

=============error message==================
**python -m sglang.bench_latency --model-path models/Qwen/Qwen2.5-7B-Instruct --batch 1 --input-len 512 --output-len 1 --trust-remote-code --disable-radix-cache --mem-fraction-static 0.7 --enable-torch-compile --tp 2**
[21:43:41 TP0] Init torch distributed begin.
[21:43:41 TP1] Init torch distributed begin.
[21:43:50 TP0] Load weight begin. avail mem=21.62 GB
[21:43:50 TP1] Load weight begin. avail mem=21.62 GB
[21:43:51 TP0] lm_eval is not installed, GPTQ may not be usable
[21:43:51 TP1] lm_eval is not installed, GPTQ may not be usable
Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:00<00:00,  1.76it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:01<00:00,  1.52it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:01<00:00,  1.55it/s]

[21:43:53 TP0] Load weight end. type=Qwen2ForCausalLM, dtype=torch.bfloat16, avail mem=14.42 GB
[21:43:53 TP1] Load weight end. type=Qwen2ForCausalLM, dtype=torch.bfloat16, avail mem=14.42 GB
[21:43:53 TP1] Memory pool end. avail mem=5.93 GB
[21:43:53 TP0] Memory pool end. avail mem=5.93 GB
[21:43:54 TP1] Capture cuda graph begin. This can take up to several minutes.
[21:43:54 TP0] Capture cuda graph begin. This can take up to several minutes.
INFO 10-23 21:48:26 custom_all_reduce.py:223] Registering 912 cuda graph addresses
INFO 10-23 21:48:26 custom_all_reduce.py:223] Registering 912 cuda graph addresses
max_total_num_tokens=296895
Warmup ...
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
Prefill. latency: 0.91232 s, throughput:    561.21 token/s
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
Decode.  latency: 0.01266 s, throughput:     78.98 token/s
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
Decode.  latency: 0.01184 s, throughput:     84.44 token/s
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
Decode.  latency: 0.01149 s, throughput:     87.05 token/s
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
Decode.  latency: 0.01157 s, throughput:     86.41 token/s
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
Decode.  latency: 0.01135 s, throughput:     88.11 token/s
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
Decode.  median latency: 0.01149 s, median throughput:     87.05 token/s
Total. latency:  0.994 s, throughput:    523.16 token/s
Benchmark ...
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
Prefill. latency: 0.05028 s, throughput:  10183.34 token/s
Total. latency:  0.050 s, throughput:  10203.23 token/s
Exception ignored in: <function CustomAllreduce.__del__ at 0x7ffbbe2fca60>
Traceback (most recent call last):
  File "/root/miniconda3/envs/sgl/lib/python3.9/site-packages/vllm/distributed/device_communicators/custom_all_reduce.py", line 274, in __del__
  File "/root/miniconda3/envs/sgl/lib/python3.9/site-packages/vllm/distributed/device_communicators/custom_all_reduce.py", line 270, in close
AttributeError: 'NoneType' object has no attribute 'dispose'
Exception ignored in: <function ShmRingBuffer.__del__ at 0x7ffbbe28bc10>
Traceback (most recent call last):
  File "/root/miniconda3/envs/sgl/lib/python3.9/site-packages/vllm/distributed/device_communicators/shm_broadcast.py", line 132, in __del__
  File "/root/miniconda3/envs/sgl/lib/python3.9/multiprocessing/shared_memory.py", line 240, in unlink
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function CustomAllreduce.__del__ at 0x7f52b1919b80>
Traceback (most recent call last):
  File "/root/miniconda3/envs/sgl/lib/python3.9/site-packages/vllm/distributed/device_communicators/custom_all_reduce.py", line 274, in __del__
  File "/root/miniconda3/envs/sgl/lib/python3.9/site-packages/vllm/distributed/device_communicators/custom_all_reduce.py", line 270, in close
AttributeError: 'NoneType' object has no attribute 'dispose'
[rank0]:[W1023 21:48:30.143561942 CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
[rank1]:[W1023 21:48:30.202617070 CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors

============Environment=================
**python3 -m sglang.check_env**
Python: 3.9.20 (main, Oct  3 2024, 07:27:41) [GCC 11.2.0]
CUDA available: True
GPU 0,1: NVIDIA A30
GPU 0,1 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda-12.1
NVCC: Cuda compilation tools, release 12.1, V12.1.105
CUDA Driver Version: 470.129.06
PyTorch: 2.4.0+cu121
sglang: 0.3.3.post1
flashinfer: 0.1.6+cu121torch2.4
triton: 3.0.0
transformers: 4.45.2
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.10
fastapi: 0.115.2
hf_transfer: 0.1.8
huggingface_hub: 0.25.2
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.9.2
uvicorn: 0.31.1
uvloop: 0.21.0
zmq: 26.2.0
vllm: 0.5.5
multipart: 0.0.12
openai: 1.51.2
tiktoken: 0.8.0
anthropic: 0.36.0
NVIDIA Topology: 
        GPU0    GPU1    mlx5_0  mlx5_1  mlx5_2  mlx5_3  CPU Affinity    NUMA Affinity
GPU0     X      NODE    SYS     SYS     SYS     SYS     18-31,80,82-95  1
GPU1    NODE     X      SYS     SYS     SYS     SYS     18-31,80,82-95  1
mlx5_0  SYS     SYS      X      PIX     SYS     SYS
mlx5_1  SYS     SYS     PIX      X      SYS     SYS
mlx5_2  SYS     SYS     SYS     SYS      X      PIX
mlx5_3  SYS     SYS     SYS     SYS     PIX      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 1024768

**Comment by merrymercy** [comment]
@zzh-www Your error is different and it has been addressed in #1764

**Comment by merrymercy** [comment]
@tongyx361 I am able to reproduce this. Adding `--disable-cuda-graph-padding` can temporarily fix the problem. I am working on a better solution.

**Comment by merrymercy** [comment]
This should be fixed by https://github.com/sgl-project/sglang/pull/1779
