### ISSUE TITLE
initialise model with max_model_len

### ISSUE THREAD

**Issue by nivibilla** [sgl-project/sglang#159]
Similar to how vllm has the 'max_model_length' when starting the server. Can we have this here too?

This would help when trying to host models on smaller gpus. For example with vllm Mistral 7b with 32k context doesn't fit on a single 24GB GPU. Whereas with 8k context it does.

**Comment by merrymercy** [comment]
Contributions are welcome.

**Comment by psych0v0yager** [comment]
Second on this issue. I do not have much experience with AI backends, roughly what would need to be modified in order to get this change to work?
