### ISSUE TITLE
[Bug] Can't distinguish whether the EOS token or the stop token caused the generation to stop

### ISSUE THREAD

**Issue by g-drozdov** [sgl-project/sglang#1609]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

It is impossible to distinguish whether the EOS token or the stop token caused the generation to stop. It can be useful to know specifically which of these caused the sequence generation to stop, especially since by default the stop tokens and eos are omitted from the output text.

Before [this pull request](https://github.com/sgl-project/sglang/pull/1407), it was possible to do this by extracting the token_id. Now, it's no longer possible.

As a solution, the stop_reason parameter can be used, as implemented in vllm:
https://github.com/vllm-project/vllm/blob/8c746226c956f7c8a4672689fee91c7d22befed6/vllm/entrypoints/openai/protocol.py#L734
or also returning the matched field in the response under finish_reason.

### Reproduction

```
python3 -m sglang.launch_server --model-path Qwen/Qwen2.5-Coder-7B --host 0.0.0.0 --port 30000 --trust-remote-code --context-length 8192 --tp 1 --dp 2
```
Doesn't matter which model is used

### Environment

Python: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
CUDA available: True
GPU 0,1: NVIDIA A100-SXM4-40GB
GPU 0,1 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
CUDA Driver Version: 550.90.07
PyTorch: 2.4.0+cu121
sglang: 0.3.2
flashinfer: 0.1.6+cu121torch2.4
triton: 3.0.0
transformers: 4.44.0
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.3
fastapi: 0.112.0
hf_transfer: 0.1.8
huggingface_hub: 0.24.5
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.8.2
uvicorn: 0.30.5
uvloop: 0.19.0
zmq: 26.1.0
vllm: 0.5.5
multipart: 0.0.9
openai: 1.40.3
anthropic: 0.34.1
NVIDIA Topology: 
        GPU0    GPU1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV12    0-23    0               N/A
GPU1    NV12     X      0-23    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

Hypervisor vendor: KVM
ulimit soft: 1024

**Comment by merrymercy** [comment]
This is a good feature to have. Can you send a fix for us?

**Comment by g-drozdov** [comment]
Sure, will do it in the next few days
