### ISSUE TITLE
[Bug] Message to guide using <=0.3.2 for data parallel is not shown when --dp is set

### ISSUE THREAD

**Issue by seungduk-yanolja** [sgl-project/sglang#1617]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

More details:
https://github.com/sgl-project/sglang/commit/048685430d4c46fd5bc150675b0df49fc6a681d3#r147740163

### Reproduction

setting `--dp 2`

### Environment

sglang 0.3.3

**Comment by merrymercy** [comment]
Thanks for reporting. It has been added back https://github.com/sgl-project/sglang/pull/1635. It will be included in the next release https://github.com/sgl-project/sglang/pull/1636 (v0.3.3.post1).
