### ISSUE TITLE
[Question]Where is data parallelism

### ISSUE THREAD

**Issue by josephydu** [sgl-project/sglang#1618]
I found that in the latest version (v0.3.2), I can't find the code about data parallelism. Have you removed it? What are the considerations based on this?

**Comment by merrymercy** [comment]
Thanks for reporting. It has been added back https://github.com/sgl-project/sglang/pull/1635. It will be included in the next release https://github.com/sgl-project/sglang/pull/1636 (v0.3.3.post1).
