### ISSUE TITLE
[Feature] Add date to logging

### ISSUE THREAD

**Issue by zeng-zc** [sgl-project/sglang#1623]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

I've deployed sglang in my production environment, but the log is like this:
```
[23:14:09 TP0] Decode batch. #running-req: 1, #token: 998, token usage: 0.00,……
```
So I don't know the exact date of this log message.

The fix is very easy, just change this line: https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/utils.py#L575
as this:
```
datefmt='%Y-%m-%d %H:%M:%S',
```

**Comment by merrymercy** [comment]
Can you send us a patch to fix this?

**Comment by zeng-zc** [comment]
> Can you send us a patch to fix this?

[sglang_log.PATCH](https://github.com/user-attachments/files/17374472/sglang_log.PATCH)

hi, the attachment patch has been tested as this:
```
git apply sglang_log.PATCH
```
Run it on the `main` branch.
Please review it, thank you.

**Comment by zeng-zc** [comment]
> > Can you send us a patch to fix this?
> 
> [sglang_log.PATCH](https://github.com/user-attachments/files/17374472/sglang_log.PATCH)
> 
> hi, the attachment patch has been tested as this:
> 
> ```
> git apply sglang_log.PATCH
> ```
> 
> Run it on the `main` branch. Please review it, thank you.

The following is the logging effects before and after the patch:
![Screenshot from 2024-10-15 15-58-53](https://github.com/user-attachments/assets/36976849-b6d5-4caf-b332-1ef50c32c856)
![Screenshot from 2024-10-15 15-54-22](https://github.com/user-attachments/assets/a40a1b6d-9fe8-4e92-8ec2-36d2a6ea00e7)

**Comment by ByronHsu** [comment]
Hi can you open a PR?
