### ISSUE TITLE
[Feature] Support for GPT-2

### ISSUE THREAD

**Issue by hariharan98m** [sgl-project/sglang#1643]
### Checklist

- [x] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 2. Please use English, otherwise it will be closed.

### Motivation

I believe there is still a vast majority of our community working with GPT-2 or similar small language models for niche datasets. It would be great if these finetuned GPT-2 models can be deployed through sglang.

**Comment by Abhrajitdas02** [comment]
hi can I work on this?

**Comment by zhyncs** [comment]
> hi can I work on this?

Sure, go ahead. It's not difficult. ref https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/gpt2.py

**Comment by merrymercy** [comment]
https://github.com/sgl-project/sglang/blob/main/docs/en/model_support.md

**Comment by DanielC12321** [comment]
Hi! Is anyone currently working on this issue? If not, I’d love to take it on. I’m new to contributing, so any pointers on where to start or key files to review would be really helpful.

**Comment by merrymercy** [comment]
implemented by https://github.com/sgl-project/sglang/pull/1833
