### ISSUE TITLE
[Feature] Multi-instance deployment

### ISSUE THREAD

**Issue by vkc1vk** [sgl-project/sglang#1649]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

I want to host multiple instances of Llama 3 8B across multiple A100 GPUs (with load balancing handled). Is there a way to do this currently?

### Related resources

n/a

**Comment by merrymercy** [comment]
We support a simple data parallelism. Could you try this?
https://github.com/sgl-project/sglang/blob/69aa937aa528f0066ab5226bb428cbdf37dec048/README.md?plain=1#L217-L220

**Comment by vkc1vk** [comment]
Thanks! Is this option available with `sgl.Engine` as well (Batched offline mode)

**Comment by ByronHsu** [comment]
Yes you can use `sgl.Engine` with the current simple DP. We are working on the full-fledged version.

**Comment by tsaoyu** [comment]
What about multi-node? I am currently using Ray with vLLM and it was not that straightforward to do so (Hand-crafted PlacementGroup)

**Comment by merrymercy** [comment]
@tsaoyu try this? https://github.com/sgl-project/sglang/pull/2114

**Comment by ByronHsu** [comment]
We will merge #2114 very soon and release an experimental router which can be downloaded using `pip`
