### ISSUE TITLE
[Feature] sanic Custom Server example  support openai  stream  api ?

### ISSUE THREAD

**Issue by lys791227** [sgl-project/sglang#1655]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

Custom Server example  surport openai  stream  api ?

### Related resources

Custom Server example  surport openai  stream  api ?

**Comment by ByronHsu** [comment]
Sanic custom server example is just to demonstrate how to wrap a server on top of engine. It is not a user facing feature. Can you elaborate the ask? thanks!

**Comment by lys791227** [comment]
> Sanic custom server example is just to demonstrate how to wrap a server on top of engine. It is not a user facing feature. Can you elaborate the ask? thanks!
I was originally thinking whether the custom server example could support OpenAI API calls in sanic.

**Comment by ByronHsu** [comment]
We want to keep the example minimal, but feel free to implement the API schema for your use cases
