### ISSUE TITLE
[Feature] When will a version of S-Lora be available?

### ISSUE THREAD

**Issue by kunkunzhang123** [sgl-project/sglang#1668]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

When will a version of S-Lora be available?

**Comment by Ying1123** [comment]
Yes, you can track the progress here: https://github.com/sgl-project/sglang/pull/1307.
