### ISSUE TITLE
[Bug] IndexError: Inconsistent batch_size and len(image_input)

### ISSUE THREAD

**Issue by OBJECT907** [sgl-project/sglang#1692]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

```
.......site-packages/sglang/srt/models/llava.py", line 362, in forward
    for j, image_offset in enumerate(image_offsets[i]):
IndexError: list index out of range
```

The issue persists in version `0.3.3.post1`. During batch inference, `LlavaBaseForCausalLM` can encounter inconsistent `batch_size` and `len(image_input)` in the `forward_batch`. Although this error is not consistently triggered, it is more likely to occur when the requested batch size is larger than the maximum running batch size. The root cause remains unclear.

Additionally, I am uncertain why `self.image_data` will be duplicated by `num = self.batch_size + self.parallel_sample_num * self.batch_size` in `struct_io.GenerateReqInput`.

I need some help so maybe I could fix it together with this [#1579](https://github.com/sgl-project/sglang/pull/1579) 

### Reproduction

I run Llava-v1.6(NeXT)-34b with the following command:
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m sglang.launch_server --model-path llava-v1.6/llava-v1.6-34b --tokenizer-path llava-v1.6/llava-v1.6-34b-tokenizer --port 10001 --chat-template=chatml-llava --tp 4 --enable-p2p-check --mem-fraction-static 0.8
and send a single-image batch request with `batch_size=64`

### Environment

Python: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA GeForce RTX 4090
GPU 0,1,2,3,4,5,6,7 Compute Capability: 8.9
CUDA_HOME: /usr/local/cuda-12.1
NVCC: Cuda compilation tools, release 12.1, V12.1.105
CUDA Driver Version: 550.54.14
PyTorch: 2.4.0+cu121
sglang: 0.3.3.post1
flashinfer: 0.1.6+cu121torch2.4
triton: 3.0.0
transformers: 4.44.0
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.9.5
fastapi: 0.111.0
hf_transfer: 0.1.6
huggingface_hub: 0.23.4
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.8.2
uvicorn: 0.30.1
uvloop: 0.19.0
zmq: 26.0.3
vllm: 0.5.5
multipart: 0.0.9
openai: 1.50.2
anthropic: 0.31.0
NVIDIA Topology: 
	[4mGPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	CPU Affinity	NUMA Affinity	GPU NUMA ID[0m
GPU0	 X 	PIX	PIX	PIX	SYS	SYS	SYS	SYS	0-35,72-107	0		N/A
GPU1	PIX	 X 	PIX	PIX	SYS	SYS	SYS	SYS	0-35,72-107	0		N/A
GPU2	PIX	PIX	 X 	PIX	SYS	SYS	SYS	SYS	0-35,72-107	0		N/A
GPU3	PIX	PIX	PIX	 X 	SYS	SYS	SYS	SYS	0-35,72-107	0		N/A
GPU4	SYS	SYS	SYS	SYS	 X 	PIX	PIX	PIX	36-71,108-143	1		N/A
GPU5	SYS	SYS	SYS	SYS	PIX	 X 	PIX	PIX	36-71,108-143	1		N/A
GPU6	SYS	SYS	SYS	SYS	PIX	PIX	 X 	PIX	36-71,108-143	1		N/A
GPU7	SYS	SYS	SYS	SYS	PIX	PIX	PIX	 X 	36-71,108-143	1		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 1024

**Comment by merrymercy** [comment]
Thanks for reporting. I will look into this. In the meanwhile,
1. Can you help us find which commit introduces this problem?
2. Can you reproduce this bug with https://github.com/sgl-project/sglang/tree/main/benchmark/llava_bench?

**Comment by merrymercy** [comment]
Fixed by https://github.com/sgl-project/sglang/pull/1702
