### ISSUE TITLE
[Bug] AttributeError in `openai.Client` Embeddings API

### ISSUE THREAD

**Issue by tanzelin430** [sgl-project/sglang#1698]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

When attempting to serve a model using python -m sglang.launch_server --model-path --tp 4 and sending a request using the openai.Client API for embeddings, the following error occurs:

```
AttributeError: 'EmbeddingReqInput' object has no attribute 'image_data'
```

### Reproduction

Steps to Reproduce:
Serve the model with the following command:
```
python -m sglang.launch_server --model-path --tp 4
Send a request for embedding using the openai Python client with the following code:
```
Run following code
```
import openai

client = openai.Client(
    base_url="http://127.0.0.1:30000/v1", api_key="EMPTY")

response = client.embeddings.create(
    model="default",
    input="How are you today",
)
print(response)
```
Observe the error:
```
AttributeError: 'EmbeddingReqInput' object has no attribute 'image_data'
```
Expected Behavior:
```
The request should return an embedding for the given input text "How are you today."
```

Actual Behavior:
```
An AttributeError is raised: 'EmbeddingReqInput' object has no attribute 'image_data'.
```

### Environment

Environment Details:
Model serving command: python -m sglang.launch_server --model-path --tp 4
Python version: 3.12
openai library version: 1.51.2               
Operating System: 22.04.1-Ubuntu
Additional Information:
It seems the EmbeddingReqInput class is missing an attribute or is incorrectly set up for text-based inputs. This might be due to an incorrect assumption of input types. See https://github.com/sgl-project/sglang/blob/02f7f3e4889b4941425c4da1ca4a907ac4a5c9a0/python/sglang/srt/managers/tokenizer_manager.py#L189 
Suggested Fix:
Review the input handling for the `obj`

**Comment by merrymercy** [comment]
Can you try to add `--is-embedding` when you launch the server?

**Comment by merrymercy** [comment]
This PR improved the error message https://github.com/sgl-project/sglang/pull/1700

**Comment by tanzelin430** [comment]
> This PR improved the error message #1700

Thanks for quick fix！I am seeking a chance to be a member of developer of SGLang, next time you may leave such easy case for me as a beginning~ Thank you very much for your early and effective reply

**Comment by merrymercy** [comment]
@tanzelin430 Great. You can join our slack channel and our public dev meeting. https://github.com/sgl-project/sglang/blob/736f04025d2b01893cbf3ece20614991d0a94951/README.md?plain=1#L14-L15

You can also start with many good first issues https://github.com/sgl-project/sglang/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
