### ISSUE TITLE
Does frontend language support multi-image QA?

### ISSUE THREAD

**Issue by joeyy5588** [sgl-project/sglang#1708]
Dear SGLang team, 

Thanks for the amazing work!
I have a couple questions:
1. Does frontend language support multi-image QA? For example, if I run 
```@sgl.function
def image_qa(s, image_1, image_2, question, **kwargs):
    s += sgl.user(sgl.image(image_1) + sgl.image(image_2) + question)
    s += sgl.assistant(sgl.gen("answer", max_tokens=20))
```
I'll receive error 
```
assert len(s.images_) == 1, "Only support one image."
AssertionError: Only support one image.
```
2. What's the equivalent feature of `run_batch` when we use the openai-api style request like the code in this [line](https://github.com/sgl-project/sglang/blob/main/examples/runtime/llava_onevision/http_llava_onevision_test.py#L81)?
Do I simply use the for loop to send out all the request?

Thank you!

**Comment by merrymercy** [comment]
1. The frontend does not support that. Please contribute a PR to fix that if you can help.
2. You can create many python threads to do that.

**Comment by merrymercy** [comment]
You can also try OpenAI-compatible API for interleaved multi-image/video/text https://github.com/sgl-project/sglang/blob/b6cd903604a7439fcd082290ade83a02b164eca0/test/srt/test_vision_openai_server.py#L135

**Comment by joeyy5588** [comment]
Thanks for the response!
Closing this issue.
