### ISSUE TITLE
OpenAI compatible API and JSON schema enforcing 

### ISSUE THREAD

**Issue by remixer-dec** [sgl-project/sglang#171]
Hi! I just wanted to ask if it is possible to use OpenAI compatible API in sglang with local models and to force a certain json schema. IIRC original openai api only supports `{ "type": "json_object" }` which allows generating any json objects. If currently it is not possible, introducing something like `_schema` as optional property may be a solution until a similar functionality appears in the openai specification.

**Comment by comaniac** [comment]
I support this idea, but I would suggest directly add "regex" field to the extra parameter. OpenAI>1.0 supports arbitrary extra parameters. They are just ignored if you query gpt4.

**Comment by remixer-dec** [comment]
Thank you!
