### ISSUE TITLE
[Bug] Prefill OOM!

### ISSUE THREAD

**Issue by yichuan520030910320** [sgl-project/sglang#1739]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

Prefill OOM 

reported by @caoshiyi 

### Reproduction

```py
import requests

ids =  [37]* 13647
try1 = ids
try2 = [ids + [3], ids + [4], ids + [5]]

response = requests.post(
    "http://localhost:30000/generate",
    json={
        "input_ids" : try1,
        "sampling_params": {
            "temperature": 0,
            "max_new_tokens": 32,
        },
    },
)

response = requests.post(
    "http://localhost:30000/generate",
    json={
        "input_ids" : try2,
        "sampling_params": {
            "temperature": 0,
            "max_new_tokens": 32,
        },
    },
)
```

The server cmd is:
```
python -m sglang.launch_server --model-path meta-llama/Meta-Llama-3.1-8B-Instruct --port 30000 --max-total-tokens 13649 --schedule-cons 0 --chunked-prefill -1
```

**Comment by ByronHsu** [comment]
I can help take a look. What is the GPU and its mem size?

**Comment by ByronHsu** [comment]
Could you provide the environment + GPU spec too?

**Comment by merrymercy** [comment]
@ByronHsu This should be reproducible on any hardware because the command explicitly set the relevant arguments.
