### ISSUE TITLE
[Bug] Issue in latest sglang docker image 

### ISSUE THREAD

**Issue by shubhamgajbhiye1994** [sgl-project/sglang#1744]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

after download of sglang latest image , it gives error "EOF"  

### Reproduction

docker pull lmsysorg/sglang:latest  , EOF issue

### Environment

linux with python3.10

**Comment by merrymercy** [comment]
It works for me. Could you pull again and check your network and file system condition?
