### ISSUE TITLE
Why StreamingResponse 3s Delay to Abort Requests?

### ISSUE THREAD

**Issue by matthew-hippocratic** [sgl-project/sglang#1755]
In one of my use cases I sometimes make streaming LLM requests that I cancel shortly after. I would like to reduce unnecessary load from these requests running after cancellation.

In `create_abort_task` [here](https://github.com/sgl-project/sglang/blob/1f26e8b8e4c8b884e59036dccd87929b2af592f9/python/sglang/srt/managers/tokenizer_manager.py#L560), I see a 3s delay after StreamingResponses are completed or cancelled before the `tokenizer_manager` sends the abort request to the `scheduler`. Is there a reason for this delay?

**Comment by merrymercy** [comment]
There isn't a good reason for it. I set it to 3s to be safe and reduce the overhead of frequent checking. Feel free to file a PR if smaller values work better for you and do not introduce any performance overhead.

**Comment by matthew-hippocratic** [comment]
Sounds good, will do
