### ISSUE TITLE
[Feature] Multi options

### ISSUE THREAD

**Issue by QinghanLai** [sgl-project/sglang#1761]
### Checklist

- [ ] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 2. Please use English, otherwise it will be closed.

### Motivation

I want to use sgl.gen to select multiple options from the candidate selection, does it support it?

**Comment by ByronHsu** [comment]
Do you mean select like top K choices from the candidates?

**Comment by QinghanLai** [comment]
No!


my mean is given an option list,
eg: [A,B,C,D,E]
it can select multi option in llm decode,
such as [A,C,D] or [D,B] or [D,A,E] .....,
not using top-k selection




Qinghan Lai
Qilu University Of Technology(Shangdong Academy Of Sciences)
On 10/23/2024 10:07，Byron ***@***.***> wrote：

Do you mean select like top K choices from the candidates?

**Comment by QinghanLai** [comment]
This multi option is very commonly used in our development tasks.


The top k method will destroy the original output logic of the LLM and reduce the effect of generating text.


I'd love to see sglang support that, as he's really helpful for tasks and can compensate for the limitations of single choice.


Thanks!


Qinghan Lai
Qilu University Of Technology(Shangdong Academy Of Sciences)
On 10/23/2024 10:21，Qinghan ***@***.***> wrote：
No!


my mean is given an option list,
eg: [A,B,C,D,E]
it can select multi option in llm decode,
such as [A,C,D] or [D,B] or [D,A,E] .....,
not using top-k selection




Qinghan Lai
Qilu University Of Technology(Shangdong Academy Of Sciences)
On 10/23/2024 10:07，Byron ***@***.***> wrote：

Do you mean select like top K choices from the candidates?

**Comment by merrymercy** [comment]
please give an sglang program example that you want and the expected input and output
