### ISSUE TITLE
Port fused MoE Kernels

### ISSUE THREAD

**Issue by merrymercy** [sgl-project/sglang#179]
There is a recent PR (https://github.com/vllm-project/vllm/pull/2542) in vLLM that introduced some fused kernels to accelerate mixtral MoE models.

We can bring it to our [code](https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/models/mixtral.py) as well.

**Comment by zhyncs** [comment]
It has been done with https://github.com/sgl-project/sglang/pull/460
