### ISSUE TITLE
[Bug] Parameter Update API update_weights Fails in DP=2, TP=1 Configuration

### ISSUE THREAD

**Issue by rbao2018** [sgl-project/sglang#1814]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug
I am using sglang==0.3.2, and want to call update_weights in my RLHF training.

However, the model parameter update API call ```update_weights``` fails when deploying model with Data Parallel (DP=2) and Tensor Parallel (TP=1)

When trying to deploy the model with data parallelism set to 2 (DP=2) and tensor parallelism set to 1 (TP=1), the API call for updating model parameters fails. This occurs during the parameter update process in the distributed training setup.

The requests call in the sglang http server show:
```
[14:26:31] Invalid object: UpdateWeightReqInput(model_path='/mnt/data/huggingface/models/Meta-Llama-3-8B', load_format='auto')
```

### Reproduction

```bash
python -m sglang.launch_server --model-path /mnt/data/huggingface/models/Meta-Llama-3-8B --host 0.0.0.0 --tp 1 --dp 2 --port 11226 --mem-fraction-static 0.9
```

```python
import requests
import json

model_path = "/mnt/data/huggingface/models/Meta-Llama-3-8B"
def run_update_weights(model_path):
    base_url = "http://0.0.0.0:11226"
    response = requests.post(
        base_url + "/update_weights",
        json={"model_path": model_path},
    )
    ret = response.json()
    print(json.dumps(response.json()))
    return ret
run_update_weights(model_path)
```

### Environment

WARNING 10-27 14:30:05 cuda.py:22] You are using a deprecated `pynvml` package. Please install `nvidia-ml-py` instead. See https://pypi.org/project/pynvml for more information.
Python: 3.10.14 (main, May 29 2024, 23:47:02) [GCC 11.4.0]
CUDA available: True
GPU 0,1: NVIDIA A100-SXM4-80GB
GPU 0,1 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
CUDA Driver Version: 535.54.03
PyTorch: 2.4.0+cu121
flashinfer: 0.1.6+cu121torch2.4
triton: 3.0.0
transformers: 4.44.2
requests: 2.32.3
tqdm: 4.66.4
numpy: 1.26.3
aiohttp: 3.9.5
fastapi: 0.111.1
hf_transfer: 0.1.8
huggingface_hub: 0.24.2
interegular: 0.3.3
packaging: 24.0
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.9.1
uvicorn: 0.30.3
uvloop: 0.19.0
zmq: 26.0.3
vllm: 0.5.5
multipart: 0.0.9
openai: 1.47.0
anthropic: 0.34.2
NVIDIA Topology: 
        GPU0    GPU1    NIC0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV2     PHB     0-31            N/A             N/A
GPU1    NV2      X      PHB     0-31            N/A             N/A
NIC0    PHB     PHB      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0

ulimit soft: 102400

**Comment by rbao2018** [comment]
Thank you for such a quick pull request to my issue. 

> https://github.com/sgl-project/sglang/pull/1825

I really appreciate the work of the sglang team! Thanks a lot!

**Comment by ByronHsu** [comment]
NP. Can you test the PR?

**Comment by rbao2018** [comment]
No problem, I will test it with versions 0.3.2 and 0.3.4.

**Comment by ByronHsu** [comment]
Oh I mean pull my PR and build Sglang locally

**Comment by rbao2018** [comment]
> Oh I mean pull my PR and build Sglang locally

Oh, got it! 
I will test both scenarios: a locally build and also try running version 0.3.2 with only the tokenizer manager file modified.

**Comment by rbao2018** [comment]
> Oh I mean pull my PR and build Sglang locally

I test this PR with local install. it works:

[2024-10-28 15:38:50 DP1 TP0] Update weights begin. avail mem=5.08 GB
[2024-10-28 15:38:50 DP0 TP0] Update weights begin. avail mem=5.08 GB
Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:02,  1.31it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:02,  1.30it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.23it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.21it/s]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:02<00:00,  1.24it/s]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:02<00:00,  1.21it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.74it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.52it/s]

[2024-10-28 15:38:53 DP1 TP0] Update weights end.
[2024-10-28 15:38:53 DP1 TP0] Cache flushed successfully!
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.69it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.49it/s]

[2024-10-28 15:38:53 DP0 TP0] Update weights end.
[2024-10-28 15:38:53 DP0 TP0] Cache flushed successfully!
[2024-10-28 15:38:53] INFO:     127.0.0.1:47156 - "POST /update_weights HTTP/1.1" 200 OK

However, I modify the code in 0.3.2 and it still raise the same error response.

**Comment by ByronHsu** [comment]
Glad to hear it works on the main. For 0.3.2, it might have other issues since it is quite behind. cc @merrymercy

**Comment by ByronHsu** [comment]
The PR is merged and will be included in the next release. To unblock yourself now, you can local build sglang on main HEAD.
