### ISSUE TITLE
Questions Regarding sglang vs vllm and Memory Management

### ISSUE THREAD

**Issue by hahmad2008** [sgl-project/sglang#1828]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

Hi, I have a few questions regarding the sglang framework:

1. Relationship with vllm: Is sglang based on vllm? If so, what are the key differences between the two?

2. Multi-GPU Support: For multi-GPU setups, are you using Ray or another framework for managing tensors?

3. KV Profile Cache Differences: What are the differences between the KV profile cache in sglang and the one in vllm? Specifically, I’m curious about GPU memory utilization. 

- For example, on VLLM with a 24GB GPU, I can set memory utilization to 0.9 or 0.95 for the llama3-8b model (which is 15.6GB) when loading it into memory.

- However, I encountered an "out of memory" error when I set the memory fraction in sglang to 0.9. I had to lower it to 0.7 or 0.8 to avoid this issue. Can you clarify why this happens?

Thank you!

### Reproduction

-

### Environment

sglang: 0.3.3.post1

**Comment by zeng-zc** [comment]
> ### Checklist
> * [x]  1. I have searched related issues but cannot get the expected help.
> * [ ]  2. The bug has not been fixed in the latest version.
> * [ ]  3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
> * [ ]  4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
> * [ ]  5. Please use English, otherwise it will be closed.
> 
> ### Describe the bug
> Hi, I have a few questions regarding the sglang framework:
> 
> 1. Relationship with vllm: Is sglang based on vllm? If so, what are the key differences between the two?
> 2. Multi-GPU Support: For multi-GPU setups, are you using Ray or another framework for managing tensors?
> 3. KV Profile Cache Differences: What are the differences between the KV profile cache in sglang and the one in vllm? Specifically, I’m curious about GPU memory utilization.
> 
> * For example, on VLLM with a 24GB GPU, I can set memory utilization to 0.9 or 0.95 for the llama3-8b model (which is 15.6GB) when loading it into memory.
> * However, I encountered an "out of memory" error when I set the memory fraction in sglang to 0.9. I had to lower it to 0.7 or 0.8 to avoid this issue. Can you clarify why this happens?
> 
> Thank you!
> 
> ### Reproduction
> 
> ### Environment
> sglang: 0.3.3.post1

1. sglang is an alternative of vllm, but sglang has more prettier benchmark results, that is, higher throughput, lower latency and lower TTFT. Now there is some dependency on vllm about loading models, rope and other things. But in the near future, the dependency will be removed.
2. Sglang uses its own implementations for multi-node, it's not Ray, it's very convinient, there're samples in the `readme.md`.
3. Sglang uses radix tree for kv cache, you can refer to the paper: https://arxiv.org/abs/2312.07104

I think radix-tree cache is more effective than vllm's prefix-cache implementation. By the way, I'm not an expert.

**Comment by yileld** [comment]
Vllm only uses GPU memory utilization that you set, it means if you set 0.95, it will only use 95% GPU memory.
Sglang set 0.95, it will use 0.95 memory for static state such as model, kv cache, etc. When inference, it will also use rest 0.05 of memory, so if you set GPU memory utilization too big, it may not enough for inference computing.

**Comment by hahmad2008** [comment]
Thanks @yileld  and @zeng-zc for your responses. 
@yileld I don't know why i can't load a model like gemma2-9b on a GPU of 24G with SGLANG even if I tried all possible values of `mem_fraction_static`, it always get out of memory if I increase it or a negative `self.max_total_num_tokens` if i decease it.

However, I can load the same model on the 24G GPU with vllm when I use the GPU memory utilization : 0.95
