### ISSUE TITLE
Supporting api vendors of Mixtral

### ISSUE THREAD

**Issue by amazingvince** [sgl-project/sglang#183]
Could this work with an OpenAI compatable vendor API like together or firework? I would like to use mixtral but would rather not host it. I tried but the openai implementation is hardcoded for openai model.

**Comment by merrymercy** [comment]
I added some examples for you.
Please try the latest main branch with these examples
https://github.com/sgl-project/sglang/blob/main/examples/quick_start/together_example_chat.py
https://github.com/sgl-project/sglang/blob/main/examples/quick_start/together_example_complete.py
