### ISSUE TITLE
[Bug] stop_str of qwen2-vl template should be a tuple not a str

### ISSUE THREAD

**Issue by wellhowtosay** [sgl-project/sglang#1832]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

https://github.com/sgl-project/sglang/blob/5e6c32657e384b023faf03d79e06f7727feedb7c/python/sglang/lang/chat_template.py#L147

### Reproduction

-

### Environment

-

**Comment by ByronHsu** [comment]
Issue was fixed by #1834
