### ISSUE TITLE
[Bug] sglang template import issue

### ISSUE THREAD

**Issue by multimodalpragmatic** [sgl-project/sglang#1841]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

I run sglang with the following standard zephyr.jinja template: 

```
{% if messages[0]['role'] == 'system' %}
    {% set offset = 1 %}
{% else %}
    {% set offset = 0 %}
{% endif %}

{% for message in messages %}
    {% if (message['role'] == 'user') != (loop.index0 % 2 == offset) %}
        {{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}
    {% endif %}

    {{ '<|' + message['role'] + '|>\n' + message['content'] | trim + eos_token + '\n' }}
{% endfor %}

{% if add_generation_prompt %}
    {{ '<|assistant|>\n' }}
{% endif %}

```
But I got an error of: 
"RuntimeError: Chat template configs/chat_templates/zephyr.jinja is not a built-in template name or a valid chat template file path." 

I tried to write a template in .json file myself, since your sglang reads the template in: 
```
Conversation(
  name=template["name"],
  system_template=template["system"] + "\n{system_message}",
  system_message=template.get("system_message", ""),
  roles=(template["user"], template["assistant"]),
  sep_style=sep_style,
  sep=template.get("sep", "\n"),
  stop_str=template["stop_str"],
)
```

But I still got the above error. Do you have any template example file in .json format or jinja format? 

### Reproduction

Code example: 
   ```
 sglang_command = f"python -m sglang.launch_server --model-path {model_path}" + \
                      f" --port {port}"

    if chat_template is not None:
        sglang_command += f" --chat-template {chat_template}"
    elif tokenizer_path is not None:
        sglang_command += f" --tokenizer-path {tokenizer_path}"

    print("running sglang server with command: ", sglang_command)

    with open(result_save_path, 'w', encoding='utf-8') as log_file:
        pass
    log_file = open(result_save_path, 'a', encoding='utf-8')

    ## somehow this will hang if we don't output things to a FILE
    sglang_process = subprocess.Popen(
        sglang_command,
        shell=True,
        start_new_session=True,
        stdin=log_file,
        stdout=log_file,
        stderr=log_file,
        text=True
    )

```
Model: fine tuned "alignment-handbook/zephyr-7b-sft-full". 

### Environment

sglang state-of-the-art version

**Comment by merrymercy** [comment]
SGLang supports jinja and json formats.
Jinja: the same as HF tokenizer
JSON: https://github.com/sgl-project/sglang/blob/main/docs/references/custom_chat_template.md
code: https://github.com/sgl-project/sglang/blob/16eb33ffe2afc9c043e4f80f18e15ea57b984944/python/sglang/srt/openai_api/adapter.py#L124-L160

For your error, please check the file path.
