### ISSUE TITLE
[Feature] Create a benchmark script for offline inference

### ISSUE THREAD

**Issue by ByronHsu** [sgl-project/sglang#1865]
### Motivation

Users report perf degradation of engine.generate. Add something similar to https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_throughput.py

**Comment by vrdn-23** [comment]
It would also be great to get an automated set of benchmark results with latest version of vLLM as well so users can know how much the benchmarks change with different versions.

**Comment by zolinthecow** [comment]
@ByronHsu i'll pick this one up

**Comment by merrymercy** [comment]
solved by https://github.com/sgl-project/sglang/pull/1968
