### ISSUE TITLE
Question: Does sglang support prefix cache for multimodal models?

### ISSUE THREAD

**Issue by htrekker** [sgl-project/sglang#1870]
I noticed that the cache hit rate remains 0.0% no matter how much turns the conversation has. Does sglang support prefix cache for multimodal models?

**Comment by merrymercy** [comment]
It is supported for llava and llama 3.2. What model are you using? Can you share a reproducible example?

**Comment by merrymercy** [comment]
If you run this test case, you will find the cache hit rate is not 0.
https://github.com/sgl-project/sglang/blob/c3eac1b010b3da3086457e40af555690da0787a6/test/srt/test_vision_openai_server.py#L51

**Comment by ARSblithe212** [comment]
> It is supported for llava and llama 3.2. What model are you using? Can you share a reproducible example?

is qwen2-vl supported?

**Comment by tusg** [comment]
yeah, it's the same issue for me as well-:
![image](https://github.com/user-attachments/assets/79d6edb5-2509-4fd7-b5a9-9c142375526c)

adding the keys specified in this link -: [sglang/test/srt/test_vision_openai_server.py] is also not working for qwen2-vl model.
