### ISSUE TITLE
QWen VL Follow-up Fixes

### ISSUE THREAD

**Issue by merrymercy** [sgl-project/sglang#1897]
There are still some remaining items to finish the QWen VL support.

1. There might be a small bug in the image process. The tests in CI will trigger this error sometimes. https://github.com/sgl-project/sglang/actions/runs/11598427301/job/32294256076#step:4:778
2. This `mrope_position_delta` is very model specific and seems only related to multi modal. https://github.com/sgl-project/sglang/blob/efbc116a0f81e7c3f09f45b0720152aa5b91dc0d/python/sglang/srt/managers/schedule_batch.py#L255 We should move this out of `class Req`. We can pay some costs to recompute it every time if that is possible. Otherwise, we can move that to `Class ImageInputs`.

**Comment by yizhang2077** [comment]
ci error seems caused by connection to github.com timed out when fetching images or videos, and it is not sglang code problem.
