### ISSUE TITLE
Randomly getting output full of repetitive newlines on LLaVA invocations

### ISSUE THREAD

**Issue by isidentical** [sgl-project/sglang#191]
Not sure if anyone else had hit into this but when using `liuhaotian/llava-v1.5-13b` with `llava-hf/llava-1.5-13b-hf` tokenizer, randomly I get outputs full of only newlines. The frequency of this happening increases when the temperature is close to 0 but also happens at 1 as well.

**Comment by jacob-hansen** [comment]
I've also hit this bug. My issue was that I had the generation outside of the assistant prompt. I was trying to be able to prompt the generation process (e.g. I give it what the model should start with). 

WRONG:
def image_qa(s, image_path, question, system_prompt="", initial_assistant = ""):
    s += sgl.user(system_prompt + sgl.image(image_path) + question)
    s += sgl.assistant(initial_assistant)
    s += sgl.gen("answer")

CORRECT: 
def image_qa(s, image_path, question, system_prompt="", initial_assistant = ""):
    s += sgl.user(system_prompt + sgl.image(image_path) + question)
    s += sgl.assistant(initial_assistant + sgl.gen("answer"))

This fixed the issues.
