### ISSUE TITLE
[Feature] sglang.rocm support flashinfer?

### ISSUE THREAD

**Issue by linqingxu** [sgl-project/sglang#1911]
### Checklist

- [ ] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 2. Please use English, otherwise it will be closed.

### Motivation

amdgpu上运行sglang，是否需要安装flashinfer，还是和之前一样用triton?

**Comment by ByronHsu** [comment]
flashinfer only has cuda impl for now. For AMD, you can fallback to triton attention backend by setting `--attention-backend triton`. cc @merrymercy @HaiShaw have you tested triton attn backend on AMD?

**Comment by HaiShaw** [comment]
@ByronHsu @linqingxu For AMD, please use `--attention-backend triton --sampling-backend pytorch`
FlashInfer isn't available yet.
Please use `Dockerfile.rocm` to build image first, I will update document for `Installation`
