### ISSUE TITLE
[Feature] add model  LlavaOnevisionForConditionalGeneration

### ISSUE THREAD

**Issue by zhangucan** [sgl-project/sglang#1918]
### Checklist

- [x] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 2. Please use English, otherwise it will be closed.

### Motivation

llava-hf/llava-onevision-qwen2-7b-ov-chat-hf is not supported, resulting in an error. Expect to support

**Comment by merrymercy** [comment]
Please use the official models from the model authors. These models are supported [lmms-lab/llava-onevision-qwen2-72b-ov-chat](https://huggingface.co/lmms-lab/llava-onevision-qwen2-72b-ov-chat) 
https://github.com/sgl-project/sglang/blob/c3eac1b010b3da3086457e40af555690da0787a6/test/srt/test_vision_openai_server.py#L31
