### ISSUE TITLE
[Bug] Incompatible with outlines>=0.1.0

### ISSUE THREAD

**Issue by dzimmerman-nci** [sgl-project/sglang#1930]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

When launching a server, I get a no module found error for outlines.fsm.regex. After checking the releases of the outlines library, I found that this module was removed in the 0.1.0 release. 

### Reproduction

python -m sglang.launch_server --model-path Meta-Llama-3-8B-Instruct \
--port 30000 --host 0.0.0.0

Error: No module named 'outlines.fsm.regex'. Please install a new version of outlines by `pip install "outlines>=0.0.44"`

### Environment

Python: 3.11.2 (main, Mar 16 2023, 23:15:26) [GCC 11.3.0]
CUDA available: True
GPU 0: NVIDIA A100 80GB PCIe
GPU 0 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
CUDA Driver Version: 525.105.17
PyTorch: 2.1.2+cu118
sglang: 0.3.5
flashinfer: 0.1.1+cu118torch2.1
triton: 2.1.0
transformers: 4.38.2
requests: 2.31.0
tqdm: 4.66.2
numpy: 1.26.4
aiohttp: 3.10.2
fastapi: 0.110.0
hf_transfer: Module Not Found
huggingface_hub: 0.20.3
interegular: 0.3.3
packaging: 23.2
PIL: 10.2.0
psutil: 5.9.8
pydantic: 2.6.3
uvicorn: 0.28.0
uvloop: 0.19.0
zmq: 24.0.1
vllm: Module Not Found
multipart: Module Not Found
openai: 1.52.1
tiktoken: 0.8.0
anthropic: Module Not Found
NVIDIA Topology: 
        GPU0    CPU Affinity    NUMA Affinity
GPU0     X      0-63            N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

Hypervisor vendor: VMware
ulimit soft: 1048576

**Comment by merrymercy** [comment]
Please install a new version of outlines by pip install "outlines>=0.0.44"

**Comment by dzimmerman-nci** [comment]
i've already tried your "solution". that's what caused the issue in the first place. outlines=0.1.0 is included in the requirement "outlines>=0.0.44" and it does not work... I'm reporting that it does not work with outlines>=0.1.0

**Comment by merrymercy** [comment]
Sorry that I misread the version number.  Now we specify the version < 0.1.0 here https://github.com/sgl-project/sglang/pull/2036.

In the meanwhile, contributions are welcome to make it compatible with the new version. The core team will also take a look.

**Comment by dzimmerman-nci** [comment]
thanks @merrymercy!

**Comment by merrymercy** [comment]
move to https://github.com/sgl-project/sglang/issues/2276
