### ISSUE TITLE
[Feature] Add LoRA Support for Chat Completion in SGLang

### ISSUE THREAD

**Issue by mssongit** [sgl-project/sglang#1936]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

Currently, SGLang supports LoRA via the generate API, but it is not accessible when using the OpenAI Chat Completion API. Adding LoRA support to the OpenAI Chat Completion API would enable users to leverage LoRA functionality consistently across both APIs, providing a more seamless experience.
https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/openai_api/protocol.py#L257

### Related resources

vLLM LoRA Support for v1 Chat Completion: https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/openai/serving_completion.py#L38

vLLM currently provides LoRA support for v1 Chat Completion, demonstrating how LoRA can be integrated to improve training efficiency in language models. Examining vLLM's implementation may provide insights or code references that could assist in adding this feature to SGLang.

**Comment by RonanKMcGovern** [comment]
Yes, having this as well as the ability to dynamically load or unload loras would be excellent.

**Comment by ccchow** [comment]
Have this PR for chat completion 

https://github.com/sgl-project/sglang/pull/2438
