### ISSUE TITLE
[Feature] How to serve GGUF model?

### ISSUE THREAD

**Issue by hahmad2008** [sgl-project/sglang#1937]
How to serve a gguf model? VLLM provided a tutorial for that like this:  https://docs.vllm.ai/en/latest/getting_started/examples/gguf_inference.html 

But how to inference with sglang?  Could you please provide a command to do that?
example for this model: `TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF`

### Related resources

https://docs.vllm.ai/en/latest/getting_started/examples/gguf_inference.html

**Comment by zhyncs** [comment]
duplicate https://github.com/sgl-project/sglang/issues/1950

**Comment by merrymercy** [comment]
Currently not supported, and it shouldn't be difficult to add support. You can refer to the implementation of vLLM. Are you interested in lading a PR?

**Comment by merrymercy** [comment]
moved to #1616
