### ISSUE TITLE
cannot import build_regex_from_object

### ISSUE THREAD

**Issue by amirarsalan90** [sgl-project/sglang#194]
Seems `build_regex_from_object` is changed in the new outline version

`pip install "sglang[all]"`

`~/semantic-detection$ python -m sglang.launch_server --model-path mistralai/Mistral-7B-Instruct-v0.2 --port 30000 --mem-fraction-static 0.8`

`Traceback (most recent call last):
  File “/opt/conda/envs/semantic/lib/python3.10/runpy.py”, line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File “/opt/conda/envs/semantic/lib/python3.10/runpy.py”, line 86, in _run_code
    exec(code, run_globals)
  File “/home/ubuntu/semantic-detection/sglang/python/sglang/launch_server.py”, line 3, in <module>
    from sglang.srt.server import ServerArgs, launch_server
  File “/home/ubuntu/semantic-detection/sglang/python/sglang/srt/server.py”, line 25, in <module>
    from sglang.srt.constrained import disable_cache
  File “/home/ubuntu/semantic-detection/sglang/python/sglang/srt/constrained/__init__.py”, line 4, in <module>
    from outlines.fsm.json_schema import build_regex_from_object
ImportError: cannot import name ‘build_regex_from_object’ from ‘outlines.fsm.json_schema’ (/opt/conda/envs/semantic/lib/python3.10/site-packages/outlines/fsm/json_schema.py)`

**Comment by amirarsalan90** [comment]
Changing to "outlines==0.0.30" fixed the issue:
https://github.com/sgl-project/sglang/blob/63ba630bbbb2d55787ac54ac0a01cbde993afc20/python/pyproject.toml#L23

**Comment by comaniac** [comment]
outlines updated a new version 9 hours ago that breaks SGLang. We should either pin the version to 0.0.30 or upgrade the SGLang usage. @hnyls2002
