### ISSUE TITLE
how to load a gguf model in sglang?

### ISSUE THREAD

**Issue by lovingliferwj** [sgl-project/sglang#1950]

**Comment by zhyncs** [comment]
Currently not supported, and it shouldn't be difficult to add support. You can refer to the implementation of vLLM. Are you interested in lading a PR

**Comment by merrymercy** [comment]
moved to https://github.com/sgl-project/sglang/issues/1950

**Comment by cyberluke** [comment]
@merrymercy Ni Hao, Mercy show no mercy and link #1950 to #1937 to #1616 ...but it is good worth the time reading, especially me eat 辛辣的 burger
