### ISSUE TITLE
[Feature] Is GritLM-7B supported?

### ISSUE THREAD

**Issue by vkc1vk** [sgl-project/sglang#1978]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

Does embedding support extend to all embedding models that rely on Mistral 7B, including GritLM-7B?

### Related resources

https://huggingface.co/GritLM/GritLM-7B
https://github.com/ContextualAI/gritlm

**Comment by zhyncs** [comment]
Welcome to contribute!

**Comment by merrymercy** [comment]
It is MistralForCausalLM, so it should be supported.
