### ISSUE TITLE
[Feature] Support Qwen2-VL based embedding model

### ISSUE THREAD

**Issue by VoVAllen** [sgl-project/sglang#2032]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

The multimodal embedding showed great potential for RAG pipeline. There're multiple approaches all based on Qwen-VL Conditional Generation models, like https://huggingface.co/marco/mcdse-2b-v1 and https://huggingface.co/blog/marco/announcing-mcdse-2b-v1.

**Comment by merrymercy** [comment]
solved by #2055
