### ISSUE TITLE
Will qwen-vl be supported in the future?

### ISSUE THREAD

**Issue by zhangqingwu** [sgl-project/sglang#206]
Will Qwen-VL-chat be supported in the future?

**Comment by zhyncs** [comment]
ref https://github.com/sgl-project/sglang/pull/244

**Comment by zhyncs** [comment]
It should directly support Qwen2 VL, but the priority is not high for now.

**Comment by zhyncs** [comment]
duplicate https://github.com/sgl-project/sglang/issues/1352 Close this for now. Thanks!
