### ISSUE TITLE
Have some advise to learn Openai's triton?

### ISSUE THREAD

**Issue by Arcmoon-Hu** [sgl-project/sglang#208]
I note this project use triton write kernel. It's cool, so can you share how learn triton ?

**Comment by DouHappy** [comment]
+1

**Comment by hnyls2002** [comment]
https://triton-lang.org/main/getting-started/tutorials/index.html

This is an official tutorial for beginners, and it's straightforward to learn.

**Comment by zhyncs** [comment]
ref 
https://github.com/FlagOpen/FlagGems
https://bilibili.com/video/BV11y3ne9Ec5 (Chinese)
