### ISSUE TITLE
[Feature] Is Yarn supported in sglang?

### ISSUE THREAD

**Issue by klykq111** [sgl-project/sglang#2108]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

I recently discovered that the qwen2.5 model can achieve a context length of [128k](https://github.com/QwenLM/Qwen2.5-Coder?tab=readme-ov-file#2-processing-long-texts) when run in Yarn. Is Yarn supported in sglang?

**Comment by merrymercy** [comment]
yes

**Comment by klykq111** [comment]
Thank you for confirming. I found that while sglang does support the 128k context length for the qwen2.5 model, it requires explicitly setting the `--context-length` parameter to 128k. Otherwise, it defaults to 32k and does not automatically read and apply the context length from the Yarn configuration. I hope this information is helpful to other users as well!

**Comment by zhanghx0905** [comment]
Hello, this is the approach I have taken:
1. Set the environment variable SGLANG_ALLOW_OVERWRITE_LONGER_CONTEXT_LEN=1
2. Set the launch parameter --context-length to 128k
3. Add the following to the model's config.json:
   ```json
   "rope_scaling": {
     "factor": 4.0,
     "original_max_position_embeddings": 32768,
     "rope_type": "yarn"
   }
   ```

Would this enable the yarn 128k context for the qwen2.5-instruct series of models? @merrymercy

**Comment by pseudotensor** [comment]
AFAIK the rope setting above uses static yarn, not dynamic yarn, so will ruin shorter context cases.
