### ISSUE TITLE
[Feature] Inference example code for Qwen2-VL

### ISSUE THREAD

**Issue by YuanLiuuuuuu** [sgl-project/sglang#2113]
### Checklist

- [ ] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 2. Please use English, otherwise it will be closed.

### Motivation

Thank you for this great project. I search the related document, but I cannot find the example code to run Qwen2-VL locally. Could you please give me the example code?

**Comment by lukashelff** [comment]
here is an example https://github.com/sgl-project/sglang/blob/main/test/srt/test_vision_openai_server.py
