### ISSUE TITLE
[Bug] Unable to load GPTQ Mixtral 8x7 v0.1 with SGLang

### ISSUE THREAD

**Issue by DhruvaBansal00** [sgl-project/sglang#2117]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

Attempting to start the SGLang offline server with GPTQ Mixtral 8X7 leads to the following stacktrace:

```
[2024-11-22 00:08:26 TP0] Traceback (most recent call last):
  File "/sglang/python/sglang/srt/managers/scheduler.py", line 1391, in run_scheduler_process
    scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank)
  File "/sglang/python/sglang/srt/managers/scheduler.py", line 183, in __init__
    self.tp_worker = TpWorkerClass(
  File "/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 55, in __init__
    self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port)
  File "/sglang/python/sglang/srt/managers/tp_worker.py", line 56, in __init__
    self.model_runner = ModelRunner(
  File "/sglang/python/sglang/srt/model_executor/model_runner.py", line 153, in __init__
    self.load_model()
  File "/sglang/python/sglang/srt/model_executor/model_runner.py", line 299, in load_model
    self.model = self.setup_model()
  File "/sglang/python/sglang/srt/model_executor/model_runner.py", line 241, in setup_model
    return get_model(vllm_config=vllm_config)
  File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/model_loader/__init__.py", line 12, in get_model
    return loader.load_model(vllm_config=vllm_config)
  File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 334, in load_model
    model.load_weights(self._get_all_weights(model_config, model))
  File "/sglang/python/sglang/srt/models/mixtral.py", line 357, in load_weights
    param = params_dict[name]
KeyError: 'model.layers.0.block_sparse_moe.experts.w13_bias'
```

### Reproduction

```
import sglang as sgl
engine = sgl.Engine(
      model_path="TheBloke/Mixtral-8x7B-v0.1-GPTQ",
      tp_size=1,
      max_loras_per_batch=32,
      mem_fraction_static=0.88,
      quantization="gptq_marlin",
      disable_cuda_graph=True,
  )
```

### Environment

Python: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
CUDA available: True
GPU 0: NVIDIA A100-SXM4-80GB
GPU 0 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
CUDA Driver Version: 550.90.07
PyTorch: 2.5.1+cu124
sglang: 0.3.5.post2
flashinfer: 0.1.6+cu121torch2.3
triton: 3.1.0
transformers: 4.46.3
requests: 2.32.2
tqdm: 4.66.4
numpy: 1.26.4
aiohttp: 3.8.3
fastapi: 0.115.5
hf_transfer: 0.1.8
huggingface_hub: 0.26.2
interegular: 0.3.3
packaging: 23.2
PIL: 10.3.0
psutil: 5.9.0
pydantic: 2.10.0
uvicorn: 0.32.1
uvloop: 0.21.0
zmq: 26.2.0
vllm: 0.6.4.post1
multipart: 0.0.9
openai: 1.55.0
anthropic: 0.39.0
NVIDIA Topology: 
	GPU0	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 				N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 65536

**Comment by merrymercy** [comment]
will be fixed by https://github.com/sgl-project/sglang/pull/2300
