### ISSUE TITLE
[Bug] llava use image hash as token，leading to cache bug

### ISSUE THREAD

**Issue by zwc163** [sgl-project/sglang#2151]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

In the llava model, the hash value of an image is used as a token to facilitate prefix cache matching. However, hash collisions may occur, leading to bugs.

### Reproduction

python -m sglang.launch_server --port 28056 --schedule-conservativeness 0.1 --dtype float16 --context-length 4000 --tokenizer-mode slow

### Environment

sglang 0.3.4

**Comment by merrymercy** [comment]
can you provide a reproducible example?

**Comment by merrymercy** [comment]
Thanks for reporting this. This is fixed by https://github.com/sgl-project/sglang/pull/2256
