### ISSUE TITLE
[Feature] How to accelerate constrained decoding when regex needs to change with input?

### ISSUE THREAD

**Issue by GrittyChen** [sgl-project/sglang#2168]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

In some practical application scenarios, the regex needs to change with the input, and the speed of constrained decoding using Compressed FSM will be significantly slower than that of unconstrained decoding due to each time you need to compile. How do we support the constrained decoding acceleration requirement in unfixed regex scenarios? thanks~

**Comment by merrymercy** [comment]
It seems unrelated to the constrained FSM optimization. You can submit multiple requests if the regex can change in the middle.
