### ISSUE TITLE
Using sglang without server

### ISSUE THREAD

**Issue by tweeter0830** [sgl-project/sglang#218]
I'd like to make batched requests using your inference engine without needing to start up a server. Is that possible? For me, the server is a lot of extra complexity to manage, when all I really want to do is something like:

```python
def run_inferences(images_and_prompts: list[tuple], batch_size) -> list[str]
   ...
```

**Comment by hnyls2002** [comment]
@tweeter0830 

I'm sorry. If you are using a local model to do inference, you'll need to start a server or a runtime. If you mean that you don't want to start up the server in a separate shell, you can use our `Runtime`.

https://github.com/sgl-project/sglang/blob/8d0a7fae3b89eecae8cd2a755a673462c23ab31f/examples/quick_start/srt_example_chat.py#L54

This enables you not to start a server backend but to use an exclusive runtime in this program.
