### ISSUE TITLE
[Quantization Support Request]: Exllamav2

### ISSUE THREAD

**Issue by meditans** [sgl-project/sglang#22]
Exllamav2 is an excellent quantization method that would allow to use big models in consumer (~24Gb GPUs) thanks to fractional quantization methods. Would this be in the cards?

**Comment by meditans** [comment]
@merrymercy could you give me a heads-up on how much work would this entail? Is it just a matter of updating the [model runner module](https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/managers/router/model_runner.py)?

**Comment by merrymercy** [comment]
@meditans It should be easy. You can see existing quantization support 
- https://github.com/sgl-project/sglang/blob/08df63a6f8b9d27ae80cf705ab9496632c8a18c2/python/sglang/srt/managers/router/model_runner.py#L303-L325
- Probably, you need to implement a `linear_method` for Exllamav2. This can take some effort.
