### ISSUE TITLE
[Feature] 2:4 sparsity support 

### ISSUE THREAD

**Issue by arunpatala** [sgl-project/sglang#2200]
### Checklist

- [ ] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 2. Please use English, otherwise it will be closed.

### Motivation

Introduction of llama 8B sparse models with 2:4 sparsity has shown improvments in both latency and throughput. 
Combined with w4a16 quantization, it takes advantage of both quantization and sparsity. This mode is currently supported in VLLM.
Would like to know if 2:4 sparsity (and/or) quantization is supported in SGLang. 
I would love to contribute if necessary.

### Related resources

https://neuralmagic.com/blog/24-sparse-llama-smaller-models-for-efficient-gpu-inference/

**Comment by merrymercy** [comment]
sglang resues or imports many quantization code from vllm, so it should already be supported!

**Comment by yiakwy-xpu-ml-framework-team** [comment]
hi @merrymercy @arunpatala the current support calls functions from vllm and the path is already borken. I have fixed it in  https://github.com/sgl-project/sglang/pull/8708.
