### ISSUE TITLE
FileNotFoundError: 'agent_calls.jsonl'

### ISSUE THREAD

**Issue by DouHappy** [sgl-project/sglang#221]
When I ran the /benchmark/generative_agents/bench_sglang.py it shows that:
![image](https://github.com/sgl-project/sglang/assets/88470508/8d550b74-613e-46d6-810e-842978217ab2)
I read your code and found that agent_calls.jsonl is the dataset for benchmark. But I  didn't  found it anywhere. Did I ignore some illustrate? 
If not is there any link to download this dataset? Or maybe a tutorial to show me how to make a dataset for generative_agents benchmark. 
Thank you.

**Comment by hnyls2002** [comment]
@DouHappy Sorry to cause such confusion. We have uploaded the download link.
