### ISSUE TITLE
为啥这里是异步拷贝，然后后面直接使用了？没有显示同步？

### ISSUE THREAD

**Issue by MichoChan** [sgl-project/sglang#2211]
https://github.com/sgl-project/sglang/blob/0b46b951ae088dd22fe980acc7d855947ce2537f/python/sglang/srt/managers/schedule_batch.py#L982

 new_indices = torch.tensor(keep_indices, dtype=torch.int32).to(
          self.device, non_blocking=True
   )
 self.req_pool_indices = self.req_pool_indices[new_indices]

直接使用new_indices？

**Comment by VoVAllen** [comment]
在同一个CUDA Stream上操作是串行的，non blocking只是说不需要等这个异步操作做完

**Comment by MichoChan** [comment]
> 在同一个CUDA Stream上操作是串行的，non blocking只是说不需要等这个异步操作做完

self.req_pool_indices[new_indices] 就是这个操作也对应一个stream的操作是吗？我以为这是普通的index操作？

**Comment by VoVAllen** [comment]
你只要不显式创建新的stream，都会在CUDA default stream上执行
