### ISSUE TITLE
[Feature] ROCm in WSL environment is supported

### ISSUE THREAD

**Issue by githust66** [sgl-project/sglang#2213]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

Since ROCm under WSL cannot support rocm-smi, it is necessary to determine whether the operating system is WSL when obtaining the memory of the graphics card, so as to use rocminfo to adapt to WSL. Here's a demo of my simple rewrite (The operating system is not judged here, and the case of multiple cards is not taken into account) , which allows you to use SgLang on WSL normally. I hope the official can perfectly adapt to WSL.
![image](https://github.com/user-attachments/assets/a6c01d41-657f-4320-83d9-0ad263fd1f4e)
![image](https://github.com/user-attachments/assets/b6e7d781-f2c9-48e6-bf21-64934bfac42d)

**Comment by HaiShaw** [comment]
@merrymercy @githust66 
Fix in https://github.com/sgl-project/sglang/pull/2310

**Comment by HaiShaw** [comment]
@githust66 Once you verified, we can close this issue.
Thanks again for your helpful report!

**Comment by githust66** [comment]
> @githust66 Once you verified, we can close this issue. Thanks again for your helpful report!

HI, why do you use gfx94 as the keyword to search, for example, my graphics card is gfx1100 and I can't find it
![image](https://github.com/user-attachments/assets/fab90c95-5aee-46b4-8df3-2951d2d8b785)
![image](https://github.com/user-attachments/assets/d2301933-68df-4665-9014-c1107735b63e)

**Comment by githust66** [comment]
> > @githust66 Once you verified, we can close this issue. Thanks again for your helpful report!
> 
> HI, why do you use gfx94 as the keyword to search, for example, my graphics card is gfx1100 and I can't find it ![image](https://private-user-images.githubusercontent.com/53259654/391470701-fab90c95-5aee-46b4-8df3-2951d2d8b785.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzE1NzQsIm5iZiI6MTczMzEzMTI3NCwicGF0aCI6Ii81MzI1OTY1NC8zOTE0NzA3MDEtZmFiOTBjOTUtNWFlZS00NmI0LThkZjMtMjk1MWQyZDhiNzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA5MjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MGQ4ZTc1ZTE0ZmQ2YjI3NWNlZmQ4NzAwNWExNGQ1ZmM1YzJlMDZhODc4NjRjNTk0ODFkMjBjZWNlYWJlYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._yxAYJLgvS3HVYmJ5o0XQ3-zQh_tIGoiwfcWPZpMo3M) ![image](https://private-user-images.githubusercontent.com/53259654/391472536-d2301933-68df-4665-9014-c1107735b63e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzE1NzQsIm5iZiI6MTczMzEzMTI3NCwicGF0aCI6Ii81MzI1OTY1NC8zOTE0NzI1MzYtZDIzMDE5MzMtNjhkZi00NjY1LTkwMTQtYzExMDc3MzViNjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA5MjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyM2ZjOTg1ZjdkYTU3N2M2NDEyOWFhY2M3MjNmNTUyMmJiOGE1NDkzZGQwMWIwN2MyNGJhMDlkMzc3MWViYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fdc8ARaff5PZcYnnUceil_XsQ22TvKHXiM1POklunJs)

It seems like it's possible to just use gfx as a keyword

**Comment by HaiShaw** [comment]
@githust66 
Addressed in https://github.com/sgl-project/sglang/pull/2319

Also opened https://github.com/sgl-project/sglang/issues/2320

**Comment by githust66** [comment]
> @githust66 Addressed in #2319
> 
> Also opened #2320

Ok thanks

**Comment by HaiShaw** [comment]
@githust66 we can use #2320 to track remaining issues to enablement of other AMD GPUs (gfx1100, etc.)
