### ISSUE TITLE
[Feature] Support outlines >= 0.1

### ISSUE THREAD

**Issue by merrymercy** [sgl-project/sglang#2276]
Currently, sglang only supports `outlines>=0.0.44,<0.1.0`.
https://github.com/sgl-project/sglang/blob/7d5d1d3d2915d386d20890d5bda466834fc220be/python/pyproject.toml#L21

The new outlines >= 0.1.0 is faster, but it changes some APIs so sglang does not support it. We would like to change our [outlines] backend to make it support both old versions and new version.

## Steps
1. Try outlines >= 0.1.0 and fix all incompatibilities in https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/constrained/outlines_backend.py
2. You do not need to make it work with jump-forward decoding. Only make it work with normal decoding is good enough
3. Bonus: make it work with jump forward decoding.

**Comment by gobraves** [comment]
@merrymercy Hi, I’ve completed this issue, this is [my commit](https://github.com/gobraves/sglang/commit/67157c7c7deb02ae2de20172a03ec76264c3a3e9). But I noticed a potential problem. vLLM also uses the outlines library, with the version constraint outlines >= 0.0.43, < 0.1. If we add a constraint of outlines >= 0.1, when installing via pip install "sglang[all]", the actual version of outlines will still be below 0.1. However, if installed using uv, it will result in a version conflict error for outlines.

I think it would be good to submit this PR to complete the issue after #2245  is finished.

**Comment by merrymercy** [comment]
Hi @gobraves, it is great to know that you fixed it! Can you still submit a pr and make the code work with both the old version and the new version?

While a simple `pip install` will still install the old outlines version, advanced users can try other install methods (e.g., `pip --no-deps`) and customize their outlines versions. It would be great if our code could support both the old and the new versions.

We can update the code first and update `pyproject.toml` later.

**Comment by gobraves** [comment]
@merrymercy Hi, I have updated the code and submitted a PR.

**Comment by merrymercy** [comment]
@gobraves It is merged. Thanks!
