### ISSUE TITLE
64% faster awq

### ISSUE THREAD

**Issue by nivibilla** [sgl-project/sglang#229]
https://github.com/casper-hansen/AutoAWQ/pull/365

**Comment by zhyncs** [comment]
ref
AWQ SOTA https://github.com/InternLM/lmdeploy/pull/202

**Comment by zhyncs** [comment]
Currently, AWQ Marlin already has decent performance. We just need to wait for the accuracy issue to be resolved in the new release. This issue will now be closed, and it can be reopened if there are any further discussions. Thanks.
