### ISSUE TITLE
KV cache pool leak detected when  turn on flashinfer

### ISSUE THREAD

**Issue by nbbull** [sgl-project/sglang#236]
"KV cache pool leak detected" when  turn on flashinfer.
it's ok if turn off flashinfer.

deploy@ip-172-31-66-22:~$ python3 -m sglang.launch_server --model-path ./models/llava-v1.5-7b --tokenizer-path ./models/llava-1.5-7b-hf/ --port 8080 --host 0.0.0.0 --model-mode flashinfer
WARNING: Port 8080 is not available. Use 10000 instead.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Rank 0: load weight begin.
Loading mlp_gelu projector (mlp2x_gelu)...
/usr/local/lib/python3.8/dist-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Rank 0: load weight end.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Rank 0: max_total_num_token=13103, max_prefill_num_token=4096, context_len=4096, model_mode=['flashinfer']
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO:     Started server process [22071]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:10000 (Press CTRL+C to quit)
INFO:     127.0.0.1:37298 - "GET /get_model_info HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 0. #new_token: 9. #remaining_req: 0. #running_req: 0. tree_cache_hit_rate: 0.00%.
Exception in ModelRpcClient:
Traceback (most recent call last):
  File "/home/deploy/.local/lib/python3.8/site-packages/sglang/srt/managers/router/model_rpc.py", line 176, in exposed_step
    self.forward_step()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/deploy/.local/lib/python3.8/site-packages/sglang/srt/managers/router/model_rpc.py", line 191, in forward_step
    self.forward_fill_batch(new_batch)
  File "/home/deploy/.local/lib/python3.8/site-packages/sglang/srt/managers/router/model_rpc.py", line 404, in forward_fill_batch
    ) = self.model_runner.forward(
  File "/home/deploy/.local/lib/python3.8/site-packages/sglang/srt/managers/router/model_runner.py", line 478, in forward
    return self.forward_extend_multi_modal(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/deploy/.local/lib/python3.8/site-packages/sglang/srt/managers/router/model_runner.py", line 444, in forward_extend_multi_modal
    input_metadata = InputMetadata.create(
  File "/home/deploy/.local/lib/python3.8/site-packages/sglang/srt/managers/router/model_runner.py", line 229, in create
    ret.init_flashinfer_args(tp_size)
  File "/home/deploy/.local/lib/python3.8/site-packages/sglang/srt/managers/router/model_runner.py", line 129, in init_flashinfer_args
    self.prefill_wrapper.begin_forward(
TypeError: begin_forward() missing 1 required positional argument: 'head_dim'

/home/deploy/.local/lib/python3.8/site-packages/sglang/srt/managers/router/model_rpc.py:218: UserWarning: Warning: available_size=13094, max_total_num_token=13103
KV cache pool leak detected!
  warnings.warn(
HTTPConnectionPool(host='0.0.0.0', port=10000): Read timed out. (read timeout=60)

**Comment by Qubitium** [comment]
@nbbull  Is this still happening on latest sglang master + flashinfer latest? Both projects are moving at such as speed that there are lots of bugs fixed since two weeks ago.

**Comment by nbbull** [comment]
After reinstalling flashinfer, I ran it again. The problem still remains, and my version is as follows:

pip list|grep flashinfer
flashinfer                0.0.3+cu121torch2.1 /home/deploy/.local/lib/python3.8/site-packages

**Comment by smallstepman** [comment]
experiencing same issue 

@nbbull - are you on cuda 12.1? I got the same error but was on 12.2, trying to change the version now

**Comment by nbbull** [comment]
@smallstepman 
deploy@ip-172-31-73-243:~$ python3 -c "import torch; print(torch.__version__)"
2.1.2+cu121

**Comment by smallstepman** [comment]
@nbbull hmm i thought CUDA must be installed on system, but I can be completely wrong? What CUDA version you get from nvidia-smi? 

Also, maybe your cards are nvlinked too?

**Comment by for-just-we** [comment]
still have the issue, my sglang version is 0.1.14. cuda version is 12.2, install pytorch-2.1.2 and flashinfer-0.0.3-torch121

**Comment by for-just-we** [comment]
It seems this issue is fixed in [latest version](https://github.com/sgl-project/sglang/tree/14522e6a26e7dfb6e27c0b79f211f11d190259fe), where install with pytorch-2.1.2, and 0.0.4+cu121torch2.1. My cuda is 12.2.
