### ISSUE TITLE
[Bug] sglang isn't compatible with latest vLLM

### ISSUE THREAD

**Issue by hliuca** [sgl-project/sglang#2367]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

The upstream vLLM has changed its APIs, which are not compatible with the API called inside sglang. Do you have plan to adopt newer version vLLM? Thanks.

### Reproduction

Look at the API, https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/model_loader/loader.py#L100

### Environment

Using newer version vLLM.

**Comment by zhyncs** [comment]
```
python3 -m sglang.check_env
```
Please paste the env info
