### ISSUE TITLE
sgl.function can't use the specified chat template

### ISSUE THREAD

**Issue by TideDra** [sgl-project/sglang#239]
I launch a finetuned Mixtral model which uses the `chatml` template:
```
python -m sglang.launch_server --model-path Nous-Hermes-2-Mixtral-8x7B-DPO --tp 4 --chat-template chatml
```
But the sgl.function seems not to apply this template:
```python
@function
def test(s,question):
    s += user(question)
    s += assistant(gen("answer"))

s = test.run(question="Is 1+1 = 2?")
print(s.text())
```
which prints:
```
USER:Is 1+1 = 2?
ASSISTANT: Yes, in basic arithmetic, 1 + 1 is equal to
```
Using a wrong template absolutely harms model's performance.

**Comment by ArrichM** [comment]
The chat template specified via the  --chat-template option is only applied to the OpenAI compatible server, as described in the parameter help text. 
If you want to use a certain chat template when using the the /generate endpoint, you can just set it as the chat_template for your endpoint:

```python
import sglang as sgl
from sglang.lang.chat_template import get_chat_template

endpoint = sgl.RuntimeEndpoint(
    base_url="http://localhost:8000",
)
endpoint.chat_template = get_chat_template("chatml")

@sgl.function
def test(s, question):
    s += sgl.user(question)
    s += sgl.assistant(sgl.gen("answer"))

s = test.run(question="Is 1+1 = 2?", backend=endpoint)
print(s.text())
```

Which prints:

```
<|im_start|>user
Is 1+1 = 2?
<|im_end|>
<|im_start|>assistant
Yes, 1+1 is equal to 2 in mathematics. In
<|im_end|>

```

**Comment by TideDra** [comment]
> The chat template specified via the --chat-template option is only applied to the OpenAI compatible server, as described in the parameter help text. If you want to use a certain chat template when using the the /generate endpoint, you can just set it as the chat_template for your endpoint:
> 
> ```python
> import sglang as sgl
> from sglang.lang.chat_template import get_chat_template
> 
> endpoint = sgl.RuntimeEndpoint(
>     base_url="http://localhost:8000",
> )
> endpoint.chat_template = get_chat_template("chatml")
> 
> @sgl.function
> def test(s, question):
>     s += sgl.user(question)
>     s += sgl.assistant(sgl.gen("answer"))
> 
> s = test.run(question="Is 1+1 = 2?", backend=endpoint)
> print(s.text())
> ```
> 
> Which prints:
> 
> ```
> <|im_start|>user
> Is 1+1 = 2?
> <|im_end|>
> <|im_start|>assistant
> Yes, 1+1 is equal to 2 in mathematics. In
> <|im_end|>
> ```

Thanks for your help!
