### ISSUE TITLE
Best practices for deploying different models on different GPUs for offline generation

### ISSUE THREAD

**Issue by mantle2048** [sgl-project/sglang#2428]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

I would like to evaluate the performance of various small models (≤7B) on the same benchmark in parallel. 

To achieve this, I plan to deploy a different small model on each GPU and perform offline inference.

Is it currently possible to support such functionality?

My current plan is to explicitly set `CUDA_VISIBLE_DEVICES` in the command line and run multiple offline inference evaluations simultaneously. 

Is there a better implementation for this?

**Comment by ByronHsu** [comment]
`CUDA_VISIBLE_DEVICES` works. The alternative is to use `--base-gpu-id` for arguments https://github.com/sgl-project/sglang/blob/8586b72da0fe8a9d32a76770eba4b83a893b5ddf/python/sglang/srt/server_args.py#L472.

E.g.

```bash
$ python -m sglang.launch_server --model-path meta-llama/Meta-Llama-3.1-8B-Instruct --base-gpu-id 0
$ python -m sglang.launch_server --model-path meta-llama/Meta-Llama-3.1-8B-Instruct --base-gpu-id 1

```

**Comment by mantle2048** [comment]
Thanks a lot!
