### ISSUE TITLE
flashinfer no effect

### ISSUE THREAD

**Issue by lss15151161** [sgl-project/sglang#243]
model：llava-v1.5-7b
gpu：A10
I turn on flashinfer, but inference speed does not become fast, why?

flashinfer off:
<img width="316" alt="image" src="https://github.com/sgl-project/sglang/assets/34617721/eb0bc47d-9452-41f9-8f9d-ef3ae41ddf47">

flashinfer on:
![image](https://github.com/sgl-project/sglang/assets/34617721/574e241e-8ce3-4e6b-bc86-18df50211f6e)

**Comment by comaniac** [comment]
What's your prompt and decoding length in terms of tokens?
flashinfer speedups decoding, so it should be more obvious when you have a long decoding length.

**Comment by zhyncs** [comment]
Please try the latest version at https://pypi.org/project/sglang/
It is enabled by default.
