### ISSUE TITLE
[Feature] Enhanced support/structure for Multi-modal models

### ISSUE THREAD

**Issue by tp-nan** [sgl-project/sglang#2439]
### Checklist

- [ ] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 2. Please use English, otherwise it will be closed.

### Motivation

In vllm,  the framework can accept either image or image-embedding. See  [vllm [Feature] Add vision language model support. #3042](https://github.com/vllm-project/vllm/pull/3042) and [vllm-llava impl.](https://github.com/vllm-project/vllm/blob/2e33fe419186c65a18da6668972d61d7bbc31564/vllm/model_executor/models/llava.py#L479)
 
Embedding an image requires fixed predictable compute and is easy to batch and run   in a separate framework(for instance, tensorrt-based serving framework). See discussion in https://github.com/vllm-project/vllm/issues/307#issuecomment-1840443044

Ideally, it is necessary to maintain the infrastructure to overlap (image (gpu) preprocessing + inference) and (llm inference) within the same process (avoiding the need for nvidia MPS)

**Comment by nan2088** [comment]
Sorry, duplicated from https://github.com/sgl-project/sglang/issues/745
