### ISSUE TITLE
[Feature] support Llama3.3

### ISSUE THREAD

**Issue by win4r** [sgl-project/sglang#2443]
### Checklist

- [ ] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 2. Please use English, otherwise it will be closed.

### Motivation

support Llama3.3

### Related resources

support Llama3.3

**Comment by zhaochenyang20** [comment]
@win4r I think this is somehow strange. We do support Llama 3.3 70B instruct. Launch your engine directly plz. I will close this issue right now.

https://x.com/lmsysorg/status/1865097896179437907

**Comment by vtien** [comment]
Your documentation here just needs to be updated

https://docs.sglang.ai/references/supported_models.html

**Comment by zhaochenyang20** [comment]
okay
