### ISSUE TITLE
Benchmark of First Token Time

### ISSUE THREAD

**Issue by Guanlongwoo** [sgl-project/sglang#245]
Hi folks,

Where is the code for benchmark of first token time? I only see the average latency :) 

Thanks,

**Comment by xjw00654** [comment]
Hi,
2 methods could work.

1). Just add the `--stream-interval 1` to your command and the streaming output will be generated by a single token.
2). The streaming response has the field of the "created", you can use it to estimate the First Token latency. 

BTW, for method 2, the field type is INT. If you want to be more precise, change the script at 
```.YOUR LIB PATH./sglang/lib/python3.10/site-packages/sglang/srt/managers/openai_protocol.py``` 
Find the class `ChatCompletionStreamResponse` and change the code from: 
`created: int = Field(default_factory=lambda: int(time.time()))` 
to 
`created: str = Field(default_factory=lambda: str(time.time()))`

Hope this could help you.
