### ISSUE TITLE
[Feature] plan to support Block Schedule？ 

### ISSUE THREAD

**Issue by CSEEduanyu** [sgl-project/sglang#2568]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

Will the Block Schedule scheme in FlexLLMGen bring greater throughput? Will sglang consider supporting it?

**Comment by zhaochenyang20** [comment]
Thanks for pointing this out. I will raise the attention of our group.

**Comment by zhaochenyang20** [comment]
@CSEEduanyu Hey there. Flexgen is also a paper from our team member 😂 They suggest that you can check the appendix of Flexgen, which is more clear.

Regarding the scheduler, FlexGen is used to optimize IO when we need to offload the model. We already have these features for kernel optimization in the GPU memory layers of SGLang. So we won't specifically integrate this scheduler.

Thanks for pointing this out and merry Christmas.
