### ISSUE TITLE
JSON decoding using regex breaks if model outputs a "

### ISSUE THREAD

**Issue by aliencaocao** [sgl-project/sglang#258]
As topic suggests.

Using pydantic -> regex

It causes model to subsequently output blank as the logit mask goes on.

Is there any way to escape " produces by the model in a json field?

**Comment by hnyls2002** [comment]
@aliencaocao Can you provide more details or code to reproduce your problem?

**Comment by aliencaocao** [comment]
Its a common issue as gpt4 json mode also have this problem. If a json field is string, and model decides to include double quotes in this string, it prematurely ends the field as the regex will match it as an ended string, but model does not think so, so it keep trying to output something other than the next key of the json, which after logit masking by sglang, becomes all tokens that appear as blank in console. Just have any json as regex and instruct the model to output double quotes will trigger this.

**Comment by Qubitium** [comment]
I think this is an inherent issue of json string enforcement. There is no good way to tell when a model output ends a "string" since everything is a string. json string can contain any character even special format ones like \\n. The model is not trained to escape chars the way json expects so there is no way to tell apart " vs \\".

**Comment by DouHappy** [comment]
> Its a common issue as gpt4 json mode also have this problem. If a json field is string, and model decides to include double quotes in this string, it prematurely ends the field as the regex will match it as an ended string, but model does not think so, so it keep trying to output something other than the next key of the json, which after logit masking by sglang, becomes all tokens that appear as blank in console. Just have any json as regex and instruct the model to output double quotes will trigger this.
@aliencaocao 
We can use the following regular expression to match string values in JSON. I am confused why the " still exists when it is prohibited in this regular expression?  I also occured the same problem.

>  ("(?:[^"\\\x00-\x1f\x7f-\x9f]|\\.)*"|null)
<img width="1547" alt="430d02c0663de8fca7432d9a03a27d1" src="https://github.com/sgl-project/sglang/assets/88470508/adfd3e26-4df4-4d55-b177-d5963e05a7b5">

**Comment by DouHappy** [comment]
> Its a common issue as gpt4 json mode also have this problem. If a json field is string, and model decides to include double quotes in this string, it prematurely ends the field as the regex will match it as an ended string, but model does not think so, so it keep trying to output something other than the next key of the json, which after logit masking by sglang, becomes all tokens that appear as blank in console. Just have any json as regex and instruct the model to output double quotes will trigger this.

@aliencaocao Thank you for your explanation. Do you know where the relevant code is? I hope to have a deeper understanding of this issue in sglang.
