### ISSUE TITLE
[Feature] DeepSeek-V3 support 

### ISSUE THREAD

**Issue by fengyang95** [sgl-project/sglang#2585]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

https://huggingface.co/deepseek-ai/DeepSeek-V3-Base

An extremely excellent model, also very large, and technically challenging.

**Comment by githust66** [comment]
Take a look at the changelog of sglang 0.4.1, it's already supported

**Comment by zhyncs** [comment]
```
pip install "sglang[all]" --find-links https://flashinfer.ai/whl/cu121/torch2.4/flashinfer
python3 -m sglang.launch_server --model deepseek-ai/DeepSeek-V3-Base --enable-dp-attention --tp 8 --trust-remote-code
```
https://github.com/sgl-project/sglang/releases/tag/v0.4.1

> We're excited to announce SGLang v0.4.1, which now supports [DeepSeek V3](https://huggingface.co/deepseek-ai/DeepSeek-V3-Base) - currently the strongest open-source LLM, even surpassing GPT-4o.
>
> The SGLang and DeepSeek teams worked together to get DeepSeek V3 FP8 running on NVIDIA and AMD GPU from day one. We've also supported MLA optimization and DP attention before, making SGLang one of the best open-source LLM engines for running DeepSeek models.
>
> Special thanks to Meituan's Search & Recommend Platform Team @ispobock @HandH1998 and Baseten's Model Performance Team for their support, and DataCrunch for providing GPU resources.

**Comment by halexan** [comment]
Can I run DeepSeek-V3 on A100?

**Comment by zhyncs** [comment]
You can run DeepSeek V3 FP8 on H200(141*8)
