### ISSUE TITLE
How to serve deepseekV3  by sglangv0.4.1

### ISSUE THREAD

**Issue by DragonFive** [sgl-project/sglang#2587]
the deepseekV3 base is 685B, and sglang seems not support pipeline parallel, so I wander how to deploy on an A10080*8 machine?

**Comment by zhaochenyang20** [comment]
We support serving Deepseek V3 on 8 * H200 model. Please wait for them to be released. After deepseek model released, you can try out this:

```python
pip install "sglang[all]" --find-links https://flashinfer.ai/whl/cu121/torch2.4/flashinfer
python3 -m sglang.launch_server --model deepseek-ai/DeepSeek-V3-Base --enable-dp-attention --tp 8 --trust-remote-code
```

Use the newest SGLang.

Or use docker:

```python
docker run --gpus all \
    --shm-size 32g \
    -p 30000:30000 \
    -v ~/.cache/huggingface:/root/.cache/huggingface \
    --env “HF_TOKEN=<secret>” \
    --ipc=host \
    lmsysorg/sglang:latest \
    python3 -m sglang.launch_server --model deepseek-ai/DeepSeek-V3-Base --enable-dp-attention --tp 8 --trust-remote-code --port 30000
```

@DragonFive Have a try please.

**Comment by DragonFive** [comment]
Thank you for your timely response, it's sad that  I don't have  8 * H200, can I try pipeline parallel?

**Comment by zhaochenyang20** [comment]
We do not have pipeline parallelism. @zhyncs Do we have other choice.
