### ISSUE TITLE
OpenAI Chat Completion Endpoint

### ISSUE THREAD

**Issue by aliozts** [sgl-project/sglang#26]
First of all, thank you for such a great framework and study! Do you plan to support `chat/completions` endpoint as well for the models utilizing their `chat_template` for completion during backend serving?

**Comment by tranhoangnguyen03** [comment]
Does the current `/v1/completions` endpoint automatically applies the model's prompt format to the prompt sent to it? Or do I have to apply the formatting myself?

**Comment by comaniac** [comment]
You have to apply it by yourself ATM. Meanwhile, I might be working on the chat completion support in these days.
