### ISSUE TITLE
Precision of LLaVA model weights

### ISSUE THREAD

**Issue by zhang-jr** [sgl-project/sglang#262]
Why does the `vision_tower` of the `LLaVA` model hardcode the weight loading to [`torch.float16`](https://github.com/sgl-project/sglang/blob/b0b722ee8e90bfa2b379eadb1432e2f6852a6ad0/python/sglang/srt/models/llava.py#L251) instead of following the dtype specified in the actual model config file? Although the `clip` model does not update the weights during training, there are still several precision conversions in the middle (the original `openai/clip-vit-large-patch14-336` weight precision is `torch.float32`, The weights in `LLaVA` training are usually converted to `torch.bfloat16`, and here they are converted to `torch.float16`). Can the accuracy loss during these continuous conversions be ignored?

**Comment by Mr-Loevan** [comment]
yes, I also encountered this confusing question.
