### ISSUE TITLE
Max Length.

### ISSUE THREAD

**Issue by srush** [sgl-project/sglang#27]
Is there anyway to truncate text based on tokens? I really like that as a user I don't need to think about tokens. But to save memory I would like something like 
`s += left_trunc(inp, 500)` that keeps it reasonably sized.

**Comment by Ying1123** [comment]
After this line `s += left_trunc(inp, 500)`, do you mean `inp <= 500` or `s + inp <= 500`?
Either one should be easy to implement!

**Comment by srush** [comment]
I was thinking `inp` <=500 tokens.
