### ISSUE TITLE
AttributeError: 'str' object has no attribute 'eos_token_id'

### ISSUE THREAD

**Issue by Yanshang1991** [sgl-project/sglang#292]
INFO 03-13 07:48:22 weight_utils.py:163] Using model weights format ['*.safetensors']
Rank 0: load weight end.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Rank 0: max_total_num_token=52678, max_prefill_num_token=32768, context_len=32768, 
disable_radix_cache=False, enable_flashinfer=False, disable_regex_jump_forward=False, disable_disk_cache=False, attention_reduce_in_fp32=False
router init state: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/router/manager.py", line 68, in start_router_process
    model_client = ModelRpcClient(server_args, port_args)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/router/model_rpc.py", line 619, in __init__
    self.model_server.exposed_init_model(0, server_args, port_args)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/router/model_rpc.py", line 137, in exposed_init_model
    self.regex_fsm_cache = FSMCache(
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/constrained/fsm_cache.py", line 8, in __init__
    self.outlines_tokenizer = TransformerTokenizer(
  File "/usr/local/lib/python3.10/dist-packages/outlines/models/transformers.py", line 63, in __init__
    self.eos_token_id = self.tokenizer.eos_token_id
AttributeError: 'str' object has no attribute 'eos_token_id'

I encountered an error while running the Qwen model with sglang=v0.1.13 version.

**Comment by ibadurrehman1** [comment]
I was also getting the same error. I encounter it by downgrading some of the packages
sglang[all]=0.1.12
outlines<=0.0.30
 vllm==0.3.2
 
 Hopefully this works for you as well.

**Comment by hnyls2002** [comment]
It's due to `outlines` API changes, please downgrade `outlines<=0.0.34`, we will make it compatible with latest `outlines` soon.

**Comment by Yanshang1991** [comment]
> It's due to `outlines` API changes, please downgrade `outlines<=0.0.34`, we will make it compatible with latest `outlines` soon.

thanks, it works for me. But the speed of sglang is slower than vllm when I run qwen-72-awq in 4xA100. It's strange.

**Comment by ibadurrehman1** [comment]
> > It's due to `outlines` API changes, please downgrade `outlines<=0.0.34`, we will make it compatible with latest `outlines` soon.
> 
> thanks, it works for me. But the speed of sglang is slower than vllm when I run qwen-72-awq in 4xA100. It's strange.

Yeah i also tested openhermes 2.5 7b gptq with 4090. Sglang is slower than vllm and aphrodite-engine.

**Comment by 20191864218** [comment]
> > It's due to `outlines` API changes, please downgrade `outlines<=0.0.34`, we will make it compatible with latest `outlines` soon.
> 
> thanks, it works for me. But the speed of sglang is slower than vllm when I run qwen-72-awq in 4xA100. It's strange.

Hello, sir. Currently, I'm attempting to replace the LLM with Qwen7B. I've executed the pretraining and finetuning_lora stages, but encountered this error during model inference after merging the LoRA weights. I suspect there's an issue with my code. Could you please teach me how to replace Qwen and what parts of which files need to be modified? Thank you very much！

![3e60c7d007d61ae7b3f05d122f61c74](https://github.com/sgl-project/sglang/assets/56297762/f2f3cb3c-b48d-4928-80b2-fa0c42b98778)

**Comment by yuxiyan** [comment]
anyone meet this problem?   
 if tokenizer.eos_token_id not in stop_token_ids:
AttributeError: 'NoneType' object has no attribute 'eos_token_id'
![image](https://github.com/sgl-project/sglang/assets/13945327/4dd21b6d-f1ae-4f25-bee1-b35c5af92a8e)
