### ISSUE TITLE
Parallelism with `run_batch` vs `fork`

### ISSUE THREAD

**Issue by ValeKnappich** [sgl-project/sglang#295]
First of all, great work!

The frontend seems to support two kinds of parallel processing: batching and forking.

From the docs and paper, it is not entirely clear to me how they differ and how they are handled under the hood. Do they both launch separate threads that make requests to the server, which then does continuous batching? Or is there more to it?

From a practical standpoint, what are the considerations when both `run_batch` and `fork` are possible for the use case? Are there advantages/disadvantages besides fork being more flexible?

Is it safe to combine the two? Would the total number of threads be `num_threads * num_forks`?

**Comment by hnyls2002** [comment]
@ValeKnappich Yes, you can use a mixed style of `fork` and `run_batch`, let me clarify here:

We view each of the `@sgl.function` with a set of arguments as a root task, the forked branches are inner subtasks.

1. `run_batch` is just an interface, that sends all these root tasks into the interpreter.
2. `num_threads` decides how many root tasks the interpreter can handle at the same time. This is the parallelism of the interpreter.
3. All the branches created by `fork()` will have their inner threads to handle them, which has no relation with `num_threads`
4. All these parallelism above is just frontend parallelism, the backend always uses a contiguous batch and automatically maintains the running batch and waiting queue.
