### ISSUE TITLE
[Feature Request] Support for DeepSeek Vision

### ISSUE THREAD

**Issue by brucethemoose** [sgl-project/sglang#297]
Deepseek Vision 7B has a very promising architecture, and seems to perform very well in some limited testing of mine (even compared to llava 1.6 Mistral):

https://github.com/deepseek-ai/DeepSeek-VL

Support for the architecture in sglang would be lovely.

**Comment by rostandk** [comment]
I am quite impressed with the 7B version. I ran some test and find it to be better than Llava 1.6 34B. It also consistently give me valid JSON
