### ISSUE TITLE
Can SGlang run on cuda118?

### ISSUE THREAD

**Issue by stevezxzhou** [sgl-project/sglang#309]
I can't successfully run SGlang using either "python -m sglang.launch_server --model-path LOCAL_MODEL_PATH --port 30000" or "sgl.Runtime(model_path=LOCAL_MODEL_PATH)", just like the issue mentioned in https://github.com/sgl-project/sglang/issues/199 .

Could this be related to my CUDA 11.8 installation, or is there another possible reason?

Thank you.

**Comment by LuoKaiGSW** [comment]
I have set up the environment on CUDA 118, and it's working; perhaps you can refer to [this](https://github.com/sgl-project/sglang/issues/284). However, I have encountered an issue with [garbled output](https://github.com/sgl-project/sglang/issues/316) during use, and I have not yet determined the cause.

**Comment by m0g1cian** [comment]
I have no problem running SGLang on CUDA118
