### ISSUE TITLE
The output has garbled text issues

### ISSUE THREAD

**Issue by LuoKaiGSW** [sgl-project/sglang#316]
When I use llama7b after sft on sglang, I find that the output has garbled text. However, the output is normal when not using sglang. What could be the reason for this?
<img width="885" alt="image" src="https://github.com/sgl-project/sglang/assets/49229809/b2fbf2cb-174b-4579-a9ab-23522fb79ac4">

**Comment by IliaZenkov** [comment]
This is a guess: Possible you may have fine-tuned with an incorrect/malformed/non-matched template to the one you are using in SGLang to perform the inference. The readme at project root has an exmaple of registering a custom chat template which can either be set at server lunch or from the frontend, you may want to look into that. A few existing issues mention customizing chat templates as well.
