### ISSUE TITLE
Setting Data Type from the CLI interface

### ISSUE THREAD

**Issue by Reichenbachian** [sgl-project/sglang#325]
Is it possible to set the data type from the cli interface?

```
python -m sglang.launch_server --model-path llava-v1.6-34b.Q8_0.gguf --tokenizer-path liuhaotian/llava-v1.6-34b-tokenizer --port 8888 --host 0.0.0.0 --enable-flashinfer --dtype bfloat16
```

If not, it seems like a useful feature to add.

**Comment by hahmad2008** [comment]
@ Reichenbachian 
can you run inference with gguf model? if so can you provide the full command?
