### ISSUE TITLE
Supports the InternVL multimodal large model

### ISSUE THREAD

**Issue by exceedzhang** [sgl-project/sglang#328]
Can it support the InternVL multimodal large model, which currently ranks first in the MMMU open source ranking.
[https://github.com/OpenGVLab/InternVL/](https://github.com/OpenGVLab/InternVL/)
![WX20240324-102942@2x](https://github.com/sgl-project/sglang/assets/4583537/2416f85d-5231-4d8c-9255-b598385e6eaa)
[MMMU](https://mmmu-benchmark.github.io)

**Comment by themrzmaster** [comment]
Version 1.5 got releases and its strong!

**Comment by ayvbrg** [comment]
+1

**Comment by junleiz** [comment]
+1

**Comment by zhyncs** [comment]
Based on the internal information I have, new version releases will continue in the second half of the year, so we also expect to directly support the new ones. Of course, if you are interested in submitting PRs to support existing versions, contributions are welcome.

**Comment by zhyncs** [comment]
duplicate https://github.com/sgl-project/sglang/issues/1042 Close this for now. Thanks!
