### ISSUE TITLE
Add timeout management to `StreamExecutor.get_meta_info`

### ISSUE THREAD

**Issue by SimoneRaponi** [sgl-project/sglang#340]
Currently, the `StreamExecutor.get_meta_info` function does not have a way to prevent deadlock.
The code snippet is reported below, if the server is overloaded, the `.wait()` function may take forever.

```python
def get_meta_info(self, name):
    if name in self.variable_event:
        self.variable_event[name].wait()
    ret = self.meta_info.get(name, None)
    return ret
```

I propose to add a timeout parameter and to manage the exceptions accordingly, as shown below:

```python
def get_meta_info(self, name, timeout=None):
    if name in self.variable_event:
        got = self.variable_event[name].wait(timeout)
        if not got:
            raise TimeoutError(f"Timeout while waiting for event '{name}'")
    ret = self.meta_info.get(name, None)
    return ret

```

**Comment by hnyls2002** [comment]
@SimoneRaponi You are welcome to submit a PR to handle this.
