### ISSUE TITLE
Beginner here, how to load the model from checkpoint

### ISSUE THREAD

**Issue by HoqueMahmudul** [sgl-project/sglang#349]
Hi, I am relatively new to this. Currently, I am trying to fine tune llava-v1.6-mistral-7b on a sample dataset. I have a beginner level question:

How do I load the model from the checkpoint for evaluation? Are the weights model weights on adapter_model.safetensors? I am struggling to load the checkpoint to evaluate on a test set

![adapter](https://github.com/sgl-project/sglang/assets/67953269/98b5c0cb-c9f8-4a51-b88f-4fbb9feb8f62)

**Comment by hnyls2002** [comment]
@HoqueMahmudul We only support huggingface format to load model weights. I am not sure what is your checkpoint's format, you can figure out how to convert it to huggingface format.
