### ISSUE TITLE
Source build instructions gives broken build

### ISSUE THREAD

**Issue by owu-1** [sgl-project/sglang#351]
Building from source following the instructions in readme gives the error below.
```
(build) owu@gpu:/mnt/resource_nvme/sglang/python$ pip install -e "python[all]"
(build) owu@gpu:/mnt/resource_nvme$ python run.py
Traceback (most recent call last):
  File "/mnt/resource_nvme/run.py", line 3, in <module>
    @sgl.function
AttributeError: module 'sglang' has no attribute 'function'
```

Building how ```sglang/python/upload_pypi.sh``` (```python3 -m build```) does fixes the error

**Comment by qeternity** [comment]
You have a conflict between the source dir and python module name. If you `cd` back into the sglang dir, or anywhere else, you won't have this issue.

**Comment by owu-1** [comment]
I must have copied the wrong line where i compiled it... I was back a folder otherwise it would have complained about importing sglang

**Comment by owu-1** [comment]
Sorry to waste your time. I cannot reproduce this
