### ISSUE TITLE
How do I instantiate multiple sgl backends?

### ISSUE THREAD

**Issue by accupham** [sgl-project/sglang#359]
I see the option for `sgl.set_default_backend()` but this seems to be a global setting. Is there a way to get multiple backends running and pick which one is used?

**Comment by hnyls2002** [comment]
We specify the backend here.

https://github.com/sgl-project/sglang/blob/c93293c57e16566c18443bae1bfacc107b714c74/python/sglang/lang/ir.py#L144

https://github.com/sgl-project/sglang/blob/c93293c57e16566c18443bae1bfacc107b714c74/python/sglang/lang/ir.py#L180

You can use it like this:

```python
import sglang as sgl

backend = sgl.RuntimeEndpoint("xxx")

sgl_func.run(backend = backend)

sgl.func.run_batch(backend = backend)
```

**Comment by deoxynet** [comment]
Thank you!!!
