### ISSUE TITLE
Loading a BNB 4 bit model + adapter

### ISSUE THREAD

**Issue by timothelaborie** [sgl-project/sglang#374]
After doing QLoRA with a training library (unsloth) and saving the adapter, is there a way to load the 4 bit bnb model and the un-merged adapter for use with sglang? Last time I tried loading a model from an hf repo that has only the adapter, sglang complained about how it's not a valid model

**Comment by timothelaborie** [comment]
To be more specific, I have a file called adapter_config.json:
```
{
  "alpha_pattern": {},
  "auto_mapping": null,
  "base_model_name_or_path": "unsloth/tinyllama-bnb-4bit",
  "bias": "none",
  "fan_in_fan_out": false,
  "inference_mode": true,
  "init_lora_weights": true,
  "layers_pattern": null,
  "layers_to_transform": null,
  "loftq_config": {},
  "lora_alpha": 16,
  "lora_dropout": 0,
  "megatron_config": null,
  "megatron_core": "megatron.core",
  "modules_to_save": null,
  "peft_type": "LORA",
  "r": 16,
  "rank_pattern": {},
  "revision": "unsloth",
  "target_modules": [
    "v_proj",
    "o_proj",
    "q_proj",
    "k_proj",
    "down_proj",
    "gate_proj",
    "up_proj"
  ],
  "task_type": "CAUSAL_LM",
  "use_rslora": true
}
```
When I try to load it with SGL it says:
lora_model does not appear to have a file named config.json.

**Comment by abpani** [comment]
@timothelaborie  Did it work for you. I have the same situation and it does not work.

**Comment by timothelaborie** [comment]
> [@timothelaborie](https://github.com/timothelaborie) Did it work for you. I have the same situation and it does not work.

no. you have to either merge the model or use unsloth's inference
