### ISSUE TITLE
How does or does sglang support multiple completions / samples given the same prompt?

### ISSUE THREAD

**Issue by wenting-zhao** [sgl-project/sglang#379]
Thanks for the amazing project!  I was wondering if sglang supports multiple completions / samples given the same prompt?  Like similar to the num_return_sequences parameter of HF Generation. By looking at this doc (https://github.com/sgl-project/sglang/blob/main/docs/sampling_params.md) I haven't found a way to do this.  Thanks!

**Comment by Amanda2024** [comment]
I wonder how do you solve it?
