### ISSUE TITLE
Switch to non gated models

### ISSUE THREAD

**Issue by tom-doerr** [sgl-project/sglang#387]
When running
```
python -m sglang.launch_server --model-path meta-llama/Llama-2-7b-chat-hf --port 30000
```
I get
```
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/resolve/main/config.json.
Access to model meta-llama/Llama-2-7b-chat-hf is restricted. You must be authenticated to access it.
```
I assume it's the same for most people. How about switching it to a non gated model, e.g. Mistral or a quantized 8B Llama 3?

**Comment by KMouratidis** [comment]
Mistral is also gated.

![image](https://github.com/sgl-project/sglang/assets/26832680/3ad795ab-b893-4d86-89ac-0df4db7e2b07)
