### ISSUE TITLE
Regenerate benchmark results for latest vLLM

### ISSUE THREAD

**Issue by nilesh-c** [sgl-project/sglang#389]
It appears that the benchmark plots are from a much older version of vLLM (more than 4 months old https://github.com/vllm-project/vllm/releases/tag/v0.2.5). With the latest improvements (e.g. automatic prefix caching), the numbers on vllm look much better.

I ran the MMLU benchmark with a vllm==0.4.1 backend, and it performs just as fast as using an sglang server.

**Comment by m0g1cian** [comment]
My assumption is that the latest vllm version adds automatic prefix caching and that accelerates inference performance a lot
