### ISSUE TITLE
Prefill out of memory occur when deployed with servers 

### ISSUE THREAD

**Issue by for-just-we** [sgl-project/sglang#393]
I use 4 A6000 to deploy Qwen1.5-72B-Chat. The command I start server is `CUDA_VISIBLE_DEVICES=0,1,2,3 python -m sglang.launch_server --tp-size 4 --model-path Qwen1.5-72B-Chat --port 8991 --context-length 16000`. During inference, I encounter

```
Prefill out of memory. This should nerver happen.
 3 (151644, 8948, 198) r=1
   1 (2610,) r=1
     2 (525, 264) r=1
       1 (2038,) r=1
#tokens: 7
```

How to fix this issue?

**Comment by hnyls2002** [comment]
@for-just-we Could you please checkout if there is a KV cache leak during the inference or some other runtime errors?

**Comment by for-just-we** [comment]
I didn't see something related to KV cache leak or other runtime errors in the server logging. Part of log is:

```
INFO:     127.0.0.1:32978 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 757. #new_token: 1. #remaining_req: 4. #running_req: 2. tree_cache_hit_rate: 80.83%.
new fill batch. #seq: 1. #cached_token: 746. #new_token: 1. #remaining_req: 3. #running_req: 3. tree_cache_hit_rate: 80.84%.
new fill batch. #seq: 1. #cached_token: 673. #new_token: 1. #remaining_req: 2. #running_req: 4. tree_cache_hit_rate: 80.85%.
INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 17. #new_token: 353. #remaining_req: 1. #running_req: 3. tree_cache_hit_rate: 80.82%.
new fill batch. #seq: 1. #cached_token: 17. #new_token: 106. #remaining_req: 0. #running_req: 4. tree_cache_hit_rate: 80.82%.
#running-req: 5, #token: 1938, token usage: 0.24, #queue-req: 0
INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 478. #new_token: 254. #remaining_req: 0. #running_req: 4. tree_cache_hit_rate: 80.81%.
INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 731. #new_token: 1. #remaining_req: 0. #running_req: 4. tree_cache_hit_rate: 80.82%.
INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32926 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 731. #new_token: 1. #remaining_req: 2. #running_req: 2. tree_cache_hit_rate: 80.83%.
new fill batch. #seq: 1. #cached_token: 477. #new_token: 198. #remaining_req: 1. #running_req: 3. tree_cache_hit_rate: 80.83%.
new fill batch. #seq: 1. #cached_token: 51. #new_token: 66. #remaining_req: 0. #running_req: 4. tree_cache_hit_rate: 80.82%.
#running-req: 3, #token: 1442, token usage: 0.18, #queue-req: 0
INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32890 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 760. #new_token: 1. #remaining_req: 1. #running_req: 2. tree_cache_hit_rate: 80.83%.
new fill batch. #seq: 1. #cached_token: 731. #new_token: 1. #remaining_req: 1. #running_req: 3. tree_cache_hit_rate: 80.85%.
INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 731. #new_token: 1. #remaining_req: 1. #running_req: 2. tree_cache_hit_rate: 80.86%.
INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 30. #new_token: 2045. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.72%.
#running-req: 3, #token: 3186, token usage: 0.40, #queue-req: 0
INFO:     127.0.0.1:32978 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 46. #new_token: 117. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.71%.
INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 760. #new_token: 1. #remaining_req: 4. #running_req: 2. tree_cache_hit_rate: 80.78%.
new fill batch. #seq: 1. #cached_token: 757. #new_token: 1. #remaining_req: 3. #running_req: 3. tree_cache_hit_rate: 80.80%.
new fill batch. #seq: 1. #cached_token: 56. #new_token: 53. #remaining_req: 2. #running_req: 4. tree_cache_hit_rate: 80.79%.
#running-req: 3, #token: 1336, token usage: 0.17, #queue-req: 2
INFO:     127.0.0.1:32978 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32940 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 757. #new_token: 1. #remaining_req: 4. #running_req: 2. tree_cache_hit_rate: 80.81%.
new fill batch. #seq: 1. #cached_token: 746. #new_token: 1. #remaining_req: 3. #running_req: 3. tree_cache_hit_rate: 80.82%.
new fill batch. #seq: 1. #cached_token: 47. #new_token: 82. #remaining_req: 2. #running_req: 4. tree_cache_hit_rate: 80.81%.
INFO:     127.0.0.1:32978 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 757. #new_token: 1. #remaining_req: 4. #running_req: 2. tree_cache_hit_rate: 80.83%.
new fill batch. #seq: 1. #cached_token: 746. #new_token: 1. #remaining_req: 3. #running_req: 3. tree_cache_hit_rate: 80.84%.
new fill batch. #seq: 1. #cached_token: 673. #new_token: 1. #remaining_req: 2. #running_req: 4. tree_cache_hit_rate: 80.85%.
INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 17. #new_token: 353. #remaining_req: 1. #running_req: 3. tree_cache_hit_rate: 80.82%.
new fill batch. #seq: 1. #cached_token: 17. #new_token: 106. #remaining_req: 0. #running_req: 4. tree_cache_hit_rate: 80.82%.
#running-req: 5, #token: 1938, token usage: 0.24, #queue-req: 0
INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 478. #new_token: 254. #remaining_req: 0. #running_req: 4. tree_cache_hit_rate: 80.81%.
INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 731. #new_token: 1. #remaining_req: 0. #running_req: 4. tree_cache_hit_rate: 80.82%.
INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32926 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 731. #new_token: 1. #remaining_req: 2. #running_req: 2. tree_cache_hit_rate: 80.83%.
new fill batch. #seq: 1. #cached_token: 477. #new_token: 198. #remaining_req: 1. #running_req: 3. tree_cache_hit_rate: 80.83%.
new fill batch. #seq: 1. #cached_token: 51. #new_token: 66. #remaining_req: 0. #running_req: 4. tree_cache_hit_rate: 80.82%.
#running-req: 3, #token: 1442, token usage: 0.18, #queue-req: 0
INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32890 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 760. #new_token: 1. #remaining_req: 1. #running_req: 2. tree_cache_hit_rate: 80.83%.
new fill batch. #seq: 1. #cached_token: 731. #new_token: 1. #remaining_req: 1. #running_req: 3. tree_cache_hit_rate: 80.85%.
INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 731. #new_token: 1. #remaining_req: 1. #running_req: 2. tree_cache_hit_rate: 80.86%.
INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 30. #new_token: 2045. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.72%.
#running-req: 3, #token: 3186, token usage: 0.40, #queue-req: 0
INFO:     127.0.0.1:32978 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 46. #new_token: 117. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.71%.
INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 757. #new_token: 1. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.72%.
#running-req: 3, #token: 3176, token usage: 0.40, #queue-req: 0
INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 477. #new_token: 302. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.71%.
INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 778. #new_token: 1. #remaining_req: 1. #running_req: 1. tree_cache_hit_rate: 80.72%.
new fill batch. #seq: 1. #cached_token: 42. #new_token: 108. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.71%.
INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 674. #new_token: 1. #remaining_req: 0. #running_req: 1. tree_cache_hit_rate: 80.73%.
new fill batch. #seq: 1. #cached_token: 778. #new_token: 1. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.74%.
#running-req: 1, #token: 812, token usage: 0.10, #queue-req: 0
INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 778. #new_token: 1. #remaining_req: 1. #running_req: 1. tree_cache_hit_rate: 80.75%.
new fill batch. #seq: 1. #cached_token: 674. #new_token: 1. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.76%.
INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 674. #new_token: 1. #remaining_req: 0. #running_req: 1. tree_cache_hit_rate: 80.80%.
INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
#running-req: 1, #token: 852, token usage: 0.11, #queue-req: 0
INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 61. #new_token: 99. #remaining_req: 0. #running_req: 0. tree_cache_hit_rate: 80.79%.
INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 7. #new_token: 9423. #remaining_req: 0. #running_req: 0. tree_cache_hit_rate: 80.15%.
Prefill out of memory. This should nerver happen.
 3 (151644, 8948, 198) r=1
   1 (2610,) r=1
     2 (525, 264) r=1
       1 (2038,) r=1
#tokens: 7
Prefill out of memory. This should nerver happen.
 3 (151644, 8948, 198) r=1
   1 (2610,) r=1
     2 (525, 264) r=1
       1 (2038,) r=1
#tokens: 7
Prefill out of memory. This should nerver happen.
 3 (151644, 8948, 198) r=1
   1 (2610,) r=1
     2 (525, 264) r=1
       1 (2038,) r=1
#tokens: 7
Prefill out of memory. This should nerver happen.
 3 (151644, 8948, 198) r=1
   1 (2610,) r=1
     2 (525, 264) r=1
       1 (2038,) r=1
#tokens: 7
```

The last is the only error message I see

**Comment by for-just-we** [comment]
> I didn't see something related to KV cache leak or other runtime errors in the server logging. Part of log is:
> 
> ```
> INFO:     127.0.0.1:32978 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 757. #new_token: 1. #remaining_req: 4. #running_req: 2. tree_cache_hit_rate: 80.83%.
> new fill batch. #seq: 1. #cached_token: 746. #new_token: 1. #remaining_req: 3. #running_req: 3. tree_cache_hit_rate: 80.84%.
> new fill batch. #seq: 1. #cached_token: 673. #new_token: 1. #remaining_req: 2. #running_req: 4. tree_cache_hit_rate: 80.85%.
> INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 17. #new_token: 353. #remaining_req: 1. #running_req: 3. tree_cache_hit_rate: 80.82%.
> new fill batch. #seq: 1. #cached_token: 17. #new_token: 106. #remaining_req: 0. #running_req: 4. tree_cache_hit_rate: 80.82%.
> #running-req: 5, #token: 1938, token usage: 0.24, #queue-req: 0
> INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 478. #new_token: 254. #remaining_req: 0. #running_req: 4. tree_cache_hit_rate: 80.81%.
> INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 731. #new_token: 1. #remaining_req: 0. #running_req: 4. tree_cache_hit_rate: 80.82%.
> INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32926 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 731. #new_token: 1. #remaining_req: 2. #running_req: 2. tree_cache_hit_rate: 80.83%.
> new fill batch. #seq: 1. #cached_token: 477. #new_token: 198. #remaining_req: 1. #running_req: 3. tree_cache_hit_rate: 80.83%.
> new fill batch. #seq: 1. #cached_token: 51. #new_token: 66. #remaining_req: 0. #running_req: 4. tree_cache_hit_rate: 80.82%.
> #running-req: 3, #token: 1442, token usage: 0.18, #queue-req: 0
> INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32890 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 760. #new_token: 1. #remaining_req: 1. #running_req: 2. tree_cache_hit_rate: 80.83%.
> new fill batch. #seq: 1. #cached_token: 731. #new_token: 1. #remaining_req: 1. #running_req: 3. tree_cache_hit_rate: 80.85%.
> INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 731. #new_token: 1. #remaining_req: 1. #running_req: 2. tree_cache_hit_rate: 80.86%.
> INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 30. #new_token: 2045. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.72%.
> #running-req: 3, #token: 3186, token usage: 0.40, #queue-req: 0
> INFO:     127.0.0.1:32978 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 46. #new_token: 117. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.71%.
> INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 760. #new_token: 1. #remaining_req: 4. #running_req: 2. tree_cache_hit_rate: 80.78%.
> new fill batch. #seq: 1. #cached_token: 757. #new_token: 1. #remaining_req: 3. #running_req: 3. tree_cache_hit_rate: 80.80%.
> new fill batch. #seq: 1. #cached_token: 56. #new_token: 53. #remaining_req: 2. #running_req: 4. tree_cache_hit_rate: 80.79%.
> #running-req: 3, #token: 1336, token usage: 0.17, #queue-req: 2
> INFO:     127.0.0.1:32978 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32940 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 757. #new_token: 1. #remaining_req: 4. #running_req: 2. tree_cache_hit_rate: 80.81%.
> new fill batch. #seq: 1. #cached_token: 746. #new_token: 1. #remaining_req: 3. #running_req: 3. tree_cache_hit_rate: 80.82%.
> new fill batch. #seq: 1. #cached_token: 47. #new_token: 82. #remaining_req: 2. #running_req: 4. tree_cache_hit_rate: 80.81%.
> INFO:     127.0.0.1:32978 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 757. #new_token: 1. #remaining_req: 4. #running_req: 2. tree_cache_hit_rate: 80.83%.
> new fill batch. #seq: 1. #cached_token: 746. #new_token: 1. #remaining_req: 3. #running_req: 3. tree_cache_hit_rate: 80.84%.
> new fill batch. #seq: 1. #cached_token: 673. #new_token: 1. #remaining_req: 2. #running_req: 4. tree_cache_hit_rate: 80.85%.
> INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 17. #new_token: 353. #remaining_req: 1. #running_req: 3. tree_cache_hit_rate: 80.82%.
> new fill batch. #seq: 1. #cached_token: 17. #new_token: 106. #remaining_req: 0. #running_req: 4. tree_cache_hit_rate: 80.82%.
> #running-req: 5, #token: 1938, token usage: 0.24, #queue-req: 0
> INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 478. #new_token: 254. #remaining_req: 0. #running_req: 4. tree_cache_hit_rate: 80.81%.
> INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 731. #new_token: 1. #remaining_req: 0. #running_req: 4. tree_cache_hit_rate: 80.82%.
> INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32926 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 731. #new_token: 1. #remaining_req: 2. #running_req: 2. tree_cache_hit_rate: 80.83%.
> new fill batch. #seq: 1. #cached_token: 477. #new_token: 198. #remaining_req: 1. #running_req: 3. tree_cache_hit_rate: 80.83%.
> new fill batch. #seq: 1. #cached_token: 51. #new_token: 66. #remaining_req: 0. #running_req: 4. tree_cache_hit_rate: 80.82%.
> #running-req: 3, #token: 1442, token usage: 0.18, #queue-req: 0
> INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32890 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 760. #new_token: 1. #remaining_req: 1. #running_req: 2. tree_cache_hit_rate: 80.83%.
> new fill batch. #seq: 1. #cached_token: 731. #new_token: 1. #remaining_req: 1. #running_req: 3. tree_cache_hit_rate: 80.85%.
> INFO:     127.0.0.1:40192 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 731. #new_token: 1. #remaining_req: 1. #running_req: 2. tree_cache_hit_rate: 80.86%.
> INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 30. #new_token: 2045. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.72%.
> #running-req: 3, #token: 3186, token usage: 0.40, #queue-req: 0
> INFO:     127.0.0.1:32978 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 46. #new_token: 117. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.71%.
> INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 757. #new_token: 1. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.72%.
> #running-req: 3, #token: 3176, token usage: 0.40, #queue-req: 0
> INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 477. #new_token: 302. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.71%.
> INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 778. #new_token: 1. #remaining_req: 1. #running_req: 1. tree_cache_hit_rate: 80.72%.
> new fill batch. #seq: 1. #cached_token: 42. #new_token: 108. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.71%.
> INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 674. #new_token: 1. #remaining_req: 0. #running_req: 1. tree_cache_hit_rate: 80.73%.
> new fill batch. #seq: 1. #cached_token: 778. #new_token: 1. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.74%.
> #running-req: 1, #token: 812, token usage: 0.10, #queue-req: 0
> INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 778. #new_token: 1. #remaining_req: 1. #running_req: 1. tree_cache_hit_rate: 80.75%.
> new fill batch. #seq: 1. #cached_token: 674. #new_token: 1. #remaining_req: 0. #running_req: 2. tree_cache_hit_rate: 80.76%.
> INFO:     127.0.0.1:32912 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 674. #new_token: 1. #remaining_req: 0. #running_req: 1. tree_cache_hit_rate: 80.80%.
> INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> #running-req: 1, #token: 852, token usage: 0.11, #queue-req: 0
> INFO:     127.0.0.1:32968 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 61. #new_token: 99. #remaining_req: 0. #running_req: 0. tree_cache_hit_rate: 80.79%.
> INFO:     127.0.0.1:32878 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> new fill batch. #seq: 1. #cached_token: 7. #new_token: 9423. #remaining_req: 0. #running_req: 0. tree_cache_hit_rate: 80.15%.
> Prefill out of memory. This should nerver happen.
>  3 (151644, 8948, 198) r=1
>    1 (2610,) r=1
>      2 (525, 264) r=1
>        1 (2038,) r=1
> #tokens: 7
> Prefill out of memory. This should nerver happen.
>  3 (151644, 8948, 198) r=1
>    1 (2610,) r=1
>      2 (525, 264) r=1
>        1 (2038,) r=1
> #tokens: 7
> Prefill out of memory. This should nerver happen.
>  3 (151644, 8948, 198) r=1
>    1 (2610,) r=1
>      2 (525, 264) r=1
>        1 (2038,) r=1
> #tokens: 7
> Prefill out of memory. This should nerver happen.
>  3 (151644, 8948, 198) r=1
>    1 (2610,) r=1
>      2 (525, 264) r=1
>        1 (2038,) r=1
> #tokens: 7
> ```
> 
> The last is the only error message I see. I guess this may be one of the query is too long, but I don't know how to fix this.

**Comment by aflah02** [comment]
+1 I also got this today when running Llama 2 70B on a 2xH100 machine - 
![image](https://github.com/sgl-project/sglang/assets/72096386/011997d1-867a-4242-bc81-eddcd53b5092)

I am using the same command on 2 other 2xH100 machines and one 2xA100 machine and it works well on the rest. I was sending requests using 2 clients btw and it did run for a couple of hours before showing this error and when I restart it I get this error again after a bit.

**Comment by aflah02** [comment]
Update: I skipped over the data point which caused the issue again and again and it works now. I did not have the time to investigate that specific datapoint but incase someone hits this issue maybe try skipping the data point.

**Comment by aflah02** [comment]
Update: This happens very frequently now 
No idea what is wrong. I don't see a KV leak either, @hnyls2002 any ideas?
