### ISSUE TITLE
Launch server using local LLaVA checkpoints

### ISSUE THREAD

**Issue by lukashelff** [sgl-project/sglang#397]
Has anyone managed to launch a server from a local model checkpoint. 
I'm still facing some difficulties after trying to launch llava-1.5-13b after it has been fine-tuned using the llava fine-tuning script.
Untill now i proceeded as follows:

1. update "model_type" in config.json file from "llava_lama" to "llava"
2. update folder name to llava, otherwise is_multimodal flag is set incorrectly and the server does not launch.
3. The preprocessor_config.json is not saved after running the llava training script (I used the one found in HF repo llava-hf/llava-1.5-13b-hf).
4. I added the dictonary for the image token to the "added_tokens_decoder" tokenizer_config.json as it was missing.
5. Also the processor_class was missing inside the tokenizer_config.json. i added "processor_class": "LlavaProcessor"

Unfortunately i am still missing out on something. While the server is now able to launch i get CUDA hardware-side errors during inference. The default llava model works fine.

**Comment by ayvbrg** [comment]
+1

**Comment by lukashelff** [comment]
I was able to load local v1.6 checkpoints as follows:
1. Don't use the local tokenizer. Use the HG tokenizer provided by sglang.
2. Update folder name to llava, otherwise is_multimodal flag is set incorrectly and the server does not launch.
3. Update model config.json: 
- `model_type`: "llava_lama" -> "llava"
- `image_aspect_ratio`: "pad" -> "anyres"
- `mm_patch_merge_type`: "flat" -> "spatial_unpad"
- `_name_or_path`: must contain the exact model_name for sglang to select the correct chat template e.g. "llava-v1.6-34b" 
For 1.5 checkpoints proceed with the steps 1 and 2 from above. In the config.json of the model adjust the `model_type` and remove entries `mm_patch_merge_type` and `mm_projector_lr`.

**Comment by Don-Chad** [comment]
Guys, with this working - how does one do inference at a higher res ?
