### ISSUE TITLE
Support InternVL 1.5

### ISSUE THREAD

**Issue by themrzmaster** [sgl-project/sglang#398]
Strong model with great capabilities:
https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5

![image](https://github.com/sgl-project/sglang/assets/852747/46ebbf2f-4c53-42a5-a2e2-ac8e873ce356)

with some OCR tests, the best OS that i've tested

**Comment by ruifengma** [comment]
Any Plan for support this model?

**Comment by ayvbrg** [comment]
+1
