### ISSUE TITLE
Custom chat template

### ISSUE THREAD

**Issue by nivibilla** [sgl-project/sglang#40]
This would be useful when using a model like mistral-instruct, or any model that doesn't have a standardised template like chatml. Or for example using a finetuned model that uses a custom chat/instruct template.

**Comment by merrymercy** [comment]
Hi @nivibilla, we have correctly handled the chat template for mixtral, mistral, llama, vicuna, and llava.  Here is the related code.

https://github.com/sgl-project/sglang/blob/98a3e8ef78f673175a6890fd0ed8f39a6bd51b07/python/sglang/lang/chat_template.py#L161-L164

https://github.com/sgl-project/sglang/blob/98a3e8ef78f673175a6890fd0ed8f39a6bd51b07/python/sglang/lang/chat_template.py#L134-L145

You can register your own chat template following a similar style. Let me know if you have any questions. We can add some doc on this later (or you can help us by contributing one)

**Comment by nivibilla** [comment]
Thanks.

**Comment by zengqingfu1442** [comment]
Can we put our custom system prompt in chat template and make llm use this chat template when starting sglang server?
