### ISSUE TITLE
Please add Phi3 support

### ISSUE THREAD

**Issue by Curiosity007** [sgl-project/sglang#407]
Getting this error - 

```
router init state: Traceback (most recent call last):
  File "/home/ubuntu/sglang/python/sglang/srt/managers/router/manager.py", line 73, in start_router_process
    model_client = ModelRpcClient(server_args, port_args)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/router/model_rpc.py", line 657, in __init__
    self.model_server = ModelRpcService().exposed_ModelRpcServer(
  File "/home/ubuntu/sglang/python/sglang/srt/managers/router/model_rpc.py", line 70, in __init__
    self.model_runner = ModelRunner(
  File "/home/ubuntu/sglang/python/sglang/srt/managers/router/model_runner.py", line 294, in __init__
    self.load_model()
  File "/home/ubuntu/sglang/python/sglang/srt/managers/router/model_runner.py", line 303, in load_model
    model_class = get_model_cls_by_arch_name(architectures)
  File "/home/ubuntu/sglang/python/sglang/srt/managers/router/model_runner.py", line 58, in get_model_cls_by_arch_name
    raise ValueError(
ValueError: Unsupported architectures: Phi3ForCausalLM. Supported list: ['CohereForCausalLM', 'DbrxForCausalLM', 'GemmaForCausalLM', 'LlamaForCausalLM', 'LlavaLlamaForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'StableLmForCausalLM', 'YiVLForCausalLM']

```

**Comment by gintasz** [comment]
hmm, I just wanted to try this as well... sadly not supported yet.

**Comment by Gintasz** [comment]
I checked cohere model on sglang. Looks like the code is taken from here huggingface transformers library:
https://github.com/huggingface/transformers/blob/main/src/transformers/models/cohere/modeling_cohere.py

and transformers library does have phi3 support:
https://github.com/huggingface/transformers/tree/main/src/transformers/models/phi3

**Comment by gintasz** [comment]
@hnyls2002
what would be your thoughts? I'm using SGLang for bulk information extraction, so Phi3-mini would be very interesting to try since it's only 3.8B

**Comment by Sanket-Kudtarkar-AI** [comment]
Still no support for poor Phi-3

**Comment by JerroldJV** [comment]
Phi-3 support would be a great addition.  We would really benefit from it.

**Comment by arunpatala** [comment]
Hi, how can i make changes to add support for Phi3. Can i copy the PhiForCausalLM class (phi3.py) from vllm and replace the PagedAttention with RadixAttention? I can make a pulled request if this is the case?

**Comment by zhyncs** [comment]
Phi3 I remember the part about Attention is slightly different from Llama, we might consider supporting it in SGLang after getting support from FlashInfer. cc @yzh119

**Comment by yzh119** [comment]
@zhyncs what's the difference between?

**Comment by zhyncs** [comment]
ref https://github.com/sgl-project/sglang/pull/1299
