### ISSUE TITLE
Chat role prefixes for SRT backend broken in latest

### ISSUE THREAD

**Issue by qeternity** [sgl-project/sglang#410]
Just noticed as we were trying to merge the latest changes. For example, the following raises a nested roles exception:

`s += assistant("The answer is:" + gen("answer"))`

I don't have time at the moment to pin down what is causing this, but it's one of the strengths of the SRT backend when we have full control over the API. I appreciate why this wouldn't work with OpenAI et al, but it should work with SRT completion.

**Comment by qeternity** [comment]
Actually, this appears to be related to a specific part in our code where we fork just after a generation call.

It seems there is some sort of race condition here where the previous assistant role is not being closed before forking the new state. All of this goes away if we call `.sync()` after we fork the new state. We had assumed there was an implicit sync during fork, not sure if some of the recent related commits have broken this?

Broken:
```
s += user("What color is the sky?")
s += assistant("The answer is:" + gen("answer"))
f = s.fork(1)[0]
f += user("What color is the ocean?")
f += assistant("The answer is:" + gen("answer"))
```

Working:
```
s += user("What color is the sky?")
s += assistant("The answer is:" + gen("answer"))
s.sync()
f = s.fork(1)[0]
f += user("What color is the ocean?")
f += assistant("The answer is:" + gen("answer"))
```

**Comment by qeternity** [comment]
Yes ok, I see exactly where this was introduced. We're not only syncing for > 1 forks?

**Comment by hnyls2002** [comment]
@qeternity Hi, could you please test this PR #412, is your problem fixed?
