### ISSUE TITLE
run python3 test_httpserver_llava.py get ValueError: 64002 is not in list

### ISSUE THREAD

**Issue by Aurorana** [sgl-project/sglang#413]
run python3 test_httpserver_llava.py
offset = input_ids.index(self.config.image_token_index)
ValueError: 64002 is not in list

def test_streaming(args):
    url = f"{args.host}:{args.port}"
    response = requests.post(
        url + "/generate",
        json={
            'text' : 'A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human\'s questions. USER: <im_start><image><im_end> description the video indetail \n Assistant:', 
            # "text": "A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions. USER: Describe this picture <|im_start|> <|im_end|>\n ASSISTANT:",
            "image_data": "examples/image1.webp",
            "sampling_params": {
                "temperature": 0,
                "max_new_tokens": 128,
            },
            "stream": True,
        },
        stream=True,
    )
    print(response)
    prev = 0
    for chunk in response.iter_lines(decode_unicode=False):
        chunk = chunk.decode("utf-8")
        if chunk and chunk.startswith("data:"):
            if chunk == "data: [DONE]":
                break
            data = json.loads(chunk[5:].strip("\n"))
            output = data["text"].strip()
            print(output[prev:], end="", flush=True)
            prev = len(output)
    print("--------")

**Comment by apt-team-018** [comment]
facing same issues

**Comment by apt-team-018** [comment]
@Aurorana you have to use vision enabled toknizer, as we added extra <image> token in vocab.

for llama3next you can use - lmms-lab/llama3-llava-next-8b-tokenizer

you just have to replace - [preprocessor_config.json](https://huggingface.co/lmms-lab/llama3-llava-next-8b-tokenizer/blob/main/preprocessor_config.json), [special_tokens_map.json](https://huggingface.co/lmms-lab/llama3-llava-next-8b-tokenizer/blob/main/special_tokens_map.json),  [tokenizer.json](https://huggingface.co/lmms-lab/llama3-llava-next-8b-tokenizer/blob/main/tokenizer.json), [tokenizer_config.json](https://huggingface.co/lmms-lab/llama3-llava-next-8b-tokenizer/blob/main/tokenizer_config.json) files

do not replace config.json
