### ISSUE TITLE
OpenAI speculative execution

### ISSUE THREAD

**Issue by Ying1123** [sgl-project/sglang#44]
The current frontend using OpenAI will invoke multiple calls for the example below:
```
@sgl.function
def example(s):
  s += "Construct a character."
  s += "Name: " + gen("name") + " Birthday: " + gen("birthday") + " Job: " + gen("job")
```
We can optimize this to send less number of calls to save money:
1. Gen longer in the first gen call, and skip the later if the first gen did the right thing.
2. Allow using OpenAI's n=10 keyword argument to sample multiple completions when forked. We can also provide the interface `example.run(n=10)`.

**Comment by parasol-aser** [comment]
@Ying1123 see this PR https://github.com/sgl-project/sglang/pull/48

**Comment by okhat** [comment]
This team is fast! Thanks guys. Will update you here on the integration on our end

**Comment by Ying1123** [comment]
Completion supported in #48.
