### ISSUE TITLE
RuntimeError: Cannot re-initialize CUDA in forked subprocess. 

### ISSUE THREAD

**Issue by sunil448832** [sgl-project/sglang#462]
Installed sglang using 
`pip install "sglang[all]"`
launched model with command:
`python -m sglang.launch_server --model-path mistralai/Mistral-7B-Instruct-v0.2 --port 30000`

Getting error:
raise RuntimeError( RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method  Initialization failed. detoken_init_state: init ok

1 week before it was working fine.

**Comment by itay-verkh-lightricks** [comment]
try doing pip uninstall accelerate

**Comment by sunil448832** [comment]
Thanks. It's working now.
