### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by pseudotensor** [sgl-project/sglang#466]
If I set --api-key , then always get invalid api key from server.

e.g.
```
python -m sglang.launch_server --model-path lmms-lab/llama3-llava-next-8b --tokenizer-path lmms-lab/llama3-llava-next-8b-tokenizer --port=30000 --host="0.0.0.0" --tp-size=1 --random-seed=1234 --context-length=8192 --api-key=APIKEY
```

then client (even on same machine) does:
```
curl -H "Authorization: Bearer APIKEY" http://localhost:30000
```
always results in 
```
{"detail":"Invalid API Key"}
```

I've ensured that there are no other processes around and nothing else using that port.  Everything works well if don't set the api key.

**Comment by alessiodallapiazza** [comment]
Ciao @pseudotensor,
to use the API, include the header `X-API-Key`.

Here’s an example of how to use it with `curl`:

```sh
curl http://localhost:3000/get_model_info -H 'X-API-Key: XXXXXXXXX' -v
```

Make sure to use the correct `X-API-Key` header as shown above.

**Comment by pseudotensor** [comment]
I see, different auth method, thanks!

**Comment by yur1xpp** [comment]
@alessiodallapiazza is there anyway to start the server that makes it accepts the `-H "Authorization: Bearer APIKEY"` header?. This `X-API-Key` header method seems to break tools out there like promptflow.

**Comment by dinhanhx** [comment]
I just try with docker `lmsysorg/sglang:v0.3.6.post2-cu124-srt`. Using `X-API-KEY` doesn't work. I think we should raise new issue or reopen this.
