### ISSUE TITLE
Unable to load 72b llava qwen on 8*A100 40GB

### ISSUE THREAD

**Issue by jeffhernandez1995** [sgl-project/sglang#507]
Using the command: `CUDA_VISIBLE_DEVICES=0,1,2,3 python -m sglang.launch_server --model-path lmms-lab/llava-next-72b --tokenizer-path lmms-lab/llavanext-qwen-tokenizer --port=8000 --host="0.0.0.0" --tp-size=4`

Results in error:

```
torch.distributed.DistStoreError: Timed out after 601 seconds waiting for clients. 1/4 clients joined.
Initialization failed. detoken_init_state: init ok
```

**Comment by ad1192214879** [comment]
解决了吗

**Comment by jeffhernandez1995** [comment]
Sorry, I don't speak Chinese. Are you telling me to fix it? or if I managed to solve the issue?

**Comment by StrangeTcy** [comment]
> Sorry, I don't speak Chinese. Are you telling me to fix it? or if I managed to solve the issue?

https://translate.google.com/?sl=auto&tl=en&text=%E8%A7%A3%E5%86%B3%E4%BA%86%E5%90%97&op=translate

**Comment by chuangzhidan** [comment]
> Sorry, I don't speak Chinese. Are you telling me to fix it? or if I managed to solve the issue?

he is asking if you have managed to solve the issue

**Comment by jeffhernandez1995** [comment]
No, I gave up and just loaded the model directly; although it is slower than Sglang, it works.
```
tokenizer = AutoTokenizer.from_pretrained(model_pth, use_fast=False)

model = LlavaQwenForCausalLM.from_pretrained(
    model_pth,
    low_cpu_mem_usage=True,
    attn_implementation="flash_attention_2",
    torch_dtype=TORCH_TYPE,
    device_map='auto',
)
```
