### ISSUE TITLE
Improving SG-LANG boot-times?

### ISSUE THREAD

**Issue by schopra8** [sgl-project/sglang#509]
I've been playing around with SG-LANG and local models (e.g. GEMMA) -- and i've noticed that it takes a bit of time before I'm able to run batch inference (e.g., 1-2 minutes).

Has anyone else seen similar "boot-time" performance? I'm wondering if this related to a slow hard-drive. Or, if there are any other optimizations to get sg-lang to "boot up" faster to serve traffic.

Thanks!

**Comment by Qubitium** [comment]
@schopra8  You need to exclude the model loading time as it is out of control of sglang  or any other inference library. 

1. disk to cpu ram
2. cpu ram to gpu
3. if you are you using gptq quant, there may be even more delay as backend upconverts compatible gptq to gptq_marlin.
