### ISSUE TITLE
Support for Qwen2MoeForCausalLM?

### ISSUE THREAD

**Issue by fedshyvana** [sgl-project/sglang#513]
As part of the Qwen2 series, Qwen2-57B-A14B is released, which delivers competitive performance against 32B dense models, and would be really valuable addition to community! It however, requires the Qwen2MoeForCausalLM architecture which is currently not implemented in SGL. Is there any plan to support this? Thanks!

https://qwenlm.github.io/blog/qwen2/

**Comment by merrymercy** [comment]
contributions are welcome.

**Comment by m0g1cian** [comment]
I've submit a PR to support `Qwen2MoeForCausalLM`. 
#603
