### ISSUE TITLE
Mistral v0.3 Weight Loading

### ISSUE THREAD

**Issue by huyiwen** [sgl-project/sglang#519]
Failed to launch the sglang server:

Run command: `python -m sglang.launch_server --model-path Mistral-7B-Instruct-v0.3 --port 30000`

Error message: `KeyError: 'layers.0.attention.wk.weight'`

This issue is also [reported](https://github.com/vllm-project/vllm/issues/5061) and [fixed](https://github.com/vllm-project/vllm/pull/5005) in vLLM.

**Comment by zhyncs** [comment]
Hi @huyiwen May you try the latest version? I couldn't reproduce your issue on A100.
```bash
git clone https://github.com/sgl-project/sglang.git
cd sglang

pip install --upgrade pip
pip install -e "python[all]"

pip install flashinfer -i https://flashinfer.ai/whl/cu121/torch2.3/

python3 -m sglang.launch_server --model mistralai/Mistral-7B-Instruct-v0.3
```

**Comment by zhyncs** [comment]
This issue has been closed because it cannot be reproduced in the latest version. Please feel free to reopen it if needed. Thanks.
