### ISSUE TITLE
SG-Lang Runtime Stuck Launching in Docker Container

### ISSUE THREAD

**Issue by schopra8** [sgl-project/sglang#527]
We're trying to run the latest version of `sg-lang` in a Docker Container (PyTorch 2.3.0, CUDA 12.1) -- but the runtime instantiation gets stuck. It's start loading the model onto the GPU and then hangs.

We've been able to run `sg-lang` without any problems on the host operating system. So we pip froze the requirements on the host instance and installed these exact packages within the Docker Container -- but we're still hitting this model loading hang.

Has anyone seen this issue before? Any ideas what might be going wrong?

**Comment by schopra8** [comment]
I've found the line that causes the hang -- but I have no clue why this is a problem:

https://github.com/sgl-project/sglang/blob/542bc733d6ebb6da2554704fc101830a07791584/python/sglang/srt/managers/controller/model_runner.py#L242

I'm running with `dp=1` and `tp=1` (i.e., on a single GPU). If I run `torch.cuda.set_device(0)` in my python script -- before I create the Runtime, everything works as expected.

**Comment by dinhanhx** [comment]
I recently discovered this issue by running docker images
```bash
lmsysorg/sglang           latest                   a50cab878736   3 days ago      16.3GB
lmsysorg/sglang           v0.3.6.post2-cu124-srt   ea52c1d7f333   5 days ago      16.6GB
```

**Comment by dinhanhx** [comment]
> I've found the line that causes the hang -- but I have no clue why this is a problem:
> 
> https://github.com/sgl-project/sglang/blob/542bc733d6ebb6da2554704fc101830a07791584/python/sglang/srt/managers/controller/model_runner.py#L242
> 
> I'm running with `dp=1` and `tp=1` (i.e., on a single GPU). If I run `torch.cuda.set_device(0)` in my python script -- before I create the Runtime, everything works as expected.

Try put it in a function that gets called after initialising ModelRunner object.
