### ISSUE TITLE
AttributeError: module 'flashinfer' has no attribute 'batch_prefill_with_paged_kv_cache'

### ISSUE THREAD

**Issue by ZackZeng999** [sgl-project/sglang#533]
**Description**:
When running the 'test_batch_prefill_with_paged_kv_cache' test in test_flashinfer.py, an AttributeError occurs, indicating that the flashinfer module has no attribute 'batch_prefill_with_paged_kv_cache'.

**Suggested Fix**:
Update the test test_batch_prefill_with_paged_kv_cache in test_flashinfer.py to use the correct method.

![image](https://github.com/sgl-project/sglang/assets/157339885/c2a8d93b-63c4-4b36-ae2f-45999492105f)

**Comment by hnyls2002** [comment]
This attribute error has been fixed by #560.
