### ISSUE TITLE
M2 Mac Attempted Installation: LLVM ERROR: Option 'pbqp' already exists!

### ISSUE THREAD

**Issue by velocity33** [sgl-project/sglang#537]
After building vLLM, Triton, and SGLang from source, upon attempting to run the following command. 

 python -m sglang.launch_server 

 I am met with the following error
 
LLVM ERROR: Option 'pbqp' already exists!
zsh: abort ...

Additionally, despite recieving the following message 

Successfully built sglang
Installing collected packages: sglang
Successfully installed sglang-0.1.17

When accessing SGLang within VSCode: 
sglang.srt.constrained cannot be found and 
set_default_backend also cannot be found. 
 
 
 Note: I am using vLLM 0.3.3

**Comment by zhyncs** [comment]
ref https://github.com/sgl-project/sglang/issues/508#issuecomment-2254328607
