### ISSUE TITLE
Will speculative decoding be supported?

### ISSUE THREAD

**Issue by arunpatala** [sgl-project/sglang#555]
Hi,

Thanks for this great repo. As the main branch has vllm 0.5.0, i was wondering if speculative decoding will be supported in sglang also. Right now i am getting the following error: 

    launch_server.py: error: unrecognized arguments: --speculative-model [ngram] --tensor-parallel-size 1 --num-speculative-tokens 3 --ngram-prompt-lookup-max 4 --use-v2-block-manager

i am using the main branch and installed from source.

**Comment by Ying1123** [comment]
Speculative decoding is not directly supported, since the attention modules are implemented in sglang rather than imported from vllm. But we have a draft version of speculative decoding already, which will be released soon hopefully.

**Comment by arunpatala** [comment]
thanks! looking forward to the release  :)

**Comment by Ying1123** [comment]
Also, our server has different arguments with vllm. For example, tensor parallelism should be turn on by "--tp-size 1" rather than "--tensor-parallel-size 1".

**Comment by chuangzhidan** [comment]
> Speculative decoding is not directly supported, since the attention modules are implemented in sglang rather than imported from vllm. But we have a draft version of speculative decoding already, which will be released soon hopefully.

 is speculative decoding  supported now?

**Comment by LeoLiuYan** [comment]
> > Speculative decoding is not directly supported, since the attention modules are implemented in sglang rather than imported from vllm. But we have a draft version of speculative decoding already, which will be released soon hopefully.不直接支持推测解码，因为注意力模块是在 sglang 中实现的，而不是从 vllm 导入的。但我们已经有了一个推测解码的草稿版本，希望很快就会发布。
> 
> is speculative decoding supported now?现在是否支持推测解码？

+1

**Comment by j-klesen** [comment]
+1

**Comment by arunpatala** [comment]
+1  Some reference implementation is done.
Eagle support is being added.

https://github.com/sgl-project/sglang/pull/270
https://github.com/sgl-project/sglang/pull/1498
