### ISSUE TITLE
[Feature Request] Enable working with Azure-OpenAI API (openai.AzureOpenAI())

### ISSUE THREAD

**Issue by snimu** [sgl-project/sglang#56]
Sglang looks great to me, but at my work, we use the Azure-OpenAI API. I don't see how to access this with sglang.

It would need two inputs in addition to the API-key, because at minimum I need to create the client like this:

```python
client = openai.AzureOpenAI(
    api_key="<your-api-key>",
    base_url="https://<your-project-name>.openai.azure.com/openai",
    api_version="<your-api-version>",  # for example "2023-05-15"
)
```

Also, for some reason the models are called "gpt-35-turbo" instead of "gpt-3.5-turbo" (missing dot); and I believe that you can call your models whatever you want. This should be supported, too.

If this already works somehow, I would appreciate an explicit mention in the `README.md`.

**Comment by merrymercy** [comment]
It should be very easy to support this. However, I do not have an azure account to test this.
Could you try to modify this part and see if you can contribute a PR to make it work?
https://github.com/sgl-project/sglang/blob/585eababa1ffbd68ad364681aff4ca1b7b2b1824/python/sglang/backend/openai.py#L51-L58


For the model names, please register the names of chat models here
https://github.com/sgl-project/sglang/blob/585eababa1ffbd68ad364681aff4ca1b7b2b1824/python/sglang/backend/openai.py#L33-L48

**Comment by snimu** [comment]
I will try it tomorrow, thank you :)

**Comment by snimu** [comment]
I'm a little confused by the `openai_completion`-function: 

https://github.com/sgl-project/sglang/blob/585eababa1ffbd68ad364681aff4ca1b7b2b1824/python/sglang/backend/openai.py#L205-L222

It looks to me like the `client` is simply given a prompt directly&mdash;`messages` is handed a `str`. I don't know if this is possible with OpenAI's own API, but for Azure, it throws an error. There, the `messages` has to be of the following shape:

```python
client.chat.completions.create(
    messages=[
        {"role": "system", "content": "..."},  # optional
        {"role": "user", "content": prompt},  # not optional
        {"role": "assistant", "content": "..."},  # optional
        ...
    ],
    ...
)
```

At least I cannot get it to work otherwise. How do you support multi-turn conversations? How do you support system prompts? And why does simply giving a `str` as the `messages` parameter work? 

Adding the `AzureOpenAI` class and supporting the additional arguments is easy, as is testing it, but if the fundamental communication as implemented by `sglang` doesn't work, then I unfortunately won't be able to successfully create this pull request. I simply don't have the time or knowledge of the codebase for it.

Is there something that I'm overlooking that makes this easier? Maybe you are setting some options in the background and I just have to set them for `AzureOpenAI` too?

**Comment by merrymercy** [comment]
The openai backend will choose to use chat completion or completion based on the model name.
Could you add the name of your model to this list?
https://github.com/sgl-project/sglang/blob/9076386d904171c7cc88ace681ca3ebbec2c71ea/python/sglang/backend/openai.py#L33-L48

Then `self.is_chat_model` will be True
https://github.com/sgl-project/sglang/blob/9076386d904171c7cc88ace681ca3ebbec2c71ea/python/sglang/backend/openai.py#L63-L64

Then we will use the correct multi-turn conversation input format to call
https://github.com/sgl-project/sglang/blob/9076386d904171c7cc88ace681ca3ebbec2c71ea/python/sglang/backend/openai.py#L220

**Comment by snimu** [comment]
I will look at it in more detail, but it may take a few more days until I have the time. Thanks for the response though :)

**Comment by merrymercy** [comment]
@snimu 
I added some examples for you.
Please try the latest main branch with these examples
https://github.com/sgl-project/sglang/blob/main/examples/quick_start/azure_openai_example_chat.py
