### ISSUE TITLE
Why using 16 bit dtype in memory pool state？

### ISSUE THREAD

**Issue by yileld** [sgl-project/sglang#570]
In **python/sglang/srt/memory_pool.py** TokenToKVPool
self.mem_state = torch.zeros((size,), dtype=torch.int16, device="cuda")
but ReqToTokenPool
self.mem_state = torch.ones((size,), dtype=torch.bool, device="cuda")
They are different, can I change all dtype into torch.bool？

**Comment by merrymercy** [comment]
It is a reference counter so we need to use int.
