### ISSUE TITLE
OpenAI ChatCompletionRequest max_tokens defaults to None causing error

### ISSUE THREAD

**Issue by brandonbiggs** [sgl-project/sglang#582]
I encountered a bug while using the sglang OpenAI API library. I have to specify max_tokens if using the `/v1/chat/completions` endpoint but not with the `/v1/completions` endpoint. I believe this is because of the default `max_tokens` value being set in `python/sglang/srt/openai_protocol.py`.

Default is 16 tokens https://github.com/sgl-project/sglang/blob/9380f50ff9cbc36afc1888c7a5b69f53c9a488f5/python/sglang/srt/openai_protocol.py#L31-L41

ChatCompletionRequest max_tokens defaults to None https://github.com/sgl-project/sglang/blob/9380f50ff9cbc36afc1888c7a5b69f53c9a488f5/python/sglang/srt/openai_protocol.py#L128-L137

Here's the end of the error:
```bash
  File "/usr/local/lib/python3.11/site-packages/sglang/srt/sampling_params.py", line 66, in verify
    if self.max_new_tokens < 0:
       ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```
This can be fixed by setting a default or checking if max_tokens is None and handling it, I just wasn't sure where the developers would want to do this.

**Comment by merrymercy** [comment]
@brandonbiggs Thanks for reporting this. Fixed by #605

**Comment by xiaguan** [comment]
Is this the same issue popping up again? `max_new_tokens` appears to be None in some cases, causing a TypeError in `schedule_batch.py`.

In `protocol.py`
```
class ChatCompletionRequest(BaseModel):
    # Ordered by official OpenAI API documentation
    # https://platform.openai.com/docs/api-reference/chat/create
    messages: List[ChatCompletionMessageParam]
    model: str
    frequency_penalty: float = 0.0
    logit_bias: Optional[Dict[str, float]] = None
    logprobs: bool = False
    top_logprobs: Optional[int] = None
    max_tokens: Optional[int] = None
```
Then in `adapter.py` `v1_chat_generate_request`
```
        sampling_params = {
            "temperature": request.temperature,
            "max_new_tokens": request.max_tokens,
            "min_new_tokens": request.min_tokens,
```

Finally, in `schedule_batch.py` `adjust_max_prefix_ids`
```
        if self.sampling_params.max_new_tokens > 0:
            # Need at least one token to compute logits
            max_prefix_len = min(max_prefix_len, input_len - 1)
```

The error occurs in `schedule_batch.py` within `adjust_max_prefix_ids`:
```
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by lisp2025** [comment]
sglang v052rc2 ,the same error

**Comment by feeltheagi** [comment]
i see this issue happening again.

**Comment by Capricornsong** [comment]
same here, happens again :(
