### ISSUE TITLE
sglang.launch_server raise "POST /v1/chat/completions HTTP/1.1" 404 Not Found

### ISSUE THREAD

**Issue by songkq** [sgl-project/sglang#59]

**Comment by comaniac** [comment]
Can you provide more details?

**Comment by merrymercy** [comment]
@songkq Are you using the pip version? This endpoint is recently added so please try the latest main branch

**Comment by songkq** [comment]
@merrymercy  Yeah. I'll try the main branch.

**Comment by songkq** [comment]
@comaniac @merrymercy Thanks. It works well with main branch.
Do you have plan to support INT8-Weight-Only inference?

**Comment by merrymercy** [comment]
The pip version has also been updated to support ChatCompletion.
We support AWQ quantization (4-bit, weight only). What specific quantization method do you want?
Since the original question has been addressed. Let us open a new issue for new requests.
