### ISSUE TITLE
[Bug?] gen() without max_token parameter is limited to 16 tokens long by default.

### ISSUE THREAD

**Issue by objnf-dev** [sgl-project/sglang#590]
In functions wrapped by `@sglang.function`, `sglang.gen()` without `max_token=` parameter will generate less than 16 tokens by default, which is defined in `SglFunction.run()`:

```python3
def run(
        self,
        *args,
        max_new_tokens: int = 16,
        ...
):
```

16 is too short for most situations and may produce unexpected results, such as incomplete JSON generations.

May be related: #211 #360

**Comment by merrymercy** [comment]
This is the default argument. Could you send a PR to make the default argument larger?
