### ISSUE TITLE
Slow import

### ISSUE THREAD

**Issue by bgyoon** [sgl-project/sglang#606]
It's rather a minor issue.

Since the addition of litellm, `import sglang` takes 2.5s(up from .7s without it) on my machine, in addition to complaining about `http://` missing in my proxy env variable.(as reported in https://github.com/sgl-project/sglang/issues/521)

```
$ time python -c 'import sglang'

real    0m2.494s
user    0m2.629s
sys     0m5.415s

$ pip uninstall litellm
Found existing installation: litellm 1.41.15
  Successfully uninstalled litellm-1.41.15

$ time python -c 'import sglang'
real    0m0.704s
user    0m1.483s
sys     0m5.513s
```

It could be fixed by uninstalling litellm, but it would be nicer if I don't have to manually uninstall packages I don't use to make the import faster.

Also according to a quick profiling, I think importing anthropic.py and openai.py is also taking most of the 0.7 seconds. importing them on demand would further speed up `import sglang`
<img width="851" alt="image" src="https://github.com/sgl-project/sglang/assets/8525211/5f817a60-ee6f-4c80-8fa5-30c44a9ec5de">

**Comment by merrymercy** [comment]
Nice catch! Could you contribute a PR to fix this?
