### ISSUE TITLE
select() on first assistant token broken (in different ways in Mistral and Llama). Likely tokenization issue.

### ISSUE THREAD

**Issue by max99x** [sgl-project/sglang#608]
Below is simple code with the output, showing that Llama and Mistral choose a clearly nonsensical first token in `select()` depending on whether the assistant message contains a leading space, but each in the opposite way.

```
@sglang.function
def selected(s):
    s += sglang.user('Hi!')
    s += sglang.assistant_begin()
    s += sglang.gen('var', choices=('Hello', 'Goodbye', '^*B^&A'))
    s += sglang.assistant_end()
print(selected.run(backend=runtime).text())
# Mistral: [INST] Hi! [/INST]^*B^&A </s><s>
#   LLAMA: [INST] Hi! [/INST]Hello </s><s>

@sglang.function
def selected_space(s):
    s += sglang.user('Hi!')
    s += sglang.assistant_begin()
    s += ' '
    s += sglang.gen('var', choices=('Hello', 'Goodbye', '^*B^&A'))
    s += sglang.assistant_end()
print(selected_space.run(backend=runtime).text())
# Mistral: [INST] Hi! [/INST] Hello </s><s>
#   LLAMA: [INST] Hi! [/INST] ^*B^&A </s><s>

@sglang.function
def freeform(s):
    s += sglang.user('Hi!')
    s += sglang.assistant_begin()
    s += sglang.gen('var', max_tokens=3)
    s += sglang.assistant_end()
print(freeform.run(backend=runtime).text())
# Mistral: [INST] Hi! [/INST] Hello! How </s><s>
#   LLAMA: [INST] Hi! [/INST]  Hello! </s><s>

@sglang.function
def freeformp_space(s):
    s += sglang.user('Hi!')
    s += sglang.assistant_begin()
    s += ' '
    s += sglang.gen('var', max_tokens=3)
    s += sglang.assistant_end()
print(freeformp_space.run(backend=runtime).text())
# Mistral: [INST] Hi! [/INST] Hello! How </s><s>
#   LLAMA: [INST] Hi! [/INST]  Hello! It </s><s>
```

**Comment by binarycrayon** [comment]
subscribing, seeing the same issue.

**Comment by AidanCooper** [comment]
Try inspecting the logprobs with `selected.get_meta_info("var")`. It looks like it could be a similar issue as #523. "Hello" and "Goodbye" will be one or two tokens, whereas "^*B^&A" is probably six, which may result in a lower normalised score even though it's clearly a nonsensical response.

The reason the leading space makes a difference is because it's included in the normalised logprob calculation, and/or it alters the tokenisation boundaries of the choices (for token healing purposes).

**Comment by max99x** [comment]
Yup, you're right, @AidanCooper! `decode_token_logprobs` looks reasonable, but `normalized_prompt_logprobs` is skewed. FWIW, I've switched away from using `select()`/`choices` last week after reading the issue you linked, and just do the greedy thing with regex (when possible; sometimes I have dynamic choices, which makes regex unworkable due to FSM generation time). Would definitely appreciate alternative normalization schemata, though I haven't thought through any alternative better than greedy sampling.
