### ISSUE TITLE
Lora test

### ISSUE THREAD

**Issue by nivibilla** [sgl-project/sglang#66]
Hi,

I saw that there is a lora dev branch. is it possible to test this already? Or is it still WIP. Asking as ive been asking for s-lora in vllm for like months now and s-lora being on your roadmap is very exciting.

Thanks!

**Comment by Ying1123** [comment]
@nivibilla Thanks for your interest! It is WIP. You may expect it to be ready for test in 2 weeks.

**Comment by nivibilla** [comment]
Great thanks! Looking forward to it.

**Comment by lukashelff** [comment]
hey, since quite some time has already passed i wanted to ask when we can expect the merge
