### ISSUE TITLE
[Feature] How does sglang perform on diffusion models

### ISSUE THREAD

**Issue by songh11** [sgl-project/sglang#738]
### Motivation

I wonder if supporting sglang is helpful for the diffusion model, such as stable diffusion.

**Comment by zhyncs** [comment]
Hi @songh11 Thank you for your attention, the stable diffusion model is not currently supported.

**Comment by songh11** [comment]
> Hi @songh11 Thank you for your attention, the stable diffusion model is not currently supported.

Thank you for your reply. That's a pity
