### ISSUE TITLE
Continues batch technical for different length prompt

### ISSUE THREAD

**Issue by Arcmoon-Hu** [sgl-project/sglang#74]
Suppose model's max-model-length is 8096, and there is two requests, one prompt length is 8, another is 10. And how concat them, pad them to 8096 or pad them to 10 or truncate them to 8.
I feel you will pad them to 16. But I don't seek the code. Can you tell me the location?
Thanks.

**Comment by hnyls2002** [comment]
We have a memory pool to manage the tokens automatically. Two requests with 8 tokens and 10 tokens would be put into the memory pool. When calculating attention scores, a two-level index mechanism would be used for indexing these tokens.

Here is the related code https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/memory_pool.py

If you want to see how we index the tokens in the memory pool, here is the triton kernel doing this https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/layers/context_flashattention_nopad.py

**Comment by Arcmoon-Hu** [comment]
Interesting, I will read this part of the code. Thanks !

**Comment by merrymercy** [comment]
No padding. 18 tokens will be used for storing the prompts.

**Comment by Arcmoon-Hu** [comment]
Ok, I see
