### ISSUE TITLE
Initialization failed. warmup error: 

### ISSUE THREAD

**Issue by bravelll** [sgl-project/sglang#744]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

I execute :python -m sglang.launch_server --model-path Qwen/Qwen2-7B-Instruct  --tp 2 --mem-fraction-static 0.7  --enable-p2p-check --host 0.0.0.0 --port 8000    follow error:
[gpu_id=0] Load weight end. type=Qwen2ForCausalLM, dtype=torch.bfloat16, avail mem=15.61 GB
[gpu_id=1] Load weight end. type=Qwen2ForCausalLM, dtype=torch.bfloat16, avail mem=15.95 GB
[gpu_id=0] Memory pool end. avail mem=6.12 GB
[gpu_id=1] Memory pool end. avail mem=6.46 GB
[gpu_id=1] Capture cuda graph begin. This can take up to several minutes.
[gpu_id=0] Capture cuda graph begin. This can take up to several minutes.
[gpu_id=0] max_total_num_tokens=328021, max_prefill_tokens=16384, max_running_requests=5124, context_len=32768
[gpu_id=1] max_total_num_tokens=328021, max_prefill_tokens=16384, max_running_requests=5124, context_len=32768
INFO:     Started server process [1802867]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
Initialization failed. warmup error: 
Exception in thread Thread-1 (_wait_and_warmup):
Traceback (most recent call last):
  File "/u01/liuys/anaconda3/envs/sglang-env/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/u01/liuys/anaconda3/envs/sglang-env/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/u01/liuys/anaconda3/envs/sglang-env/lib/python3.10/site-packages/sglang/srt/server.py", line 356, in _wait_and_warmup
    raise e
  File "/u01/liuys/anaconda3/envs/sglang-env/lib/python3.10/site-packages/sglang/srt/server.py", line 351, in _wait_and_warmup
    assert res.status_code == 200
AssertionError

### Reproduction

I execute :python -m sglang.launch_server --model-path Qwen/Qwen2-7B-Instruct  --tp 2 --mem-fraction-static 0.7  --enable-p2p-check --host 0.0.0.0 --port 8000 

### Environment

```Shell
rtx3090
```

**Comment by merrymercy** [comment]
The same command works on my machines. Could you help us check the details of the error by inspecting the actual error here?

https://github.com/sgl-project/sglang/blob/0736b270202696b8f865e2915aadc36d3d51811b/python/sglang/srt/server.py#L337-L356

**Comment by atanikan** [comment]
I see the same error. I am running on Nvidia A100s.

(sglang0.2.5) [atanikanti@sophia-gpu-01 sglang]$ python -m sglang.launch_server --model-path meta-llama/Meta-Llama-3-8B-Instruct --port 30000 --tp 2
Fail to set RLIMIT_NOFILE: current limit exceeds maximum limit
server_args=ServerArgs(model_path='meta-llama/Meta-Llama-3-8B-Instruct', tokenizer_path='meta-llama/Meta-Llama-3-8B-Instruct', tokenizer_mode='auto', load_format='auto', dtype='auto', trust_remote_code=False, context_length=None, quantization=None, chat_template=None, host='127.0.0.1', port=30000, additional_ports=[30001, 30002, 30003, 30004], mem_fraction_static=0.88, max_prefill_tokens=None, max_running_requests=None, max_num_reqs=None, schedule_heuristic='lpm', schedule_conservativeness=1.0, tp_size=2, stream_interval=1, random_seed=203835611, log_level='info', log_level_http=None, log_requests=False, show_time_cost=False, api_key='', file_storage_pth='SGlang_storage', dp_size=1, load_balance_method='round_robin', chunked_prefill_size=1073741824, disable_flashinfer=False, disable_flashinfer_sampling=False, disable_radix_cache=False, disable_regex_jump_forward=False, disable_cuda_graph=False, disable_disk_cache=False, enable_torch_compile=False, enable_p2p_check=False, attention_reduce_in_fp32=False, efficient_weight_load=False, nccl_init_addr=None, nnodes=1, node_rank=None)
[gpu=0] Init nccl begin.
[gpu=1] Init nccl begin.
[gpu=0] Load weight begin. avail mem=37.66 GB
[gpu=1] Load weight begin. avail mem=37.66 GB
INFO 07-29 22:23:16 weight_utils.py:223] Using model weights format ['*.safetensors']
INFO 07-29 22:23:17 weight_utils.py:223] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:01<00:05,  1.86s/it]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:02<00:02,  1.14s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:04<00:01,  1.60s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:07<00:00,  1.96s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:07<00:00,  1.79s/it]

[gpu=1] Load weight end. type=LlamaForCausalLM, dtype=torch.bfloat16, avail mem=30.18 GB
[gpu=0] Load weight end. type=LlamaForCausalLM, dtype=torch.bfloat16, avail mem=30.18 GB
[gpu=1] Memory pool end. avail mem=3.75 GB
[gpu=0] Memory pool end. avail mem=3.75 GB
[gpu=0] Capture cuda graph begin. This can take up to several minutes.
[gpu=1] Capture cuda graph begin. This can take up to several minutes.
INFO 07-29 22:23:30 custom_all_reduce.py:219] Registering 1235 cuda graph addresses
INFO 07-29 22:23:30 custom_all_reduce.py:219] Registering 1235 cuda graph addresses
[gpu=1] max_total_num_tokens=419360, max_prefill_tokens=16384, max_running_requests=26209, context_len=8192
[gpu=0] max_total_num_tokens=419360, max_prefill_tokens=16384, max_running_requests=26209, context_len=8192
INFO:     Started server process [3961985]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:30000 (Press CTRL+C to quit)
Initialization failed. warmup error: 
Exception in thread Thread-1 (_wait_and_warmup):
Traceback (most recent call last):
  File "/grand/datascience/atanikanti/envs/sglang0.2.5/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/grand/datascience/atanikanti/envs/sglang0.2.5/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/lus/grand/projects/datascience/atanikanti/llm-inference-service/sglang/python/sglang/srt/server.py", line 409, in _wait_and_warmup
    raise e
  File "/lus/grand/projects/datascience/atanikanti/llm-inference-service/sglang/python/sglang/srt/server.py", line 404, in _wait_and_warmup
    assert res.status_code == 200
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by jyf111** [comment]
I meet the same error:
```
Initialization failed. warmup error: Traceback (most recent call last):
  File "/data/miniconda3/envs/env-3.9.2/lib/python3.9/site-packages/sglang/srt/server.py", line 393, in _wait_and_warmup
    assert res.status_code == 200, f"{res}"
AssertionError: <Response [403]>
```

**Comment by Xiangxiangzhu** [comment]
| encountered the same error, which seems to stem from the server being unreachable at http://0.0.0.0:30000/, particularly when using a proxy.
`res = requests.get(url + "/get_model_info", timeout=5, headers=headers)`
I resolved this issue by adding the following commands:
`unset http_proxy
unset https_proxy`

**Comment by Anthonyfhd** [comment]
> | encountered the same error, which seems to stem from the server being unreachable at http://0.0.0.0:30000/, particularly when using a proxy. `res = requests.get(url + "/get_model_info", timeout=5, headers=headers)` I resolved this issue by adding the following commands: `unset http_proxy unset https_proxy`

yes,i solve this problem

**Comment by xihuai18** [comment]
But if need a proxy to access huggingface, how to fix this problem?

**Comment by slchenchn** [comment]
> | encountered the same error, which seems to stem from the server being unreachable at http://0.0.0.0:30000/, particularly when using a proxy. `res = requests.get(url + "/get_model_info", timeout=5, headers=headers)` I resolved this issue by adding the following commands: `unset http_proxy unset https_proxy`

I unset the http_proxy and https_proxy, but the error persists.

**Comment by jinbagi** [comment]
Same error

**Comment by fishiu** [comment]
> > | encountered the same error, which seems to stem from the server being unreachable at http://0.0.0.0:30000/, particularly when using a proxy. `res = requests.get(url + "/get_model_info", timeout=5, headers=headers)` I resolved this issue by adding the following commands: `unset http_proxy unset https_proxy`
> 
> I unset the http_proxy and https_proxy, but the error persists.

`Unset` only works for the current shell, the proxy env vars are still possible to be caught in the process by `request`. It works for me to directly modify the http_server.py code to prevent `request` using proxy.
