### ISSUE TITLE
ROCM

### ISSUE THREAD

**Issue by BasDiaz** [sgl-project/sglang#750]
Hi! Is there a way to install sglang in rocm devices?

**Comment by zhyncs** [comment]
Hi @BasDiaz thank you for your interest. Currently, only NVIDIA GPU sm80+ is supported.

**Comment by githust66** [comment]
> Hi @BasDiaz thank you for your interest. Currently, only NVIDIA GPU sm80+ is supported.

Hi,   support AMD GPU now? I found that there are many questions based on ROCM in issue.
