### ISSUE TITLE
[Feature] Frontend: be able to run generate super long text

### ISSUE THREAD

**Issue by xianbaoqian** [sgl-project/sglang#759]
### Motivation

Similar to https://stackoverflow.com/questions/73113552/open-ai-generate-longer-text-with-gpt-3

I want to be able to generate super long text, longer than what the API supported. Is it a way to achieve that in the frontend? thx

**Comment by min-xu-et** [comment]
I don't know why is this a sglang issue. This seems to be related to the context window length of a given model

**Comment by xianbaoqian** [comment]
Not really. Say that OpenAI API can only generate 4096 tokens in the output (meaning that they stop the generation after that even the model can handle much longer context length) and I want to generate the very long output, what I need to do is to issue multiple requests to continue the generation.

example:

First query
Input:
user: INSTRUCTION
Output:
assistant: RESPONSE_1


RESPONSE_1 is truncated so going to issue the second query
Input:
user: INSTRUCTION
assistant: RESPONSE_1
Output:
assistant: RESPONSE_2

etc.

Is there a way to do that in the frontend? thx
