### ISSUE TITLE
[Bug]ImportError: cannot import name 'top_k_top_p_sampling_from_probs' from 'flashinfer.sampling' 

### ISSUE THREAD

**Issue by lonngxiang** [sgl-project/sglang#764]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

python -m sglang.launch_server --model-path /ai/qwen2-7b --port 30000
error:
Traceback (most recent call last):
  File "/home/anaconda3/envs/llm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/anaconda3/envs/llm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/envs/llm/lib/python3.10/site-packages/sglang/launch_server.py", line 5, in <module>
    from sglang.srt.server import launch_server
  File "/home/anaconda3/envs/llm/lib/python3.10/site-packages/sglang/srt/server.py", line 32, in <module>
    from sglang.srt.managers.controller.manager_multi import (
  File "/home/anaconda3/envs/llm/lib/python3.10/site-packages/sglang/srt/managers/controller/manager_multi.py", line 15, in <module>
    from sglang.srt.managers.controller.manager_single import (
  File "/home/anaconda3/envs/llm/lib/python3.10/site-packages/sglang/srt/managers/controller/manager_single.py", line 10, in <module>
    from sglang.srt.managers.controller.tp_worker import (
  File "/home/anaconda3/envs/llm/lib/python3.10/site-packages/sglang/srt/managers/controller/tp_worker.py", line 17, in <module>
    from sglang.srt.managers.controller.infer_batch import (
  File "/home/anaconda3/envs/llm/lib/python3.10/site-packages/sglang/srt/managers/controller/infer_batch.py", line 10, in <module>
    from flashinfer.sampling import top_k_top_p_sampling_from_probs
ImportError: cannot import name 'top_k_top_p_sampling_from_probs' from 'flashinfer.sampling' (/home/anaconda3/envs/llm/lib/python3.10/site-packages/flashinfer/sampling.py)

### Reproduction

qwen2

### Environment

```Shell
python3 -m sglang.check_env
Python: 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:24:10) [GCC 9.4.0]
CUDA available: True
GPU 0,1,2: NVIDIA GeForce RTX 4090
CUDA_HOME: /usr/local/cuda-12.2
NVCC: Cuda compilation tools, release 12.2, V12.2.91
CUDA Driver Version: 550.78
550.78
550.78
PyTorch: 2.3.1+cu121
sglang: 0.2.5
flashinfer: 0.0.8+cu121torch2.3
requests: 2.32.3
tqdm: 4.66.4
numpy: 1.26.3
aiohttp: 3.9.5
fastapi: 0.111.0
hf_transfer: 0.1.8
huggingface_hub: 0.23.4
interegular: 0.3.3
packaging: 23.2
pillow: Module Not Found
psutil: 5.9.8
pydantic: 2.7.0
uvicorn: 0.29.0
uvloop: 0.19.0
zmq: 26.0.3
vllm: 0.5.3.post1
openai: 1.30.1
anthropic: 0.31.2
NVIDIA Topology: 
        GPU0    GPU1    GPU2    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PHB     PHB     0-7     0               N/A
GPU1    PHB      X      PHB     0-7     0               N/A
GPU2    PHB     PHB      X      0-7     0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 1024
```

**Comment by zhyncs** [comment]
Please use the [latest FlashInfer version](https://github.com/flashinfer-ai/flashinfer/releases/tag/v0.1.1).

```bash
pip install flashinfer -i https://flashinfer.ai/whl/cu121/torch2.3/
```

**Comment by lonngxiang** [comment]
> Please use the [latest FlashInfer version](https://github.com/flashinfer-ai/flashinfer/releases/tag/v0.1.1).
> 
> ```shell
> pip install flashinfer -i https://flashinfer.ai/whl/cu121/torch2.3/
> ```

OK , i will try. Please update the installation documentation

```
pip install -U flashinfer -i https://flashinfer.ai/whl/cu121/torch2.3/
```

**Comment by zhyncs** [comment]
It is available in the [README](https://github.com/sgl-project/sglang?tab=readme-ov-file#method-1-with-pip).

**Comment by lonngxiang** [comment]
> It is available in the [README](https://github.com/sgl-project/sglang?tab=readme-ov-file#method-1-with-pip).

Since the above is already installed, running this sentence again will not update the latest version
