### ISSUE TITLE
[Bug]Why is the qwen2 openai interface accessing the streaming output incomplete 

### ISSUE THREAD

**Issue by lonngxiang** [sgl-project/sglang#765]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

```
from openai import OpenAI
# from openai._client import OpenAI
# Set OpenAI's API key and API base to use vLLM's API server.
openai_api_key = "EMPTY"
openai_api_base = "http://192****:30000/v1"

client = OpenAI(
    api_key=openai_api_key,
    base_url=openai_api_base,
)
## 流式回答
stream = client.chat.completions.create(
model="/ai/qwen2-7b",

messages=[{"role": "user", "content": "介绍广州"}],
stream=True,
)
for chunk in stream:
    if chunk.choices[0].delta.content is not None:
        # print(chunk.choices[0].delta.content)
        print(chunk.choices[0].delta.content, end="")


```
![image](https://github.com/user-attachments/assets/3e767dc1-7209-4d4c-9693-a68892295bf4)
![image](https://github.com/user-attachments/assets/3d8a2d44-1392-4378-a55e-3eddf7c541f1)

### Reproduction

 python -m sglang.launch_server --model-path /ai/qwen2-7b --host 0.0.0.0 --port 30000

### Environment

```Shell
Python: 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:24:10) [GCC 9.4.0]
CUDA available: True
GPU 0,1,2: NVIDIA GeForce RTX 4090
CUDA_HOME: /usr/local/cuda-12.2
NVCC: Cuda compilation tools, release 12.2, V12.2.91
CUDA Driver Version: 550.78
550.78
550.78
PyTorch: 2.3.1+cu121
sglang: 0.2.5
flashinfer: 0.1.1+cu121torch2.3
requests: 2.32.3
tqdm: 4.66.4
numpy: 1.26.3
aiohttp: 3.9.5
fastapi: 0.111.0
hf_transfer: 0.1.8
huggingface_hub: 0.23.4
interegular: 0.3.3
packaging: 23.2
pillow: Module Not Found
psutil: 5.9.8
pydantic: 2.7.0
uvicorn: 0.29.0
uvloop: 0.19.0
zmq: 26.0.3
vllm: 0.5.3.post1
openai: 1.30.1
anthropic: 0.31.2
```

**Comment by lonngxiang** [comment]
Increase the context_length parameter setting by 10000, or the answer is short to 10 words
![image](https://github.com/user-attachments/assets/3b8556f8-7928-493e-9dd1-9c9df15dadd1)

**Comment by lonngxiang** [comment]
context_length parameter  does not work

**Comment by hnyls2002** [comment]
<img width="1430" alt="image" src="https://github.com/user-attachments/assets/cda73d90-1572-4d39-8435-cad40e5ecbe4">

```
以下是关于广州的介绍：

广州是中国南方的重要城市，位于广东省中部，珠江三角洲东部。这座城市的历史可以追溯到公元前214年，当时秦朝在此建立了番禺县。广州在中国历史上一直是重要贸易港口，曾经是海上丝绸之路的重要节点。

广州是中国华南地区的经济、文化、科技和教育中心。它是全国最大的城市之一，也是中国重要的交通枢纽，拥有多个国际机场、港口和高速公路。广州还是著名的旅游城市，拥有许多历史古迹和% 
```
@lonngxiang Hi, this is not the `context_length` parameter that decides the output len. You should set the `max_token` in the openai calling function. I suppose the default max token number is minimal.

**Comment by lonngxiang** [comment]
> <img alt="image" width="1430" src="https://private-user-images.githubusercontent.com/95566987/352707772-cda73d90-1572-4d39-8435-cad40e5ecbe4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjY2MzgsIm5iZiI6MTcyMjA2NjMzOCwicGF0aCI6Ii85NTU2Njk4Ny8zNTI3MDc3NzItY2RhNzNkOTAtMTU3Mi00ZDM5LTg0MzUtY2FkNDBlNWVjYmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDA3NDUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3OGI3OWI0NDBhNDhmNjA4YWIwMTUyYWFjN2NhMWIzMDIxMDRlNGNmNmM2NjcyMGI4NjZhMzFhMmM4ZjE0NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RlRKL7hEMISoQU-qgnXVu4xvbrYzgGaXxRcuMY2SAuk">
> ```
> 以下是关于广州的介绍：
> 
> 广州是中国南方的重要城市，位于广东省中部，珠江三角洲东部。这座城市的历史可以追溯到公元前214年，当时秦朝在此建立了番禺县。广州在中国历史上一直是重要贸易港口，曾经是海上丝绸之路的重要节点。
> 
> 广州是中国华南地区的经济、文化、科技和教育中心。它是全国最大的城市之一，也是中国重要的交通枢纽，拥有多个国际机场、港口和高速公路。广州还是著名的旅游城市，拥有许多历史古迹和% 
> ```
> 
> @lonngxiang Hi, this is not the `context_length` parameter that decides the output len. You should set the `max_token` in the openai calling function. I suppose the default max token number is minimal.

Look at the source code seems to have no default value for this parameter, here using vllm to perform qwen2 here do not specify it


![image](https://github.com/user-attachments/assets/50072685-f78c-41fe-8ec3-46a8092ef6a7)

**Comment by merrymercy** [comment]
Should be fixed by https://github.com/sgl-project/sglang/pull/766
