### ISSUE TITLE
OPTIONS method is not supported when using sglang with the nextchat client

### ISSUE THREAD

**Issue by jjiwei** [sgl-project/sglang#768]
I am using qwen1.5 model, how to use openai compatible api interface in sglang to use
Launch command: python -m sglang.launch_server --model-path Qwen1.5-72B-Chat-GPTQ-Int4 --tp 2 --enable-p2p-check --port 8000 --host 0.0.0.0
Using openai compatible api reported this error, "OPTIONS /v1/chat/completions HTTP/1.1" 405 Method Not Allowed.
thx

**Comment by merrymercy** [comment]
1. Can you successfully run the example in the README? https://github.com/sgl-project/sglang?tab=readme-ov-file#openai-compatible-api
2. Can you share your code for sending the OAI requests?

**Comment by jjiwei** [comment]
I'm using the nextchat client to try to connect to sglang's OpenAI-compatible api interface, and I'm using the project's template to get through!
thx
<img width="1160" alt="image" src="https://github.com/user-attachments/assets/efb50eb3-9019-4995-80a5-c153fe18bc2c">
<img width="1124" alt="image" src="https://github.com/user-attachments/assets/9a8b65ce-e094-46d8-b3cc-b24db10486e0">

**Comment by merrymercy** [comment]
From the log, you can see `POST` method is supported, but `OPTIONS` method is not supported.
I am not sure why the nextchat client uses this endpoint.
You can either
1. Modify nextchat client to not using `OPTIONS` method.
2. Help us add the support for OPTIONS here. https://github.com/sgl-project/sglang/blob/f95e6617576ee30597ecf1d5de7e6feada70394d/python/sglang/srt/server.py#L133-L140. You can lean how to do this from ChatGPT: https://chatgpt.com/share/6d9e0db7-4c7c-47b1-9a85-ad05b5b43890

**Comment by wizd** [comment]
Easy walk around by adding a proxy: https://github.com/songquanpeng/one-api

**Comment by zhyncs** [comment]
May you try the latest release? Thanks! ref https://github.com/sgl-project/sglang/pull/1373
