### ISSUE TITLE
Sketch guided constrained deciding for black box LLMs

### ISSUE THREAD

**Issue by AriMKatz** [sgl-project/sglang#78]
https://twitter.com/SaiboGeng/status/1749490603111387643?t=MRfYngCpJRB7zfZCpW43MA&s=19

Any thoughts about adding that?

**Comment by merrymercy** [comment]
This sounds very interesting. You can already implement the low-level logic with the current sglang.
When this method becomes stable and mainstream, we can provide it as a default option in sglang.

**Comment by AriMKatz** [comment]
Cool @merrymercy. Also this [tweet](https://twitter.com/SaiboGeng/status/1749492475427746051) mentions that LMQL uses OAI's logit-bias API. is that something else that may be useful? I can open an issue[](url)
