### ISSUE TITLE
[Feature] Add check_health API

### ISSUE THREAD

**Issue by Xu-Chen** [sgl-project/sglang#801]
### Motivation

When deploying on k8s, it is necessary to check the service status. Hope to add the check_health API like vllm.

### Related resources

https://github.com/vllm-project/vllm/blob/7cbd9ec7a9bfd4952ad522355b6bbb8e82b54fc9/vllm/executor/executor_base.py#L121

**Comment by zhyncs** [comment]
ref https://github.com/sgl-project/sglang/blob/7cd4f244a42178d0cdfb6a81156f38e87a7d92cd/python/sglang/srt/server.py#L84-L87

**Comment by Xu-Chen** [comment]
> ref
> 
> https://github.com/sgl-project/sglang/blob/7cd4f244a42178d0cdfb6a81156f38e87a7d92cd/python/sglang/srt/server.py#L84-L87

Thank you
