### ISSUE TITLE
[Feature] RadixCache: remove recursive logic

### ISSUE THREAD

**Issue by hnyls2002** [sgl-project/sglang#813]
### Motivation

When the chunked prefill size is too small and the prefill length is too long, python would reach maximum recursion depth in the radix cache.

Same as proposed in #154

**Comment by jon-chuang** [comment]
Hello @hnyls2002 please assign this to me

**Comment by jon-chuang** [comment]
I'm just wondering, why did you choose to Implement radix trie in python rather than use off the shelf library?

**Comment by lwing1966** [comment]
##RadixCache: remove recursive logic##

how can i  do?
