### ISSUE TITLE
[Bug] response = client.completions.create( 	model="default", 	prompt="The capital of France is", 	temperature=0, 	max_tokens=32, ) print(response) 如何在启动的时候指定服务名称 比如test_gpt,在请求的时候传入model="test_gpt"

### ISSUE THREAD

**Issue by mayu123mayu** [sgl-project/sglang#841]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

[Bug] response = client.completions.create( 	model="default", 	prompt="The capital of France is", 	temperature=0, 	max_tokens=32, ) print(response) 如何在启动的时候指定服务名称 比如test_gpt,在请求的时候传入model="test_gpt"

### Reproduction

[Bug] response = client.completions.create( 	model="default", 	prompt="The capital of France is", 	temperature=0, 	max_tokens=32, ) print(response) 如何在启动的时候指定服务名称 比如test_gpt,在请求的时候传入model="test_gpt"

### Environment

```Shell
[Bug] response = client.completions.create( 	model="default", 	prompt="The capital of France is", 	temperature=0, 	max_tokens=32, ) print(response) 如何在启动的时候指定服务名称 比如test_gpt,在请求的时候传入model="test_gpt"
```

**Comment by Ying1123** [comment]
see https://github.com/sgl-project/sglang/pull/749

**Comment by Ying1123** [comment]
add `--served-model-name your_model_name` when you launch the server
