### ISSUE TITLE
[Feature] Add sampling parameters set twice warning.

### ISSUE THREAD

**Issue by DouHappy** [sgl-project/sglang#846]
### Motivation

```python
@sgl.function
def qwen_generate(s, prompt):
    prompt = '<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n'\
        +prompt+'<|im_end|>\n<|im_start|>assistant\n'
    s += prompt
    s += sgl.gen(
        name='output',
        temperature=0,
        # max_tokens=2000,
    )

sgl.set_default_backend(sgl.RuntimeEndpoint("http://127.0.0.1:10100"))

outputs = qwen_generate.run_batch(
    [
        {
            'prompt':"Hello"
        }
    ],
    temperature=10,
    max_new_tokens=50,
)
print(outputs[0]['output'])
```

sgl.gen() and function.run_batch can both set sampling params. But the temperature=0 is finally set.
Can you add a warning if sampling parameters are set twice?

**Comment by hnyls2002** [comment]
@DouHappy The outer setting in `run_batch` is the default sampling parameters and you can still specify very requests sampling parameters in the decorated function through arguments (like the prompt you passed in).

You can just recognize the outer is default, then there is no confusion about it.

**Comment by DouHappy** [comment]
Thank you. I will close this issue.
