### ISSUE TITLE
There doesn't seem to be a wheel available for python312.

### ISSUE THREAD

**Issue by 17Reset** [sgl-project/sglang#849]
(llm_venv_sglang) xlab@xlab:/mnt/SGLang$ uv pip install flashinfer -i https://flashinfer.ai/whl/cu121/torch2.3/
  × No solution found when resolving dependencies:
  ╰─▶ Because only the following versions of flashinfer are available:
          flashinfer==0.0.4+cu121torch2.3
          flashinfer==0.0.5+cu121torch2.3
          flashinfer==0.0.6+cu121torch2.3
          flashinfer==0.0.7+cu121torch2.3
          flashinfer==0.0.8+cu121torch2.3
          flashinfer==0.0.9+cu121torch2.3
          flashinfer==0.1.0+cu121torch2.3
          flashinfer==0.1.1+cu121torch2.3
          flashinfer==0.1.2+cu121torch2.3
      and flashinfer==0.0.4+cu121torch2.3 has no wheels with a matching Python ABI tag, we can conclude that
      flashinfer<0.0.5+cu121torch2.3 cannot be used.
      And because flashinfer==0.0.5+cu121torch2.3 has no wheels with a matching Python ABI tag, we can conclude
      that flashinfer<0.0.6+cu121torch2.3 cannot be used.
      And because flashinfer==0.0.6+cu121torch2.3 has no wheels with a matching Python ABI tag and
      flashinfer==0.0.7+cu121torch2.3 has no wheels with a matching Python ABI tag, we can conclude that
      flashinfer<0.0.8+cu121torch2.3 cannot be used.
      And because flashinfer==0.0.8+cu121torch2.3 has no wheels with a matching Python ABI tag and
      flashinfer==0.0.9+cu121torch2.3 has no wheels with a matching Python ABI tag, we can conclude that
      flashinfer<0.1.0+cu121torch2.3 cannot be used.
      And because flashinfer==0.1.0+cu121torch2.3 has no wheels with a matching Python ABI tag and
      flashinfer==0.1.1+cu121torch2.3 has no wheels with a matching Python ABI tag, we can conclude that
      flashinfer<0.1.2+cu121torch2.3 cannot be used.
      And because flashinfer==0.1.2+cu121torch2.3 has no wheels with a matching Python ABI tag and you require
      flashinfer, we can conclude that the requirements are unsatisfiable.

**Comment by zhyncs** [comment]
Yes. ref https://github.com/flashinfer-ai/flashinfer/blob/main/.github/workflows/release_wheel.yml#L28

**Comment by zhyncs** [comment]
cc @yzh119

**Comment by zhyncs** [comment]
Hi @17Reset May you temporarily set up a Python 3.11 environment with conda for now? Thanks.

**Comment by 17Reset** [comment]
Ubuntu24.04 uses Python3.12 by default. I think we can add support for Python3.12 since Python3.13 is coming soon

**Comment by zhyncs** [comment]
Hi @17Reset Thanks for your advice. I checked the images currently provided by NVIDIA, and indeed there is support for Ubuntu 24.04 `nvidia/cuda:12.5.1-devel-ubuntu24.04`. SGLang is currently using the excellent [FlashInfer](https://github.com/flashinfer-ai/flashinfer), and we need to wait until FlashInfer adds support for Python 3.12 before supporting it on SGLang. cc @yzh119

**Comment by 17Reset** [comment]
Thanks

**Comment by yzh119** [comment]
We will release python 3.12 wheel starting from flashinfer 0.1.4
