### ISSUE TITLE
Can the stop tokens be retained? 

### ISSUE THREAD

**Issue by CSWellesSun** [sgl-project/sglang#85]
I set the stop token as `.`, but the output text will not include the stop token, so can the stop tokens be retained in the output?

request:
```bash
curl http://localhost:8081/generate \
  -H "Content-Type: application/json" \
  -d '{
    "text": "Once upon a time,",
    "sampling_params": {
      "max_new_tokens": 1024,
      "temperature": 0,
      "stop": ".",
    }
  }'
```

response:
```bash
{"text":" and in a land far, far away, there was a young girl named Lily","meta_info":{"prompt_tokens":6,"completion_tokens":18,"id":"fe8e78ca46ab4f4bb69842202201288c"}}
```

**Comment by merrymercy** [comment]
Can you add it by yourself in your script? Or do you have multiple stop strings?

**Comment by merrymercy** [comment]
The code for handling the stop str is here https://github.com/sgl-project/sglang/blob/9e037c822ccabaf593c0145a9d8377f177e22ff9/python/sglang/srt/managers/detokenizer_manager.py#L50-L52
You can try to hardcode for your case or you can contribute a PR to add an option.

**Comment by merrymercy** [comment]
@CSWellesSun You are welcome to try this new JSON decode feature on the main branch. We landed some additional optimizations to make it faster https://github.com/sgl-project/sglang/tree/main?tab=readme-ov-file#json-decoding
