### ISSUE TITLE
[Bug] can not run flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol

### ISSUE THREAD

**Issue by CSEEduanyu** [sgl-project/sglang#851]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

 /opt/conda/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

### Reproduction

A100 linux py310-torch231-cu121

### Environment

```Shell
A100 linux py310-torch231-cu121
```

**Comment by zhyncs** [comment]
May you try our latest docker? Thanks.

**Comment by jtmer** [comment]
I also met the same question:
```
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/cpp_extensions/__init__.py", line 6, in <module>
[rank0]:     from transformer_engine_extensions import *
[rank0]: ImportError: /usr/local/lib/python3.10/dist-packages/transformer_engine_extensions.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
```
I just followed the install commands:
```
# Use the stable v0.2.8 branch
git clone -b v0.2.8 https://github.com/sgl-project/sglang.git
cd sglang

pip install --upgrade pip
pip install -e "python[all]"

# Install FlashInfer CUDA kernels
pip install flashinfer -i https://flashinfer.ai/whl/cu121/torch2.3/
```
then run this command:**[I replaced the model path with my own]**
```
python -m sglang.bench_latency --model-path /path_to_my_local_model/llama3_8B_chat_self_play_wenxin --batch 32 --input-len 256 --output-len 32
```
then came the error.

**Environment**
```
A800 linux py310-torch231-cu122
```

**Comment by jtmer** [comment]
又换了个镜像（用的公司的开发机，换的镜像也不知道里面有啥），报错变成了：
```
ImportError: /usr/local/lib/python3.8/dist-packages/flash_attn_2_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

/home/m/S/sglang on release !4 ?12 > c++filt _ZN3c104cuda9SetDeviceEi
c10::cuda::SetDevice(int)
```

**Comment by jtmer** [comment]
> ### Checklist
> * [ ]  1. I have searched related issues but cannot get the expected help.
> * [ ]  2. The bug has not been fixed in the latest version.
> * [ ]  3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
> 
> ### Describe the bug
> /opt/conda/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
> 
> ### Reproduction
> A100 linux py310-torch231-cu121
> 
> ### Environment
> ```shell
> A100 linux py310-torch231-cu121
> ```

I solved the problem. Just update flash-attn to the latest version.

**Comment by zhyncs** [comment]
Hi @jtmer Thanks for your attempt and verification!
