### ISSUE TITLE
[Feature] plan to support medusa?

### ISSUE THREAD

**Issue by CSEEduanyu** [sgl-project/sglang#859]
### Motivation

plan to support medusa?

**Comment by zhyncs** [comment]
Speculative decoding support is on our roadmap. Currently, FlashInfer has implemented the corresponding kernel and made targeted optimizations, please stay tuned.

**Comment by CSEEduanyu** [comment]
https://github.com/sgl-project/sglang/pull/270/commits

**Comment by chuangzhidan** [comment]
> Speculative decoding support is on our roadmap. Currently, FlashInfer has implemented the corresponding kernel and made targeted optimizations, please stay tuned.

really looking for fast decoding methods like medusa,Speculative decoding, LOOKAHEAD DECODING and such

**Comment by vkc1vk** [comment]
Hi I was wondering Medusa will be supported with full tree attention or the Top-1 version currently available in vLLM? 

Thanks.
cc: @zhyncs  @merrymercy
