### ISSUE TITLE
Why changed images in Dockerfile?

### ISSUE THREAD

**Issue by lzcchl** [sgl-project/sglang#863]
Why did you change 
nvidia/cuda:12.4.1-devel-ubuntu22.04 (in v0.2.0)
to 
nvidia/cuda:12.1.1-devel-ubuntu22.04 (in v0.2.7)
in Dockerfile. 

Is there any bugs in 12.4.1 images? and you check no bugs in 12.1.1 ?

can I use 12.4.1 or 12.1.0 to replace 12.1.1 when build docker images? 
If you have already found bugs in the 12.4.1 image, then I'd better download the 12.1.1 image.

**Comment by zhyncs** [comment]
In fact, we support both. ref https://github.com/sgl-project/sglang/blob/c9bff5fcc80e3c5edad31d1998bf11cfc7781f57/.github/workflows/release-docker.yml#L17
