### ISSUE TITLE
RuntimeError: TopKTopPSamplingFromProbs failed with error code no kernel image is available for execution on the device  已杀死[Bug] 

### ISSUE THREAD

**Issue by mayu123mayu** [sgl-project/sglang#865]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

RuntimeError: TopKTopPSamplingFromProbs failed with error code no kernel image is available for execution on the device

已杀死

### Reproduction

RuntimeError: TopKTopPSamplingFromProbs failed with error code no kernel image is available for execution on the device

已杀死

### Environment

```Shell
RuntimeError: TopKTopPSamplingFromProbs failed with error code no kernel image is available for execution on the device

已杀死
```

**Comment by zhyncs** [comment]
Hi @mayu123mayu  please provide detailed information according to the checklist.

**Comment by zhyncs** [comment]
ref https://github.com/sgl-project/sglang/blob/main/.github/ISSUE_TEMPLATE/1-bug-report.yml

**Comment by Ying1123** [comment]
try adding `--disable-flash-sampling` to your server launch command.

**Comment by merrymercy** [comment]
should be fixed with the latest version.
