### ISSUE TITLE
 run llama 3.1 405B with multi node has tp server error [Bug] 

### ISSUE THREAD

**Issue by kinglion811** [sgl-project/sglang#868]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

I have two node,node1 and node2,every node eth set is
eth0 is the controller network
eth1 to eth8 is the GPU IB network,
I  run llama 3.1 405B by sglang,like that
<img width="1619" alt="image" src="https://github.com/user-attachments/assets/d0380369-074f-4afc-90e8-84b62ec7362d">
the error is
<img width="903" alt="image" src="https://github.com/user-attachments/assets/397ebfc9-1517-4d1a-82c2-86d5d47f9509">

### Reproduction

sglang:latest

### Environment

```Shell
two node,node1 and node2,every node eth set is
eth0 is the controller network
eth1 to eth8 is the GPU IB network
```

**Comment by zhyncs** [comment]
ref https://github.com/sgl-project/sglang?tab=readme-ov-file#run-llama-31-405b

**Comment by min-xu-et** [comment]
I have seen this error (gloo mesh connection failed) with vllm too. I think it is related to your network setup. I wasn't able to find a solution other than using a different set of machines. For me, using H100s from AWS didn't work but using A100s from AWS did work (with exact same OS software and vllm code).

You might want to specific GLOO_SOCKET_IFNAME to your nic interface but it didn't help for me. Other than that, you might want to disable all but the network interface you are using.

**Comment by min-xu-et** [comment]
In your case, perhaps gloo only needs eth0 since my understanding is that gloo is only used for some low bandwidth coordination between the nodes using a CPU process group (at least for vllm).

**Comment by kinglion811** [comment]
> In your case, perhaps gloo only needs eth0 since my understanding is that gloo is only used for some low bandwidth coordination between the nodes using a CPU process group (at least for vllm).



GLOO_SOCKET_IFNAME is set eth0(not roce and IB network)，there is no gloo error，
but if --nccl-init-addr    is set to eth1 ip，the error is
<img width="1851" alt="image" src="https://github.com/user-attachments/assets/2d2eb8d2-0adb-4579-b5ca-ce533b75506d">
if --nccl-init-addr is set to eth0‘s ip ，the error is
<img width="1874" alt="image" src="https://github.com/user-attachments/assets/1171ed82-3886-4348-992c-67c6d5f5e8ea">

the --nccl-init-addr is what？

**Comment by kinglion811** [comment]
> ref https://github.com/sgl-project/sglang?tab=readme-ov-file#run-llama-31-405b

that can't solve my question

**Comment by hrukalive** [comment]
Readme says GLOO, but you can also try to set `NCCL_SOCKET_IFNAME=<your interface name>` as well.

**Comment by db24** [comment]
I solved by running docker with args "--shm-size=1g --ulimit memlock=-1"
ref: https://help.aliyun.com/zh/egs/support/faq-1
I guess it not relevant to sglang, purely nccl issue
