### ISSUE TITLE
[Bug] Fail to build from Docker

### ISSUE THREAD

**Issue by jywangx** [sgl-project/sglang#885]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

Building from the Dockerfile, got gpg-key error like:

```
Err:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
```

while executing:

```
RUN echo 'tzdata tzdata/Areas select America' | debconf-set-selections \
    && echo 'tzdata tzdata/Zones/America select Los_Angeles' | debconf-set-selections \
    && apt-get update -y \
    && apt-get install -y ccache software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update -y \
    && apt-get install -y python${PYTHON_VERSION} python${PYTHON_VERSION}-dev python${PYTHON_VERSION}-venv python3-pip \
    && if [ "${PYTHON_VERSION}" != "3" ]; then update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1; fi \
    && python3 --version \
    && python3 -m pip --version \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean
```

It may due to [Cuda Repo Signing Key Change is causing package repo update failures](https://gitlab.com/nvidia/container-images/cuda/-/issues/158)

This problem could be fixed by chanaging the value of `FROM` in Dockerfile to `nvidia/cuda:${CUDA_VERSION}-devel-ubuntu20.04` (It's validated on my env and `CUDA_VERSION` is set to `12.2.2`)

### Reproduction

```
docker build --pull --network=host -t sglang0.28 .
```

### Environment

```Shell
Nothing
```

**Comment by Ying1123** [comment]
Our CI/CD machine can build it successfully. Can you check out the logs here and see whether they are helpful for your debugging?
https://github.com/sgl-project/sglang/actions/runs/10205918382/job/28237724517#step:4:1

**Comment by Ying1123** [comment]
@jywangx Could you check if the newest docker image fixed your problem? We have changed the base image to ubuntu 20.04 (#900)

**Comment by jywangx** [comment]
> @jywangx Could you check if the newest docker image fixed your problem? We have changed the base image to ubuntu 20.04 (#900)

Thanks it's ok now!
