### ISSUE TITLE
[Feature] Add alternative names for pp-size, tp-size, and dp-size

### ISSUE THREAD

**Issue by w013nad** [sgl-project/sglang#893]
### Motivation

Probably a bit immature but I just had a meeting with a coworker to explain the options for sglang. I really don't want to say `pp-size` at work again......

Can we modify the options to include pipeline-parallel-size, tensor-parallel-size, and data-parallel-size like vLLM do? We can still keep the old ones for back compatibility.

### Related resources

https://github.com/vllm-project/vllm/blob/main/vllm/engine/arg_utils.py

**Comment by zhyncs** [comment]
Make sense.

**Comment by merrymercy** [comment]
@w013nad Could you contribute a PR to fix this?

**Comment by yichuan-w** [comment]
@w013nad #941 supports that now
