### ISSUE TITLE
[Feature] Can we remove api-key authentication from the /health endpoint?

### ISSUE THREAD

**Issue by ucciicci** [sgl-project/sglang#901]
### Motivation

Currently, when the server is started with an api-key, the /health endpoint also requires the api-key for requests. 
Some cloud services' health check functions cannot set authentication information for requests, causing issues with deployment health checks. 
Is it possible to remove the authentication check from the /health endpoint?

For reference, in vllm, the /health endpoint does not require authentication.

**Comment by zhyncs** [comment]
You may set ‘EMPTY’.

**Comment by ucciicci** [comment]
Thank you for your response.

What I would like to achieve is to have api-key authentication for inference endpoints (e.g., /v1/completions), but allow the /health endpoint to respond with a 200 status without requiring authentication.

https://github.com/sgl-project/sglang/blob/001b0bdd089a626ada2ee217fdc59b4212f0b461/python/sglang/srt/server.py#L90
https://github.com/sgl-project/sglang/blob/001b0bdd089a626ada2ee217fdc59b4212f0b461/python/sglang/srt/utils.py#L545

**Comment by Ying1123** [comment]
Should be fixed by #917
