### ISSUE TITLE
[Feature] Add a flag for computing the prompt's logprobs or not.

### ISSUE THREAD

**Issue by hnyls2002** [sgl-project/sglang#902]
### Motivation

Mentioned in #852

**Comment by merrymercy** [comment]
@yichuan520030910320 Can you take on this? In most cases, when using the ChatCompletion API or using the Completion API with `echo=False`, only the output log probs are returned https://platform.openai.com/docs/api-reference/chat/create#chat-create-logprobs.

Currently, this is blocking us from using the chunked prefill feature for requests that require logprob. After we fix this, all chat completion requests can use the ChunkedPrefill feature. 
https://github.com/sgl-project/sglang/blob/e712837d389e307fe0a4d07d06a6a940695455d8/python/sglang/srt/managers/policy_scheduler.py#L178-L182

**Comment by hnyls2002** [comment]
When logprob is turned on, the start_len is set to 0 most of the time.

https://github.com/sgl-project/sglang/blob/43fbb6d919d9b6c07ab256a8ab04bc4d7462df66/python/sglang/srt/managers/io_struct.py#L79-L80

Because of this, the maximum prefix cache length would be zero. 

https://github.com/sgl-project/sglang/blob/43fbb6d919d9b6c07ab256a8ab04bc4d7462df66/python/sglang/srt/managers/schedule_batch.py#L180-L181

But most of the time we do not need to compute the logprobs of input part. So you can solve this by adding a new flag that indicates whether we should apply the start_len truncatenation. The default is False, but when using `select` or be set, apply the start_len to truncate it.
