### ISSUE TITLE
[Feature] Does sglang now support beam search

### ISSUE THREAD

**Issue by StevenZHB** [sgl-project/sglang#903]
### Motivation

Does sglang now support beam search? I tried using the 'best_of' parameter, but the output seems to be the same as if it wasn't used.

**Comment by zhyncs** [comment]
Currently not supported. Whether to support it in the future needs to be discussed. At present, other features and optimizations may have a higher priority. Thank you for your interest in SGLang. Please stay tuned, thanks.

**Comment by min-xu-et** [comment]
I agree it is a low priority. There are a lot of way to generate diverse output from LLMs and then select a good response. Unclear that beam search is a good approach anyway.
