### ISSUE TITLE
[Feature] Does SGLang support KV Cache reuse?

### ISSUE THREAD

**Issue by vnkc1** [sgl-project/sglang#906]
### Motivation

A key feature in TensorRT-LLM involves re-using KV cache based on prompt prefixes. Wondering if SGLang Runtime already supports or will support that in the future. Love this project, thanks!

### Related resources

https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/kv_cache_reuse.md

**Comment by min-xu-et** [comment]
I think sglang already supports "reuse" by match the longest matching prompt prefixes. It is probably better than TRT-LLM in that regard. The sglang paper should have more details.

The link you provided also mentioned about offloading to host memory. I don't think that is currently supported by sglang.

**Comment by Ying1123** [comment]
KV cache reuse is called RadixAttention in SGLang  (https://lmsys.org/blog/2024-01-17-sglang/)
It is turned on by default. During your prefill, you can actually see the cache hit rate in the log
```
[gpu=0] Prefill batch. #new-seq: 1, #new-token: 3, #cached-token: 3, cache hit rate: 23.08%, #running-req: 0, #queue-req: 0
```
