### ISSUE TITLE
[Feature] Google TPU Support

### ISSUE THREAD

**Issue by RonanKMcGovern** [sgl-project/sglang#919]
### Motivation

TPUs potentially provide a cheap serving option

### Related resources

vLLM does support TPUs: https://docs.vllm.ai/en/latest/getting_started/tpu-installation.html#installation-with-tpu

**Comment by zhyncs** [comment]
Hi @RonanKMcGovern Our main priority is still to first support NVIDIA GPUs at the **data center** level, such as **A100, L40s, H100**, etc. After that we may consider supporting AMD GPUs. We do not have the resources to support other hardware platforms in the short term. If you can contribute, we are very welcoming and would be very willing to help you review. Thanks!

**Comment by RonanKMcGovern** [comment]
Yeah that makes sense, thanks, Ronan

**Comment by zhyncs** [comment]
This issue is closed for now. If there are any further problems, please reopen. Thanks!

**Comment by miladm** [comment]
I'd love to discuss this further & explore ways to enable TPU on SGLang. @zhyncs
