### ISSUE TITLE
[Bug] 我想问一下支持qwen1.5-14B模型吗？

### ISSUE THREAD

**Issue by yawzhe** [sgl-project/sglang#930]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

[Bug] 我想问一下支持qwen1.5-14B模型吗？

### Reproduction

[Bug] 我想问一下支持qwen1.5-14B模型吗？

### Environment

```Shell
[Bug] 我想问一下支持qwen1.5-14B模型吗？
```

**Comment by Ying1123** [comment]
支持
