### ISSUE TITLE
how to use the finetuned mistral model for inference with sglang

### ISSUE THREAD

**Issue by pradeepdev-1995** [sgl-project/sglang#94]
how to use the finetuned mistral model for inference with sglang. 
Please share the code for this

**Comment by merrymercy** [comment]
For the official model, you can just use

```
python -m sglang.launch_server --model-path mistralai/Mistral-7B-Instruct-v0.2 --port 30000
```

and follow the usage https://github.com/sgl-project/sglang?tab=readme-ov-file#usage.

For your fine-tuned models, just replace `mistralai/Mistral-7B-Instruct-v0.2` with your model path

**Comment by pradeepdev-1995** [comment]
@merrymercy  Tried above  method to load a finetuned mistral model. but it raises the given error
```
 ImportError: /tmp/pip_packages/vllm/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15to_dtype_layout4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEEbbNS6_INS5_12MemoryFormatEEE
```
