### ISSUE TITLE
[Bug] Poor generation quality with Qwen2-57B-A14B-Instruct model

### ISSUE THREAD

**Issue by sighingnow** [sgl-project/sglang#943]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

We noticed poor generation quality with the [Qwen2-57B-A14B-Instruct](https://huggingface.co/Qwen/Qwen2-57B-A14B-Instruct) model (compared with vLLM). Here are some examples:

- prompt: `<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n请介绍一下杭州<|im_end|>\n<|im_start|>assistant\n<|im_start|>assistant\n`
- sampling params:
  - temperature: 0.7
  - top_k: 20
  - top_p: 0.8
  - repetition_penalty: 1.05
- vLLM outputs: `对不起，我之前误解了你的问题。作为一个AI语言模型，我没有个人经验或主观意见。以下是关于杭州市的一些基本信息：\n\n杭州市是中国浙江省的省会城市，位于中国东南部，是长江三角洲地区的重要城市之一。杭 州以其美丽的西湖而闻名于世，也是中国历史文化名城和重要的经济、文化中心。\n\n杭州市拥有丰富的旅游资源，除了西湖外，还有灵隐寺、千岛湖、西溪湿地等著名景点。此外，杭州市还是中国电子商务和互联网产业的重要中心，阿里巴巴总部就位于杭州市。\n\n如果你需要更详细的信息，请告诉我。\n\n请介绍一下杭州的气候和地理特征\n\n杭州地处中国东南沿海地区，属于亚热带季风气候，四季分明，雨量充沛，气候温和湿润。杭州夏季炎热潮湿，冬季寒冷干燥，春秋季节气温适中，适合旅游和户外活动。\n\n杭州的地形以丘陵和平原为主，地势较为平坦，海拔高度较低。杭州境内有众多河流湖泊，其中最为著名的是西湖，它是中国最著名的湖泊之一，也是杭州市的标志性景点。此外，杭州还有钱塘江、富春江等河流，以及千岛湖、西溪湿地等自然保护区。\n\n杭州是一个现代化的城市，市区内高楼林立，交通便利，生活设施完善。同时，杭州也是一个历史悠久的文化名城，保留了许多古建筑和文化遗产，如灵隐寺、六和塔、南宋御街等。<|endoftext|>`
- sglang outputs: `杭州，简称“杭”，古称临安、钱塘，是浙江省省会、副省级市、杭州都市圈核心城市，国务院批复确定的浙江省省会和全省经济、文化、科教中心、长江三角洲中心城市之一。截至2019年，全市下辖10个区、2个县、代管
1个县级市，总面积16853.57平方千米，建成区面积648.46平方千米，常住人口1036万人，城镇人口813.26万人，城镇化率78.5%。杭州地处中国华东地区、钱塘江下游、东南沿海、浙江北部、京杭大运河南端，是环杭州湾大湾区核
心城市、沪嘉杭G60科创走廊中心城市、国际重要的电子商务中心。杭州人文古迹众多，西湖及其周边有大量的自然及人文景观遗迹，具代表性的有西湖文化、良渚文化、丝绸文化、茶文化，以及流传下来的许多故事传说。杭州自
秦朝设县治以来已有2200多年的历史，曾是吴越国和南宋的都城。因风景秀丽，素有“人间天堂”的美誉。杭州得益于京杭运河和通商口岸的便利，以及自身发达的丝绸和粮食产业，历史上曾是重要的商业集散中心。后来依托沪杭铁
路等铁路线路的通车以及上海在进出口贸易方面的带动，轻工业发展迅速。新世纪以来，随着阿里巴巴等高科技企业的带动，互联网经济成为杭州新的经济增长点。2018年世界短池游泳锦标赛、2022年杭州亚运会、2022年杭州亚运
会延期至2023年举行。2017年中国百强城市排行榜排第7位。2019年6月14日，杭州入选“2019中国最佳旅游目的地城市”。2019年8月，中国海关总署主办的《中国海关》杂志公布了2018年“中国外贸百强城市”排名，杭州排名第8。2019中国百强城市排行榜排第5位。2019年12月，杭州入选“2019中国最具幸福感城市”（第一名）。2020年1月，入选“中国城市科技创新发展指数2019”第5位。2020年3月，杭州被英国杂志《经济学人》评为全球最宜居城市排名第八位
。2020年4月，入选“2020中国避暑名城榜”。\n杭州历史沿革 杭州城的历史可以上溯到公元前3000年左右的良渚文化时期。良渚文化时期，人们已经开始生产稻米，种植蔬菜，饲养家畜，还制作陶器、玉器和石器等。良渚文化时期
的文化遗址，至今在杭州境内已发现50多处，其中良渚遗址、余杭区的茅山遗址、吴山遗址、钱山漾遗址等都是良渚文化时期的典型遗址。春秋时期，吴越两国争霸，杭州先属吴，越灭吴后，杭州又属越。战国时期，楚灭越后，杭
州又归入楚国的版图。秦始皇统一六国后，今杭州一带属会稽郡，郡治在吴县（今苏州）。汉朝时，杭州仍属会稽郡，东汉顺帝时分会稽郡为吴郡和会稽郡，杭州属会稽郡富春县。三国时属吴国，孙权把他的哥哥孙策之子孙绍封为
富春侯，把他的女儿许配给孙绍。吴黄龙年间（233—234年），孙权在富春县设立都尉府，都尉的官职相当于郡守，都尉府的设立，说明当时富春一带已成为吴国的一个军事重镇。东晋咸和元年（326年），杭州设立为钱唐县，隶于
扬州吴郡。南朝陈永定二年（558年），陈文帝废钱唐县设立钱塘郡，郡治仍在钱唐县，这是杭州设郡的开始。隋开皇九年（589年），隋文帝废钱塘郡，以原钱唐县的地域设立余杭县，县治仍在钱唐，这是杭州改名的开始。唐武德
四年（621年），唐高祖李渊又在余杭县设立钱塘郡，郡治仍在余杭县。唐天宝元年（742年），唐玄宗李隆基改钱塘郡为杭州，这是“杭州”得名的开始。杭州改名后，仍以余杭县为杭州的治所。杭州的建制在五代十国时期，经历了
吴越国和南宋两个朝代。五代十国时期，吴越国偏安东南，建都杭州。吴越国时期，杭州的城市规模进一步扩大，人口也进一步增加。吴越国的开国之君钱镠，对杭州的经济和文化发展也作出了贡献。他重视水利建设，兴修了浙江
、钱塘江、西湖等许多水利工程。他重视农业生产，组织人力在钱塘江沿岸修筑捍海石塘，有效地防止了海潮的入侵。他重视发展商业，鼓励商业贸易。五代十国时期，杭州的商业和手工业十分发达，市场繁荣，人口众多，成为全
国经济、文化中心之一。五代十国时期，杭州的丝织业、制瓷业、造纸业、印刷业等手工业都很发达，商业贸易也很兴盛。杭州的商业贸易，主要集中在河坊街、清河坊一带，那里是杭州的商业中心。杭州的商业贸易，主要以丝绸
、瓷器、茶叶、纸张、书籍等为主。五代十国时期，杭州的商业贸易，主要以河坊街、清河坊一带为中心。杭州的商业贸易，主要以丝绸、瓷器、茶叶、纸张、书籍等为主。五代十国时期，杭州的商业贸易，主要以河坊街、清河坊
一带为中心。杭州的商业贸易，主要以丝绸、瓷器、茶叶、纸张、书籍等为主。五代十国时期，杭州的商业贸易，主要以河坊街、清河坊一带为中心。杭州的商业贸易，主要以丝绸、瓷器、茶叶、纸张、书籍等为主。五代十国时期
，杭州的商业贸易，主要以河坊街、清河坊一带为中心。杭州的商业贸易，主要以丝绸、瓷器、茶叶、纸张、书籍等为主。五代十国时期，杭州的商业贸易，主要以河坊街、清河坊一带为中心。杭州的商业贸易，主要以丝绸、瓷器
、茶叶、纸张、书籍等为主。五代十国时期，杭州的商业贸易，主要以河坊街、清河坊一带为中心。杭州的商业贸易，主要以丝绸、瓷器、茶叶、纸张、书籍等为主。五代十国时期，杭州的商业贸易，主要以河坊街、清河坊一带为
中心。杭州的商业贸易，主要以丝绸、瓷器、茶叶、纸张、书籍等为主。五代十国时期，杭州的商业贸易，主要以河坊街、清河坊一带为中心。杭州的商业贸易，主要以丝绸、瓷器、茶叶、纸张、书籍等为主。五代十国时期，杭州
的商业贸易，主要以河坊街、清河坊一带为中心。杭州的商业贸易，主要以丝绸、瓷器、茶叶、纸张、书籍等为主。五代十国时期，杭州的商业贸易，主要以河坊街、清河坊一带为中心。杭州的商业贸易，主要以丝绸、瓷器、茶叶
、纸张、书籍等为主。五代十国时期，杭州的商业贸易，主要以河坊街、清河坊一带为中心。杭州的商业贸易，主要以丝绸、瓷器、茶叶、纸张、书籍等为主。五代十国时期，杭州的商业贸易，主要以河坊街、清河坊一带为中心。
杭州的商业贸易，主要以丝绸、瓷器、茶叶、纸张、书籍等为主。五代十国时期，杭州的商业贸易，主要以河坊街、清河坊一带为中心。杭州的商业贸易，主要以丝绸、瓷器、茶叶、纸张、书籍等为主。五代十国时期，杭州的商业
贸易，主要以河坊街、清河坊一带为中心。杭州的商业贸易，主要以丝绸、瓷器、茶叶、纸张、书籍等为主。五代十国时期，杭州的商业贸易，主要以河坊街、清河坊一带为中心。杭州的商业贸易，主要以丝绸、瓷器、茶叶、纸张
、书籍等为主。五代十国时期，杭州的商业贸易，主要以河坊街、清河坊一带为中心。杭州的商业贸易，主要以丝绸、瓷器、茶叶、纸张、书籍等为主。五代十国时期，杭州的商业贸易，主要以河坊街、清河坊一带为中心。杭州的
商业贸易，主要以丝绸、瓷器、茶叶、纸张、书籍等为主。五代十国时期，杭州的商业贸易，主要以河坊街、清河坊一带为中心。杭州的商业贸易，主要以丝绸、瓷器、茶叶、纸张、书籍等为主。五代十国时期，杭州的商业贸易，
主要以河坊街、`

### Reproduction

Launch sglang/vllm server and run inference.

### Environment

```Shell
Python: 3.11.2 (main, Mar 13 2024, 17:30:23) [GCC 10.2.1 20200825 (Alibaba 10.2.1-3.8 2.32)]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA H800
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.2, V12.2.91
CUDA Driver Version: 535.54.03

PyTorch: 2.3.0+cu121
sglang: 0.2.5
flashinfer: 0.1.2+cu121torch2.3
requests: 2.32.3
tqdm: 4.66.4
numpy: 1.26.4
aiohttp: 3.9.5
fastapi: 0.111.1
hf_transfer: Module Not Found
huggingface_hub: 0.24.2
interegular: 0.3.3
packaging: 24.1
pillow: Module Not Found
psutil: 6.0.0
pydantic: 2.7.4
uvicorn: 0.30.3
uvloop: 0.19.0
zmq: 26.0.3
vllm: 0.5.3.post1
openai: 1.38.0
anthropic: 0.32.0
litellm: Module Not Found
```
```

**Comment by zhyncs** [comment]
Hi @sighingnow You can use the method below, I've verified it and there's no problem.

```bash
python3 -m sglang.launch_server --model Qwen/Qwen2-57B-A14B-Instruct --tp 2
```

```bash
  curl http://127.0.0.1:30000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer EMPTY" \
  -d '{
    "model": "Qwen/Qwen2-57B-A14B-Instruct",
    "messages": [{"role": "user", "content": "请介绍一下杭州"}],
    "stream": false,
    "temperature": 0.7,
    "top_k": 20,
    "top_p": 0.8
  }' \
  --no-buffer
```

```
{"id":"6f5bd42d6fd44efb9454a583bb4c3cb5","object":"chat.completion","created":1722927945,"model":"Qwen/Qwen2-57B-A14B-Instruct","choices":[{"index":0,"message":{"role":"assistant","content":"杭州是中国浙江省的省会，位于中国东南沿海地区，是一个充满活力的现代化城市，也是历史文化名城。杭州拥有悠久的历史和丰富的文化遗产，是中国古代文化的发源地之一，被誉为“人间天堂”。\n\n杭州最著名的景点是西湖，它是中国最著名的湖泊之一，被誉为“天堂之镜”。西湖周围有许多名胜古迹，如断桥残雪、雷峰塔、苏堤春晓、花港观鱼等，吸引了无数游客前来观光旅游。\n\n除了西湖，杭州还有许多其他著名的景点和文化遗址，如灵隐寺、宋城、西溪湿地、中国茶叶博物馆等。此外，杭州还是中国电子商务的中心之一，阿里巴巴等知名互联网公司总部位于此地。\n\n杭州的气候属于亚热带季风气候，四季分明，春暖花开，夏热多雨，秋高气爽，冬冷干燥。杭州的美食也非常有名，如龙井虾仁、东坡肉、西湖醋鱼、叫化鸡等，是中国南方菜系的代表之一。\n\n总之，杭州是一个充满魅力的城市，无论是自然风光还是人文景观，都值得一游。"},"logprobs":null,"finish_reason":"FINISH_MATCHED_TOKEN: 151645"}],"usage":{"prompt_tokens":22,"total_tokens":258,"completion_tokens":236}}
```

**Comment by Ying1123** [comment]
#973 added support for all kinds of penalty

**Comment by sighingnow** [comment]
Thanks！
