### ISSUE TITLE
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

### ISSUE THREAD

**Issue by ChuanhongLi** [sgl-project/sglang#944]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

CUDA_VISIBLE_DEVICES=7 python -m sglang.launch_server --model-path /mnt/afs/data/model/open_source_data/Qwen/Qwen2-7B-Instruct --port 30000
server_args=ServerArgs(model_path='/mnt/afs/data/model/open_source_data/Qwen/Qwen2-7B-Instruct', tokenizer_path='/mnt/afs/data/model/open_source_data/Qwen/Qwen2-7B-Instruct', tokenizer_mode='auto', load_format='auto', dtype='auto', trust_remote_code=False, context_length=None, quantization=None, served_model_name='/mnt/afs/data/model/open_source_data/Qwen/Qwen2-7B-Instruct', chat_template=None, host='127.0.0.1', port=30000, additional_ports=[30001, 30002, 30003, 30004], mem_fraction_static=0.88, max_prefill_tokens=None, max_running_requests=None, max_num_reqs=None, max_total_tokens=None, schedule_policy='lpm', schedule_conservativeness=1.0, tp_size=1, stream_interval=1, random_seed=369954340, log_level='info', log_level_http=None, log_requests=False, show_time_cost=False, api_key=None, file_storage_pth='SGlang_storage', dp_size=1, load_balance_method='round_robin', chunked_prefill_size=None, disable_flashinfer=False, disable_flashinfer_sampling=False, disable_radix_cache=False, disable_regex_jump_forward=False, disable_cuda_graph=False, disable_disk_cache=False, enable_torch_compile=False, enable_p2p_check=False, enable_mla=False, attention_reduce_in_fp32=False, efficient_weight_load=False, nccl_init_addr=None, nnodes=1, node_rank=None)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Process Process-33:
Traceback (most recent call last):
  File "/usr/local/lib/miniconda3/envs/sglang/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/miniconda3/envs/sglang/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/afs/19110/lich/sglang/python/sglang/srt/managers/controller_single.py", line 150, in start_controller_process
    controller = ControllerSingle(
                 ^^^^^^^^^^^^^^^^^
  File "/mnt/afs/19110/lich/sglang/python/sglang/srt/managers/controller_single.py", line 84, in __init__
    self.tp_server = ModelTpServer(
                     ^^^^^^^^^^^^^^
  File "/mnt/afs/19110/lich/sglang/python/sglang/srt/managers/tp_worker.py", line 92, in __init__
    self.model_runner = ModelRunner(
                        ^^^^^^^^^^^^
  File "/mnt/afs/19110/lich/sglang/python/sglang/srt/model_executor/model_runner.py", line 99, in __init__
    torch.cuda.set_device(self.gpu_id)
  File "/usr/local/lib/miniconda3/envs/sglang/lib/python3.11/site-packages/torch/cuda/__init__.py", line 399, in set_device
    torch._C._cuda_setDevice(device)
  File "/usr/local/lib/miniconda3/envs/sglang/lib/python3.11/site-packages/torch/cuda/__init__.py", line 279, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

### Reproduction

I have installed sglang with pip,  and  also from source. When I ran  "CUDA_VISIBLE_DEVICES=7 python -m sglang.launch_server --model-path /mnt/afs/data/model/open_source_data/Qwen/Qwen2-7B-Instruct --port 30000", the same issue occured.

Try doing pip uninstall accelerate in https://github.com/sgl-project/sglang/issues/462 does not work for me.

Thanks for your help!

### Environment

```Shell
On NVIDIA A100-SXM4-80GB
```

**Comment by zhyncs** [comment]
For any environmental issues, my suggestion is to try using Docker. https://github.com/sgl-project/sglang?tab=readme-ov-file#method-3-using-docker

**Comment by ChuanhongLi** [comment]
> For any environmental issues, my suggestion is to try using Docker. https://github.com/sgl-project/sglang?tab=readme-ov-file#method-3-using-docker

Thanks! I'll have a try.
