### ISSUE TITLE
[Feature] Post link to paper in the README.md

### ISSUE THREAD

**Issue by horiacristescu** [sgl-project/sglang#946]
### Motivation

New users struggle to form a mental model of how sglang works, for example understanding how many rounds of interaction take place for a structured prompt, will the chat history be re-sent to the model and have to pay for the prefix again, and what works and what doesn't work with OpenAI vs local server?

I suggest you post the link to the paper "Efficiently Programming Large Language Models using SGLang" in the README.md as it covers most questions

### Related resources

https://arxiv.org/pdf/2312.07104v1

**Comment by zhyncs** [comment]
make sense

**Comment by zhyncs** [comment]
The README already has it now https://github.com/sgl-project/sglang?tab=readme-ov-file#citation-and-acknowledgment
