### ISSUE TITLE
is pip install difference with sourcecode install?

### ISSUE THREAD

**Issue by CSEEduanyu** [sgl-project/sglang#947]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

Will the performance be different with different installation methods?

### Reproduction

Will the performance be different with different installation methods?

### Environment

```Shell
A100
```

**Comment by zhyncs** [comment]
The main branch is our development branch, tags and PyPI are usually stable releases, that's all.
