### ISSUE TITLE
Problem with Installing sglang with cuda118

### ISSUE THREAD

**Issue by Vodkazy** [sgl-project/sglang#950]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

I install sglang in py310, cuda118 environment, pip install sglang[all], and cuda12-related packages will be installed by default, which is in conflict with my current environment. How do I install cuda118?

### Reproduction

pip install sglang[all]

### Environment

```Shell
cuda 118
py 3.10
```

**Comment by zhyncs** [comment]
@ispobock Help take a look at the issue with cu118.

**Comment by Vodkazy** [comment]
If possible, could you guys provide a special installation command guide for cuda118 like vllm

**Comment by ispobock** [comment]
@Vodkazy I solved this problem by reinstalling the related dependencies with cu118 version.
For example:
```
# pytorch
pip3 install torch==2.3.1 --index-url https://download.pytorch.org/whl/cu118

# flashinfer
pip3 install flashinfer==0.1.3 --index-url https://flashinfer.ai/whl/cu118/torch2.3
```
