### ISSUE TITLE
[Bug] sglang可以在A6000上使用吗？对服务器显卡有要求吗？

### ISSUE THREAD

**Issue by yawzhe** [sgl-project/sglang#952]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

glang可以在A6000上使用吗？对服务器显卡有要求吗？

### Reproduction

glang可以在A6000上使用吗？对服务器显卡有要求吗？

### Environment

```Shell
glang可以在A6000上使用吗？对服务器显卡有要求吗？
```

**Comment by zhyncs** [comment]
The main support is A100, L40s, H100. A6000 is also supported. For sm70 sm75, it is recommended to use `--disable-flashinfer --disable-flashinfer-sampling`, for sm80+ it is recommended to use FlashInfer.
