### ISSUE TITLE
[Bug] Multinode cannot be started on runpod

### ISSUE THREAD

**Issue by Desmond819** [sgl-project/sglang#958]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

Hi, I try to run a multi-node following the instructions for 2 machine with 8x4090 each. But it just stopped at "Init nccl begin" without further progress.
<img width="1523" alt="image" src="https://github.com/user-attachments/assets/3ed8af47-d512-42de-9222-33bb545ca05c">

### Reproduction

Node 1:
GLOO_SOCKET_IFNAME=eth0 pm2 start /root/miniconda3/envs/sgl/lib/python3.11/site-packages/sglang/launch_server.py --name sgl -- --model-path NousResearch/Meta-Llama-3.1-8B-Instruct --nccl-init-addr xxx:xxx --nnodes 2 --node-rank 0 --tp-size 16 --schedule-conservativeness 0.01 --mem-fraction-static 0.8
Node 2:
GLOO_SOCKET_IFNAME=eth0 pm2 start /root/miniconda3/envs/sgl/lib/python3.11/site-packages/sglang/launch_server.py --name sgl -- --model-path NousResearch/Meta-Llama-3.1-8B-Instruct --nccl-init-addr xxx:xxx --nnodes 2 --node-rank 1 --tp-size 16 --schedule-conservativeness 0.01 --mem-fraction-static 0.8

### Environment

```Shell
N/A
```

**Comment by zhyncs** [comment]
export NCCL_P2P_LEVEL=NVL

**Comment by Desmond819** [comment]
Thanks, but it's still stuck at the same step.

**Comment by Desmond819** [comment]
got error after waiting for a while.
torch.distributed.DistNetworkError: The client socket has timed out after 600s while trying to connect to (xxx, xxx).

I am running GPU on runpod. The internal and extern port is different.

**Comment by Ying1123** [comment]
Could you try adding `--disable-cuda-graph` and `--disable-flashinfer-sampling`?

**Comment by merrymercy** [comment]
`export NCCL_DEBUG=INFO`
what is the output?

**Comment by Desmond819** [comment]
still same, stuck at "Init nccl begin". I am using runpod, how should I set the ip and port?

**Comment by merrymercy** [comment]
likely a runpod issue or a configuration issue, not an sglang issue
