### ISSUE TITLE
I got an error when I gave the parameters.

### ISSUE THREAD

**Issue by 0nur0duncu** [sgl-project/sglang#972]
image: lmsysorg/sglang:latest
python3 -m sglang.launch_server --model-path NousResearch/Meta-Llama-3.1-8B-Instruct --port 8000 --tp 2 --dp 2 --schedule-conservativeness 0.3 --max-prefill-tokens 10000 --mem-fraction-static 0.7 --max-running-requests 1000 --schedule-policy lpm --quantization fp8 --enable-p2p-check --context-length 8192 --host 0.0.0.0 --max-total-tokens 300000

[gpu=0] Load weight end. type=LlamaForCausalLM, dtype=torch.bfloat16, avail mem=18.64 GB
[gpu=1] Load weight end. type=LlamaForCausalLM, dtype=torch.bfloat16, avail mem=18.64 GB
[gpu=0] Memory pool end. avail mem=15.42 GB
[gpu=1] Memory pool end. avail mem=15.42 GB
[gpu=0] Capture cuda graph begin. This can take up to several minutes.
[gpu=1] Capture cuda graph begin. This can take up to several minutes.
[gpu=1] max_total_num_tokens=50000, max_prefill_tokens=10000, max_running_requests=1000, context_len=8192
[gpu=0] max_total_num_tokens=50000, max_prefill_tokens=10000, max_running_requests=1000, context_len=8192
Exception in run_tp_server:
Traceback (most recent call last):
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 858, in run_tp_server
    model_server = ModelTpServer(
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 92, in __init__
    self.model_runner = ModelRunner(
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 99, in __init__
    torch.cuda.set_device(self.gpu_id)
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 399, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by 13140438775** [comment]
使用--dp 2参数需要足够的GPU   这个错误是指GPU设备不足   你可以试试--tp 1 --dp 2 --mem-fraction-static 0.5

**Comment by Ying1123** [comment]
@13140438775 seems to be correct. It seems you do not have enough GPUs.

**Comment by 0nur0duncu** [comment]
thx guys
