### ISSUE TITLE
On NVIDIA GeForce RTX 4090, is sglang supported for deploying models with tp >1?

### ISSUE THREAD

**Issue by ChuanhongLi** [sgl-project/sglang#991]
root@localhost:/sgl-workspace/sglang/python# CUDA_VISIBLE_DEVICES=4,5 python3 -m sglang.launch_server --model-path /workspace/sdb/models/QWen/Qwen2-7B-Instruct/ --tp 2
server_args=ServerArgs(model_path='/workspace/sdb/models/QWen/Qwen2-7B-Instruct/', tokenizer_path='/workspace/sdb/models/QWen/Qwen2-7B-Instruct/', tokenizer_mode='auto', load_format='auto', dtype='auto', trust_remote_code=False, context_length=None, quantization=None, served_model_name='/workspace/sdb/models/QWen/Qwen2-7B-Instruct/', chat_template=None, host='127.0.0.1', port=30000, additional_ports=[30001, 30002, 30003, 30004], mem_fraction_static=0.87, max_prefill_tokens=None, max_running_requests=None, max_num_reqs=None, max_total_tokens=None, schedule_policy='lpm', schedule_conservativeness=1.0, tp_size=2, stream_interval=1, random_seed=729541709, log_level='info', log_level_http=None, log_requests=False, show_time_cost=False, api_key=None, file_storage_pth='SGlang_storage', dp_size=1, load_balance_method='round_robin', chunked_prefill_size=None, disable_flashinfer=False, disable_flashinfer_sampling=False, disable_radix_cache=False, disable_regex_jump_forward=False, disable_cuda_graph=False, disable_disk_cache=False, enable_torch_compile=False, enable_p2p_check=False, enable_mla=False, attention_reduce_in_fp32=False, efficient_weight_load=False, nccl_init_addr=None, nnodes=1, node_rank=None)
[gpu=0] Init nccl begin.
[gpu=1] Init nccl begin.
Failed: Cuda error /workspace/csrc/custom_all_reduce.cuh:307 'peer access is not supported between these two devices'
Failed: Cuda error /workspace/csrc/custom_all_reduce.cuh:307 'peer access is not supported between these two devices'
[rank1]:[W CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
[rank0]:[W CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]

**Comment by Ying1123** [comment]
Yes, it is supported. Add `--enable-p2p-check`
https://github.com/sgl-project/sglang/blob/228cf47547a3d2f7f38f636f40a5e85b0c3cd646/README.md?plain=1#L142
