### ISSUE TITLE
[Feature] Inference speed difference between sglang and vllm is smaller than advertised

### ISSUE THREAD

**Issue by IAMZn1018** [sgl-project/sglang#998]
### Motivation

I compared the inference speed of two large model inference frameworks. I found that sglang is only about 30% faster than vllm, which is much lower than the claimed 3.8 times speedup.

Below are my environment details, prompt, and inference results.
my environment：
gpu:4090*1
cuda:12.4
Python:3.11.0
vllm:0.5.3
sglang:0.2.7

launch command:
`python -m vllm.entrypoints.openai.api_server --model /home/modeldata/Qwen2-1.5B-Instruct --port 8899`
`python -m sglang.launch_server --model-path /home/modeldata/Qwen2-1.5B-Instruct --host 0.0.0.0 --port 30000`

prompt:
`请根据用户反馈，仔细思考标准答案构成要素，并改写出5句答案\n你是直播真人问答客服，为避免客服回答的答案重复度过高，请你逐句思考并改写问题的答案。\n****************\n#样例\n用户问题：声音好好听\n参考的问答对：["问题: 声音好好听, 答案: 谢谢宝宝的夸奖，喜欢主播的可以点个关注", "问题: 你是真人吗, 答案: 什么，你说我是不是真人", "问题: 没有红包吗, 答案: 红包左上角都会安排的", "问题: 拍啦, 答案: 好的感谢支持咱家玉米"]\n输出格式：["感谢你的夸赞支持", "你的夸赞是我前进的动力", "收到你的夸奖，心情美美哒", "夸奖收到，谢谢宝宝的热情", "你的夸奖我收到了，谢谢"]\n\n****************\n#规则（必须严格遵循）\n1、你的答案必须仿照改写用户觉得满意的答案\n2、你的答案绝对不能按照用户不满意答案的写法。\n3、必须给出和用户反馈的数据中改写答案，但是不能改变句义\n如果问题涉及包邮的需要注意：偏远地区不包邮，偏远地区包含：新疆、西藏、宁夏、内蒙古、甘肃、青海\n涉及价格的数字不能出错！！\n\n#要求（必须严格遵循）\n1、不能改变句义，不能随意*增删改*答案当中的主体，口语化一点，答案符合口播场景\n2、答案中涉及数字的一定不能改变数字大小！！\n3、输出格式必须用 list列表["", "", "", "", ""]只能出现一个列表, 否则我们取不到答案\n\n#输入\n已知用户的问题是：*黄的好吃白的好吃*\n参考的问答：我们玉米，黄的更甜，白的更糯\n\n#输出`

code:
`%%time

sglang_result = []
for p in tqdm(prompt):
    url = "http://localhost:30000/v1/chat/completions"
    
    data = {
            "model": "/home/modeldata/Qwen2-7B-Instruct",
            "messages": [
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": p},
            ],
            "max_tokens": 512,
            "temperature": 0.7,
            "top_p": 0.8
        }
    
    sglang_result.append(requests.post(url, json=data).json())`
![image](https://github.com/user-attachments/assets/bcea5975-de1e-4d91-97b6-afbd15d5dcf6)

 I look forward to your response.

**Comment by zhyncs** [comment]
@IAMZn1018  First, we tested the Llama 3 or 3.1 series, and secondly, the smallest model size we used is 8B, not the Qwen2 1.5B you mentioned here. Lastly, we used A100 80G or H100 80G devices for our tests. All test results are [reproducible](https://github.com/sgl-project/sglang/tree/main/benchmark/blog_v0_2). The data in the [blog](https://lmsys.org/blog/2024-07-25-sglang-llama3/) is entirely as expected. I don't understand what you mean by your title. The data and conclusions are not exaggerated in any way. I hope this answers your question.

**Comment by IAMZn1018** [comment]
> @IAMZn1018 First, we tested the Llama 3 or 3.1 series, and secondly, the smallest model size we used is 8B, not the Qwen2 1.5B you mentioned here. Lastly, we used A100 80G or H100 80G devices for our tests. All test results are [reproducible](https://github.com/sgl-project/sglang/tree/main/benchmark/blog_v0_2). The data in the [blog](https://lmsys.org/blog/2024-07-25-sglang-llama3/) is entirely as expected. I don't understand what you mean by your title. The data and conclusions are not exaggerated in any way. I hope this answers your question.

I am not questioning your test results. I am merely stating the situation I encountered and hoping to find the cause and solve it. At first, I also thought it was due to the model's parameters being too small, so I tested the qwen7b model, and the inference speed was similar.
我不是质疑你们的测试结果，我只是说明我遇到的情况，并且希望能够找到原因并且解决。我刚开始也觉得是模型参数太小的原因，所以我测了qwen7b的模型，推理速度上也是差不多的

**Comment by zhyncs** [comment]
>  I found that sglang is only about 30% faster than vllm, which is much lower than the claimed 3.8 times speedup.

Your conclusion is based on your model and test scenario, while the blog's conclusions come from its models, test scenarios, and device types. I believe they are **NOT EQUIVALENT**. You can check ModelScope's results for reference. https://mp.weixin.qq.com/s/kDOpaVSECJ8NyapSPKpQIA

**Comment by zhyncs** [comment]
Additionally, I noticed that you have very few test prompts(only 38 items) and the method for sending requests differs from what was described in the blog.

**Comment by merrymercy** [comment]
You can add `--enable-torch-compile` when you launch the sglang server, it will be much faster.

It seems you only test batch size = 1, but we typically test the throughput under the maximum batch size. Please follow the above links to reproduce our benchmark.

**Comment by dionren** [comment]
在线推理的速度，原本就不是差距太大，你这都20%的差距了，非常不错了。两者差距大的好像原本就是在离线跑大batch上。我大致测下来，在线推理，相同的TPOT，sglang大概多20%的throughput吧。

**Comment by IAMZn1018** [comment]
> 在线推理的速度，原本就不是差距太大，你这都20%的差距了，非常不错了。两者差距大的好像原本就是在离线跑大batch上。我大致测下来，在线推理，相同的TPOT，sglang大概多20%的throughput吧。

我跟你的测试结论一致

**Comment by merrymercy** [comment]
Thanks for reporting your results. Close this for now.
